embox/embox

- .travis.yml
> travis: Add Coverity Scan addon

- README.md
Mostly moved from the legacy Wiki: http://code.google.com/p/embox/w/edit/GettingStarted
Cc: @anton-bondarev
> README: Add Getting Started guide

- src/cmds/games/race.c
- src/kernel/lthread/lthread.h
- src/kernel/sched/strategy/runq/list_array.c
- src/pnet/net_entry.c
- Fix buildbot failing because of lthread
- Make resume and yield functions inline.
> Lthread minor

- src/net/inetdev.c
> fix inetdev_get_first

- platform/stm32f4_iocontrol/cmds/flash_settings.c
Quick resolution of not working dfs-based flash settings
> Ledbox settings quickfix

- platform/ti816x_net_filter/templates/chip1/build.conf
- platform/ti816x_net_filter/templates/chip2/build.conf
@anton-bondarev check this please
> Remove platform from netfilter templates

- src/net/socket/af_inet.c
Fix ping after raw_socket_test (clear IP_HDRINCL).
> net: Fix inet_init(), clear socket options

- src/cmds/hardware/lsusb/Mybuild
- src/cmds/hardware/lsusb/lsusb.c
- src/drivers/net/Mybuild
- src/drivers/net/usbnet.c
- src/drivers/usb/class/usb_class_cdc.c
- src/drivers/usb/class/usb_class_hid.c
- src/drivers/usb/hc/ohci.h
- src/drivers/usb/hc/ohci_pci.c
- src/drivers/usb/usb_class.c
- src/drivers/usb/usb_core.c
- src/drivers/usb/usb_pnp.c
- src/include/drivers/usb/usb_cdc.h
- templates/x86/usbnet/build.conf
- templates/x86/usbnet/lds.conf
- templates/x86/usbnet/mods.config
- templates/x86/usbnet/start_script.inc
Purpose: Obtain ping between Embox and Linux through usbnet driver.
What 's done:
- Added usbnet (Ethernet over USB) driver
- Added USB CDC class
> usbnet driver

- src/drivers/usb/hc/ohci.h
- src/drivers/usb/hc/ohci_pci.c
- src/drivers/usb/usb_core.c
- src/drivers/usb/usb_port.c
- src/drivers/usb/usb_whitelist_dev.c
Some fixes in usb and ohci.
Not everything is ready (#774, #775) but this makes things much better
> Usb hardening

- src/framework/mod/Mybuild
- src/framework/mod/embuild_light_impl.h
Fix a couple logger defects that make build fail
> Logger fix

- src/cmds/net/Telnetd.my
- src/drivers/input/keyboard/Mybuild
Fix some template which broken after moving headers and cleaning Mybuild files
> Fix template

- mk/image3.mk
- mk/main.mk
> Disable piggy build target by default

- mk/gensums.py
- mk/image2.mk
- mk/image3.mk
- mk/script/lds-apps.mk
- src/cmds/module/Lsmod.my
- src/cmds/module/lsmod.c
- src/framework/mod/Mybuild
- src/framework/mod/core.c
- src/include/framework/mod/api.h
- src/include/framework/mod/embuild.h
- src/include/framework/mod/types.h
- src/include/framework/test/self.h
- src/tests/framework/mod/Mybuild
- src/tests/framework/mod/integrity_test.c
Module integrity check (text & rodata)
> Integrity check

- src/drivers/block_dev/block_dev.c
- src/drivers/net/tun.c
- src/drivers/usb/usb_whitelist_dev.c
- src/fs/driver/ext2/ext2.c
- src/fs/driver/ext3/ext3.c
- src/fs/driver/ext4/ext4.c
- src/fs/driver/fat/fat.c
- src/fs/driver/initfs/initfs.c
- src/fs/driver/initfs/initfs_dvfs.c
- src/fs/driver/iso9660/cdfs.c
- src/fs/driver/jffs2/jffs2.c
- src/fs/driver/nfs/nfs.c
- src/fs/driver/power_save/inode.c
- src/fs/driver/power_save/qnx6.c
- src/fs/driver/ramfs/ramfs.c
- src/fs/driver/tmpfs/tmpfs.c
- src/fs/dvfs/dvfs.h
- src/fs/syslib/kfile.c
- src/include/fs/file_operation.h
Remove using stdarg in the kernel
> Change ioctl signature in file_operation structure

- src/include/embox/net/pack.h
- src/net/Mybuild
- src/net/l0/Mybuild
- src/net/l0/net_rx.c
- src/net/l0/net_tx.c
- src/net/l3/Mybuild
- src/net/l3/arp.c
- src/net/l3/icmpv4.c
- src/net/l3/icmpv6.c
- src/net/l3/ipv6/Mybuild
- src/net/l3/ipv6/ip6_input.c
- src/net/l3/ipv6/ip6_output.c
- src/net/l3/rarp.c
- src/net/l4/Mybuild
- src/net/l4/tcp.c
- src/net/lib/Mybuild
- src/net/lib/dns.c
- src/net/neighbour.c
- src/net/skb.c
- src/net/socket/tcp_sock.c
It's just a **draft** PR because I haven't finished building the environment for Embox developing yet.
Code has been written just in Sublime.
Build has been completed with `make confload-arm/qemu`.
Please check at first, is it what did you mean)
And please don't be afraid to make cruel CR's)
> Change net logger

- src/arch/arm/cortexa8/mmu.c
- src/drivers/clock/omap3_clk.c
- src/drivers/clock/raspi_systick.c
- src/drivers/interrupt/omap3_intc.c
- src/drivers/interrupt/raspi.c
- src/drivers/serial/ns16550.c
- src/mem/vmem/vmem_device_memory.c
Also minor fix for mmap_device_memory() flags
> Add exec/cache flags for vmem pages

- src/drivers/block_dev/ide/ide_drive.c
Refactor and fix to use non-hardcoded block size
> Ide rework

- src/cmds/fs/Mkfs.my
- src/cmds/fs/mkfs.c
- src/drivers/block_dev/Mybuild
- src/drivers/block_dev/block_dev.h
- src/drivers/block_dev/block_dev_common.c
- src/drivers/block_dev/ide/harddisk_dma.c
- src/drivers/block_dev/ide/harddisk_pio.c
- src/drivers/block_dev/ide/ide_drive.c
- src/drivers/block_dev/ide/partition.c
- src/drivers/block_dev/ramdisk/ramdisk_dvfs.c
- src/drivers/block_dev/stm32_sd/stm32f4_sd.c
- src/fs/driver/devfs/devfs_dvfs.c
- src/fs/driver/fat/Mybuild
- src/fs/driver/fat/fat.c
- src/fs/driver/fat/fat.h
- src/fs/driver/fat/fat_common.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/dvfs/compat.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs.h
- templates/x86/dvfs/mods.config
- templates/x86/dvfs/start_script.inc
* FAT FS now supports FAT32 formatting
* mkfs now works with dvfs
* ramdisk minor fixes
* Refactor, eliminating dead code, etc.
> Vfat rework

- src/fs/Mybuild
- src/fs/dvfs/dvfs_util.c
Fix error on mount with flag -Os
> Stm32f4 dvfs fixes

- src/fs/driver/dfs/Mybuild
- src/fs/driver/dfs/dfs.c
- src/fs/driver/dfs/dfs.h
- src/fs/dvfs/dvfs.c
Implemented long files in dumb fs.
File could be extended iff it's latest file. Also a number of options is moved to Mybuild from constants.
Minor refactor/optimization/etc
> DumbFS extended files

- src/compat/posix/fs/dvfs/dirent.c
- src/compat/posix/fs/dvfs/fsop.c
- src/fs/driver/dfs/dfs.c
- src/fs/driver/dfs/dfs.h
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs.h
Now DumbFS supports subdirectories
> Dumbfs directories

- src/cmds/fs/Mkdir.my
- src/cmds/fs/mkdir.c
- src/compat/posix/fs/dvfs/fsop.c
- src/fs/dvfs/dvfs.c
* Add "-v" option for creating virtual directories
* Fix minor issues
> Mkdir fixes

- src/drivers/serial/stm_usart.c
Add uart's interrupt support on stm32f4discovery.
Note: only dynamical case, without STATIC_IRQ (it's not very easy to do)
> uart: Enable irq for stm32 uart

- src/cmds/fs/mv.c
- src/compat/libc/stdio/Mybuild
- src/compat/libc/stdio/rename_dvfs.c
- src/compat/posix/fs/dvfs/fsop.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/dvfs/dvfs.h
- src/fs/dvfs/dvfs_dentry.c
- src/fs/dvfs/dvfs_xattr.c
Implement following POSIX calls for new VFS
* truncate()
* rename()
> POSIX calls for new VFS

- src/mem/mmap/mmap_nommu.c
Remove some dead code. The rest of problems of #628  is outdated.
> Fix issue #628 

- src/fs/driver/fat/fat_dvfs.c
Now return error on some invalid sectors
> fatfs: Improve FS detection

- src/drivers/block_dev/ramdisk/ramdisk.h
- src/drivers/block_dev/ramdisk/ramdisk_dvfs.c
Handle some ramdisk problems
* Use given name, not hdr#
* Store index and free resources properly on delete
> Ramdisk name

- src/cmds/fs/df/df.c
- src/compat/posix/fs/statvfs/statvfs.c
- src/compat/posix/fs/statvfs/statvfs.h
- src/fs/driver/devfs/devfs_dvfs.c
- src/fs/driver/dvfs_driver.c
- src/fs/driver/initfs/initfs_dvfs.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs.h
- src/fs/dvfs/dvfs_dentry.c
Change mount sequence
Change fill_sb() routines in initfs and devfs drivers for dvfs
Improove 'df' command and statvfs() syscall
> Statvfs dvfs fat

- src/cmds/fs/File.my
- src/cmds/fs/file.c
- src/cmds/fs/mkfs.c
- src/cmds/fs/mount.c
- src/compat/libc/stdio/Mybuild
- src/compat/posix/fs/dvfs/Mybuild
- src/fs/Mybuild
- src/fs/driver/fat/Mybuild
- src/fs/driver/initfs/Mybuild
- src/fs/dvfs/Mybuild
- src/fs/dvfs/dvfs.h
- src/fs/file_format.c
- src/fs/file_format.h
- src/kernel/task/resource/Mybuild
- templates/arm/stm32_modbus/mods.config
- templates/x86/dvfs/mods.config
Implement simple file format detection (right now uses simple check for RIFF file format)
> File format

- src/arch/Mybuild
- src/arch/arm/armlib/Mybuild
- src/arch/arm/armlib/mem_barriers.S
- src/arch/arm/armlib/mem_barriers.h
- src/drivers/mailbox/Mybuild
- src/drivers/mailbox/bcm2835_mailbox.c
- src/drivers/mailbox/bcm2835_mailbox.h
- src/drivers/power/Mybuild
- src/drivers/power/bcm2835_power.c
- src/drivers/power/bcm2835_power.h
- src/drivers/usb/hc/Mybuild
- src/drivers/usb/hc/usb_dwc.c
- src/drivers/usb/hc/usb_dwc.h
- src/drivers/usb/usb_class.c
- src/drivers/usb/usb_core.c
- src/drivers/usb/usb_driver.c
- src/drivers/video/Mybuild
- src/drivers/video/raspi_video.c
- src/include/drivers/usb/usb.h
- src/include/drivers/usb/usb_desc.h
- src/include/drivers/usb/usb_hid.h
- src/include/hal/mem_barriers.h
- templates/arm/raspi/mods.config
This PR includes:
- Initial version of the USB driver for RPi
- Moved mailbox and memory barriers outside of the video driver, because they
are used also for other purposes
Note: currently the USB is not working. The controller does not send
interrupts after setup.
> 704 raspberry usb

- src/arch/arm/armlib/Mybuild
- src/arch/arm/armlib/static_excpt_table.S
- templates/arm/nxt_bt_pnet/mods.config
Add implimentation of setup_exception_table for static table
> arch: Fix 'nxt_bt_pnet' template

- src/cmds/net/bootpc.c
- src/include/net/l3/route.h
- src/include/net/lib/bootp.h
- src/net/l3/route.c
- src/net/lib/bootp.c
- templates/x86/bootpc/build.conf
- templates/x86/bootpc/lds.conf
- templates/x86/bootpc/mods.config
- templates/x86/bootpc/start_script.inc
Fix 'bootpc' requesting address from 'busybox' 'udhcpd' and refactoring bootpc & bootp lib
> Bootpc-dhcp

- scripts/app_diff.sh
That is a problem to remember how to create a patch for a third-party application :)
There is my own script which I use to make this task.
> scripts: Add script to create a patch for third-party applications

- src/compat/posix/util/getopt_long.c
- templates/x86/smp/mods.config
Fix x86/smp and x86/test/packetdrill
> waterfall fix

- src/tests/kernel/Mybuild
- src/tests/kernel/timer_test.c
Check problem reported in issue #606
> (test) timer_test: Set/unset mutex in handler

- src/cmds/fs/Chmod.my
- src/cmds/fs/chmod.c
- src/compat/posix/fs/Mybuild
- src/compat/posix/fs/chmod_old.c
- src/compat/posix/fs/dvfs/Mybuild
- src/compat/posix/fs/dvfs/chmod.c
- src/compat/posix/include/sys/stat.h
What's done:
* syscall chmod() is added for both of old and new fs's
* chmod cmd is posix now
It's an open question how to sync an inode's data/metadata with a storage during execution of chmod(), but currently we leave that as is.
> Dvfs chmod

- src/drivers/net/ti816x/ti816x.c
Correct processing rx_desc flags (some isn't errors)
> driver: Update ti816x.c driver

- src/compat/libc/assert/Mybuild
- src/compat/libc/assert/assert.c
Now pseudo-picture can be disabled
> assert: Add option for banner print

- platform/stm32f3_agents/cmds/Mybuild
- platform/stm32f3_agents/cmds/transmitter.c
- platform/stm32f3_agents/libcomm/communication.h
- src/drivers/serial/stm32_usart/Mybuild
- src/drivers/serial/stm32_usart/hal_msp_f3.c
- src/drivers/serial/stm32_usart/stm32_usart_conf_f3.h
1. Fix tranismitter to work with multiple agents.
2. Add support for USART2 and USART3 for stm32f3
> stm32f3 agents

- src/cmds/fs/chown/chown.c
- src/cmds/net/ping.c
- src/net/skb.c
Fix ping command issues & chown build for -O2
> Ping cmd fix

- src/cmds/fs/ls.c
make failed, could not cast size_t to int
> fixed macos make error

- scripts/qemu/auto_qemu
- src/drivers/net/lan91c111/Mybuild
- src/drivers/net/lan91c111/lan91c111.c
- src/drivers/net/pattern/Mybuild
- src/drivers/net/pattern/ethernet_pattern.c
- src/include/util/dlist.h
- src/net/Mybuild
- src/net/skbuff/Mybuild
- src/security/seculog/Mybuild
- src/security/smac/Mybuild
- templates/arm/integratorcp/build.conf
- templates/arm/integratorcp/mods.config
Implement LAN91C111 driver for IntegratorCP ethernet card.
Also update arm/integratorcp template
> Integrator cp ethernet

- scripts/qemu/auto_qemu
- src/arch/arm/cortexa9/Mybuild
- src/arch/arm/cortexa9/cpu_reset.S
- src/drivers/clock/Mybuild
- src/drivers/clock/cortexa9_timer.c
- src/drivers/diag/no_diag.c
- src/drivers/interrupt/Mybuild
- src/drivers/interrupt/cortex_a9_gic/Mybuild
- src/drivers/interrupt/cortex_a9_gic/cortex_a9_gic.c
- src/drivers/interrupt/cortex_a9_gic/cortex_a9_gic.h
- src/drivers/interrupt/no_interrupts.c
- src/drivers/serial/imx_uart/Mybuild
- src/drivers/serial/imx_uart/imx_uart.c
- src/kernel/sched/Mybuild
- src/kernel/sched/boot_thread.c
- src/kernel/sched/idle_thread.c
- src/kernel/sched/sched.c
- src/tests/kernel/timer_test.c
- templates/arm/imx6/build.conf
- templates/arm/imx6/lds.conf
- templates/arm/imx6/mods.config
- templates/arm/vexpress-a9/build.conf
- templates/arm/vexpress-a9/lds.conf
- templates/arm/vexpress-a9/mods.config
Enable cortex-a9 sub-arch and two chips base on it (imx6 and vexpres-a9)
> Imx6 porting

- src/cmds/service.c
Add volatile keyword to srv_cmd_ready_flag
> service: Add volatile to the waiting flag

- .travis.yml
See https://launchpad.net/gcc-arm-embedded/+announcement/13824
> Fix gcc-arm-embedde ppa and package name

- src/drivers/net/ti816x/Mybuild
- src/drivers/net/ti816x/ti816x.c
- src/drivers/usb/usb_whitelist_dev.c
> Update ti816x net driver

- src/drivers/console/vc/vc.c
- src/kernel/syscall/syscall.c
- templates/x86/user_apps/mods.config
> 954 fix x86 user apps

- src/compat/posix/net/getaddrinfo.c
- src/tests/posix/netdb/getaddrinfo_test.c
> Fix getaddrinfo

- src/compat/posix/include/sys/mman.h
- src/mem/mmap/mmap_userspace.c
- src/mem/vmem/Mybuild
- src/mem/vmem/mmap.c
- src/mem/vmem/vmem_device_memory.c
- src/tests/mem/Mybuild
- src/tests/mem/mmap.c
- templates/x86/qemu/mods.config
Implemented a wrap for pages allocation calls.
Please review the code and I'll continue to work on it.
> Anonymous mmap

- src/cmds/hardware/pin/pin.c
More error messages. More int conversion checking. @Deryugin
> Rewrite `pin` utility.

- src/kernel/task/multi.c
When a task died its children became orphans. To solve this problem we simply attach each orphan to the kernel task (like in unix).
> task: Make children of a died task daemons

- src/cmds/fs/mkfs.c
- src/framework/cmd/core.c
- src/framework/mod/core.c
- src/framework/mod/embuild_light_impl.h
- src/framework/runlevel.c
- src/framework/test/registry.c
- src/fs/driver/devfs/devfs_dvfs.c
- src/fs/driver/dfs/dfs.c
- src/fs/driver/dvfs_driver.c
- src/fs/driver/ext2fuse/ext2fuse.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/driver/fs_driver.c
- src/fs/driver/initfs/initfs_dvfs.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs.h
- src/fs/dvfs/dvfs_util.c
- src/fs/fuse/fuse_linux.c
- src/fs/fuse/fuse_module_linux.h
- src/fs/rootfs_dvfs.c
- src/include/framework/cmd/api.h
- src/include/framework/mod/api.h
- src/include/framework/mod/embuild.h
- src/include/framework/test/api.h
- src/include/fs/fs_driver.h
- src/include/kernel/task/resource.h
- src/include/kernel/time/clock_source.h
- src/kernel/task/task_resource.c
- src/kernel/time/clock_source.c
Change all spread arrays with pointer types to view ARRAY_SPREAD_DEF(const mytype * const) as suggested in issue #958
> 958 add const array spread def

- src/cmds/Service.my
- src/cmds/service.c
- templates/arm/qemu/mods.config
- templates/x86/qemu/mods.config
Now use `vfork()` to run services.
> Work on Service

- src/drivers/net/Mybuild
- src/drivers/net/fec/Mybuild
- src/drivers/net/fec/fec.c
- src/drivers/net/greth.c
- src/drivers/net/lan91c111/Mybuild
- src/drivers/net/lan91c111/lan91c111.c
- src/drivers/net/mipsnet/Mybuild
- src/drivers/net/mipsnet/mipsnet.c
- src/drivers/net/ne2k/Mybuild
- src/drivers/net/ne2k/ne2k.c
- src/drivers/net/stm32cube/Mybuild
- src/drivers/net/stm32cube/stm32cube_eth.c
- src/net/util/Mybuild
- src/net/util/show_packet.h
Remove duplicated code that shows content of the IP packet #969
> Ip show packet

- src/compat/posix/fs/statvfs/statvfs.c
- src/compat/posix/include/sys/mman.h
- src/compat/posix/sys/mman/Mybuild
- src/compat/posix/sys/mman/msync.c
- third-party/qpid/Mybuild
- third-party/qpid/qpid_embox_compat.h
- third-party/samba_ext/Mybuild
> Samba extbld

- mk/flags.mk
- src/cmds/net/iptables.c
- src/cmds/net/netmanager.c
- src/cmds/net/netstat.c
- src/cmds/net/telnetd.c
- src/compat/posix/curses/curses.c
- src/compat/posix/net/inet_addr.c
- src/drivers/char/terminal/vtparse.c
- src/include/kernel/spinlock.h
- src/include/kernel/task/resource/vfs.h
- src/include/util/bit.h
- src/kernel/task/resource/sig_table.c
- src/profiler/tracing/cyg_profile.h
Some warnings detected by clang compiler are fixed.
> Clang minifixes

- src/compat/posix/pwd_grp/pwd_grp.c
- src/mem/vmem/vmem_nommu.h
- templates/x86/qt-app/mods.config
- third-party/qt/tree/src/plugins/platforms/emboxvc/emboxvcwindowsurface.cpp
Template qt-app got back to life.
> Embox qt template

- src/arch/arm/mmu/Mybuild
- src/arch/arm/mmu/mmu_common.c
- src/arch/arm/mmu/mmu_small_page.c
- src/include/mem/vmem.h
- src/kernel/task/multi.c
- src/kernel/task/resource/mmap.c
- src/kernel/thread/stack_protect.c
- src/mem/mmap/mmap_mmu.c
- src/mem/vmem/vmem_mapper.c
- src/mem/vmem/vmem_unmapper.c
- src/tests/kernel/thread/stack_protect_test.c
- src/tests/mmu/mmu_core.c
- src/tests/mmu/mmu_double_map.c
Fix problems with 2-level MMU model (specially, for ARM).
> MMU improve

- src/arch/arm/armlib/exception_table.S
- src/drivers/serial/el24d1/Mybuild
- src/drivers/serial/el24d1/el24d1.c
- templates/arm/el24d2/build.conf
- templates/arm/el24d2/lds.conf
- templates/arm/el24d2/mods.config
- templates/arm/el24d2/start_script.inc
Appropriate template was created, UART was implemented, addresses for GIC/GPT were added, some minor issues were fixed
> el24d1 porting

- platform/pjsip/templates/arm-qemu/build.conf
- platform/pjsip/templates/arm-qemu/mods.config
- scripts/qemu/auto_qemu
- src/drivers/audio/aaci_pl041/Mybuild
- src/drivers/audio/aaci_pl041/aaci_pl041.c
- src/drivers/audio/aaci_pl041/aaci_pl041.h
- src/drivers/audio/ac97/ac97.h
- src/drivers/audio/intel8x0/intel8x0.c
- src/drivers/audio/portaudio/Mybuild
- src/drivers/audio/portaudio/portaudio_lib.c
- templates/arm/vexpress-a9/build.conf
Developed sound card driver.
For testing 
make confload-platform/pjsip/arm-qemu
make
./scripts/qemu/auto_qemu
embox#play -s
> 982 aaci pl041 soundcard

- platform/pjsip/templates/x86-qemu/lds.conf
- platform/pjsip/templates/x86-qemu/mods.config
- platform/pjsip/templates/x86-qemu/start_script.inc
- src/cmds/play.c
- src/cmds/record/Mybuild
- src/cmds/record/record.c
- src/drivers/audio/audio_dev.c
- src/drivers/audio/audio_dev.h
- src/drivers/audio/es1370/es1370.c
- src/drivers/audio/intel8x0/intel8x0.c
- src/drivers/audio/portaudio/Mybuild
- src/drivers/audio/portaudio/portaudio_info.c
- src/drivers/audio/portaudio/portaudio_lib.c
- src/drivers/audio/portaudio/portaudio_stub.c
- src/drivers/block_dev/ramdisk/Mybuild
- src/drivers/block_dev/ramdisk/ramdisk.c
- src/fs/driver/ramfs/Mybuild
- src/fs/driver/ramfs/ramfs.c
- src/fs/file_format.h
- src/fs/file_system.c
- src/mem/pagealloc/bitmask.c
- src/mem/vmem/vmem_alloc.c
Finally, microphone is working for qemu-x86.
> pjsip improve

- templates/arm/overo/mods.config
Fix arm/overo template (with lan9118 net driver)
> templates: Fix arm/overo

- COPYRIGHT
> Change copyright years (2017)

- src/cmds/net/netmanager.c
- src/cmds/net/ping.c
- src/net/l0/net_rx.c
- src/net/l0/net_tx.c
- src/net/l3/icmpv4.c
> 1015 fix ping localhost

- src/drivers/net/loopback.c
`net_tx` updates TX statistics.
> drivers: (loopback) Fix TX statistics

- src/include/sys/cdefs.h
- templates/arm/stm32f4cube_clang/build.conf
- templates/arm/stm32f4cube_clang/lds.conf
- templates/arm/stm32f4cube_clang/mods.config
- templates/arm/stm32f4cube_clang/start_script.inc
- third-party/lib/libgcc/Mybuild
- third-party/lib/openlibm/Makefile
> Clang porting stm32cube

- src/drivers/net/fec/fec.c
- src/drivers/net/fec/fec.h
- src/include/net/mii.h
- templates/arm/imx6/mods.config
Fix arm/imx6 template network
Starting MII support
> Working on 'fec' ethernet driver

- scripts/app_diff.sh
- templates/x86/debug/mods.config
- templates/x86/qt-app/mods.config
- third-party/lib/nuklear/Makefile
- third-party/lib/nuklear/Mybuild
- third-party/lib/nuklear/patch.txt
Add ['nuklear'](https://github.com/vurtun/nuklear) gui library to third-party
fix debug & qt-app x86 templates
Update app_diff.sh
> Nuklear porting

- src/compat/posix/fs/Mybuild
- src/compat/posix/proc/Proc.my
- src/compat/posix/util/Util.my
- src/fs/Mybuild
- src/fs/dvfs/Mybuild
- src/fs/syslib/Mybuild
- src/kernel/task/resource/Mybuild
- src/mem/mmap/Mybuild
- src/net/l3/Mybuild
- src/profiler/tracing/Mybuild
- src/security/seculog/Mybuild
Remove some annoying tsort-loop message
> Tsort loop break

- scripts/qemu/auto_qemu
- src/mem/vmem/vmem_alloc.c
- src/mem/vmem/vmem_nommu.h
- templates/x86/debug/mods.config
Improve auto_qemu script for graphical templates
> Vga template improve

- mk/extbld/toolchain.mk
- templates/mips/qemu/build.conf
- templates/mips/qemu/lds.conf
> Workaround mips gcc bug of soft/hard float mixed

- src/cmds/module/Lsmod.my
- src/cmds/module/lsmod.c
- src/framework/mod/Mybuild
- src/framework/mod/core.c
- src/framework/mod/mod_integrity.c
- src/include/framework/mod/api.h
- src/include/framework/mod/integrity.h
> Move mod_integrity to separate module

- platform/stm32f4_multibots/templates/nrf24/mods.config
- platform/stm32f7/templates/stm32f7_discovery/mods.config
- src/drivers/net/stm32cube/Mybuild
- src/drivers/net/stm32cube/stm32cube_eth.c
- src/drivers/net/stm32cube/stm32f4cube_eth.c
- src/drivers/net/stm32cube/stm32f4cube_eth.h
- src/drivers/net/stm32cube/stm32f7cube_eth.c
- src/drivers/net/stm32cube/stm32f7cube_eth.h
- templates/arm/stm32f4cube/mods.config
- templates/arm/stm32f4cube_clang/mods.config
- templates/arm/stm32f7cube/lds.conf
- templates/arm/stm32f7cube/mods.config
- templates/arm/stm32f7cube/start_script.inc
- third-party/bsp/stmf7cube/Mybuild
- third-party/bsp/stmf7cube/arch.c
Enable eth on stm32f7-disco board
> Stm32cube eth rework

- platform/pjsip/templates/arm-qemu/mods.config
- src/drivers/clock/Mybuild
- src/drivers/clock/cortexa9_timer.c
- templates/arm/el24d2/mods.config
- templates/arm/imx6/mods.config
- templates/arm/iwave_imx6/mods.config
- templates/arm/vexpress-a9/mods.config
Now frequency can be configure via module config
> Work on MPCore timer

- src/drivers/serial/Mybuild
- src/drivers/serial/imx_uart/imx_uart.c
Fix uart-tty config and imx-uart driver
> Fix TTY-devfs

- platform/stm32f7/templates/stm32f7_discovery/mods.config
- src/cmds/user/Login.my
- src/drivers/video/fb_videomodes.c
- src/drivers/video/stm32f7_lcd/Mybuild
- src/drivers/video/stm32f7_lcd/stm32f7_lcd.c
Implement FB driver for STM32F7 board.
> STM32f7 FB driver

- src/net/l3/route.c
> Fixed route command.

- third-party/bsp/stmf3cube/Makefile
- third-party/bsp/stmf4cube/Makefile
- third-party/bsp/stmf7cube/Makefile
Switch remote storage to dropbox instead of doogle drive
> Stm32cube download links

- src/arch/arm/include/asm/hal/mmu.h
- src/arch/arm/mmu/mmu_small_page.c
- src/drivers/cache/pl310/Mybuild
- src/drivers/cache/pl310/pl310.c
- src/drivers/cache/pl310/pl310.h
- src/drivers/net/fec/fec.c
- templates/arm/imx6/mods.config
- templates/arm/iwave_imx6/mods.config
- templates/arm/vexpress-a9/mods.config
Working on ARMv7 cache subsystem
Some fix in fec ethernet driver
> Pl310 cache controller

- src/drivers/block_dev/ramdisk/Mybuild
- src/drivers/block_dev/ramdisk/ramdisk.c
- src/drivers/block_dev/ramdisk/ramdisk_dvfs.c
- src/drivers/block_dev/sdhc/Mybuild
- src/drivers/block_dev/sdhc/sdhc.c
- src/fs/driver/devfs/devfs_dvfs.c
- src/fs/driver/fat/fat_common.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs_util.c
- src/include/hal/reg.h
- templates/arm/sabrelite/mods.config
- templates/arm/sabrelite/readme
Initial implementation of SDHC driver which works on QEMU.
This branch also fixes a number of minor issues:
- vfat driver issues
- ramdisk issues
- some dvfs bugs
> Add SDHC support for QEMU

- CONTRIBUTING.md
Better late than never.
Closes #721.
> contributing: Add initial version of the guide

- mk/flags.mk
- src/drivers/block_dev/partition/partition.c
- src/fs/driver/tmpfs/tmpfs.c
Is it possible to change compiler flags only for single source file in project?
What does `-Wno-gnu-designator` mean? GCC says it doesn't know such option
> Trying to fix GCC 7 build errors

- src/drivers/tty/termios_ops.c
- src/drivers/tty/termios_ops.h
- src/drivers/tty/tty.c
- src/include/drivers/tty.h
Full description of the task:
https://trello.com/c/fNVYQQt3/10-tty-termios
> Termios processing was separated from tty

- .gitignore
- Vagrantfile
Vagrant file, more info in https://github.com/embox/embox/wiki/Xen-port-workflow
> Add vagrant defintion for xen dev vm

- third-party/lib/nuklear/Makefile
- third-party/lib/stb/Makefile
- third-party/lib/stb/Mybuild
Add stb-image.h required for nuklear examples
> Port stb framework

- mk/extbld/toolchain.mk
- platform/pjsip/templates/stm32f4discovery/mods.config
- src/compat/posix/proc/Proc.my
- src/drivers/interrupt/cortexm_nvic.c
Fix build of pjsip/stm32f4discovery template
> Fix template pjsip/stm32f4discovery

- src/compat/posix/fs/dvfs/dirent.c
- src/compat/posix/include/dirent.h
- src/drivers/video/stm32f7_lcd/Mybuild
- src/drivers/video/stm32f7_lcd/stm32f7_lcd.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs_util.c
* Fix image depth while draw images
* Fix VFS
> stm32f7 fixes

- mk/flags.mk
- platform/mesa/cmds/osdemo_fb/osdemo_fb.c
- platform/mesa/templates/integratorcp/build.conf
- platform/mesa/templates/integratorcp/lds.conf
- platform/mesa/templates/integratorcp/mods.config
- platform/mesa/templates/integratorcp/rootfs/network
- platform/mesa/templates/integratorcp/start_script.inc
- platform/mesa/templates/integratorcp/system_start.inc
- src/compat/atomic/pseudo_atomic/Mybuild
- src/compat/atomic/pseudo_atomic/pseudo_atomic.c
- src/drivers/video/pl110/Mybuild
- src/drivers/video/pl110/pl110.c
- third-party/freedesktop/mesa/mesa/mesa_x86_osmesa/Makefile
* Fix some ARM-related buildsystem issues (passing flags etc.)
* Implement PL110/PL111 driver (close #983)
* Add template for MESA on arm/integratorcp
* Minor MESA-related fixes
* Add support for pseudo-atomic operations for compatibility with arm-none-eabi-gcc (which for some reason doesn't have builtin atomic operation support)
> Add support for arm/integratorcp graphics

- src/arch/arm/mmu/Mybuild
- src/arch/arm/mmu/mmu.h
- src/arch/arm/mmu/mmu_common.c
- src/arch/arm/mmu/mmu_small_page.c
- templates/arm/qemu/mods.config
This commits fix vmem for integratorcp platform.
> ARM v5 MMU tables

- src/drivers/video/pl110/pl110.c
- templates/arm/qemu/mods.config
> Fix arm/qemu templates

- platform/mesa/templates/mesa_imx6/build.conf
- platform/mesa/templates/mesa_imx6/mods.config
- src/compat/atomic/pseudo_atomic/pseudo_atomic.c
- src/compat/libc/stdlib/bsearch.c
- templates/arm/iwave_imx6/build.conf
Add flags and change template so it's possible to run MESA demo on i.MX6 via LVDS
> i.MX6 MESA support

- third-party/lib/nuklear/patch.txt
Add aligment for nk_color structure for stm32f7 platform
> third-party: Update nuklear patch

- src/drivers/video/Mybuild
- src/drivers/video/bochs.c
- src/drivers/video/cirrus_logic.c
- src/drivers/video/fb.c
- src/drivers/video/fb.h
- src/drivers/video/generic.c
- src/drivers/video/pl110/pl110.c
- src/drivers/video/stm32f7_lcd/stm32f7_lcd.c
- src/init/graphic_init.c
Add color format for video subsystem
> Fb improve

- platform/mesa/cmds/osdemo_fb/Mybuild
- platform/mesa/cmds/osdemo_fb/osdemo_fb.c
- platform/mesa/cmds/osdemo_fb/text_layout.c
New version of 3D MESA test.
Changes:
* Add animation (scene is rotating clockwise)
* Add frame rate counter at the upper left corner of the screen
* Autodetect image bit depth based on video driver preferences
* Add a number of flags for command (number of bits per pixel can be passed as parameter, static scene can be drawn instead of animation, help can be printed)
> osdemofb 0.2

- src/arch/x86/kernel/smp/smp.c
- src/arch/x86/lib/ptregs_jmp.S
- src/cmds/shell/tish.c
- src/compat/posix/proc/exec.c
- src/compat/posix/proc/fork_nommu/fork.c
- src/compat/posix/proc/fork_nommu/fork_addr_space.c
- src/compat/posix/proc/fork_nommu/fork_addr_space_heap.c
- src/compat/posix/proc/fork_nommu/fork_addr_space_stack.c
- src/compat/posix/proc/fork_nommu/fork_addr_space_static.c
- src/compat/posix/proc/fork_nommu/fork_copy_addr_space.h
- src/drivers/tty/termios_ops.c
- src/drivers/tty/termios_ops.h
- src/drivers/tty/tty.c
- src/kernel/thread/core.c
- src/kernel/thread/thread_switch.c
- src/tests/posix/vfork_test.c
- templates/x86/qemu/mods.config
- templates/x86/qemu/start_script.inc
- third-party/dash/Makefile
- third-party/dash/include/fnmatch.h
- third-party/dash/include/sys/param.h
Finally, fork() without MMU works :)
> Fix fork() without MMU

- src/net/skbuff/skb_data.c
These changes revert 3107afe030b1c56e82cf648d2d3a977238401610 which is partially wrong since all huge packets are dropped.
This also fixes template x86/qt-vnc
> net: Fix skb allocation

- Vagrantfile
- scripts/xen/run_xen
- templates/xen/debug/build.conf
1. Fix diag output
2. Add gdbsx to Vagrant
> Xen improve

- src/arch/xen/Mybuild
- src/arch/xen/include/COPYING
- src/arch/xen/include/barrier.h
- src/arch/xen/include/xenstore.h
- src/arch/xen/kernel_init.c
- src/arch/xen/xenstore.c
- templates/xen/debug/mods.config
1. Breakpoint on 49 line of src/arch/xen/kernel_init.c
2. Continue
3. print list
4. got: `$1 = "EACCES\000\000\362\313\000\000\363\313\000\000\364\313\000\000\365\313\000\000\000\000\000\000 \00 0\000"`
> Added basic xenstore support

- src/arch/arm/mmu/mmu_common.c
- src/drivers/net/emac/emac.c
- src/drivers/net/emac/emac.h
- src/drivers/net/emac/emac_mdio.c
Handle auto negotiation correctly
> emac: Enable correct 10/100mpbs handle

- src/arch/arm/lib/debug/stack_iter.c
- src/arch/sparc/lib/debug/stack_iter.c
- src/arch/x86/lib/debug/stack_iter.c
- src/lib/debug/whereami.c
Now it works for Integrator/CP and Cortex-A9
> Fix backtrace for ARM

- src/cmds/testing/ticker/Mybuild
- src/cmds/testing/ticker/ticker.c
- templates/arm/vexpress-a9/mods.config
Add 'ticker' command
Update arm/vexpress-a9 template
- Fix timer frequency
- Fix /dev/ttyS0 irq number
> Implement ticker command

- .travis.yml
- src/cmds/shell/Mybuild
- templates/microblaze/debug/mods.config
- templates/microblaze/qemu/mods.config
- templates/ppc/qemu/mods.config
- third-party/lib/openlibm/Makefile
- third-party/lib/openlibm/patch.txt
Fix templates sparc/microblaze/ppc qemu
Enable support ppc to openlibm
> Fix archs build

- src/arch/arm/embox.lds.S
- src/drivers/flash/stm32f4/Mybuild
- templates/arm/omap/build.conf
- templates/arm/omap/mods.config
- templates/arm/stm32_dvfs/mods.config
- templates/arm/stm32_modbus/mods.config
- templates/arm/stm32_vl_light/mods.config
Fix build for following templates:
- arm/stm32_vl_light
- arm/omap
- arm/stm32_dvfs
- arm/stm32_modbus
> Templates fix

- platform/pjsip/templates/stm32f4discovery/mods.config
> templates: Fix compilation pjsip/stm32f4discovery

- platform/stm32f3_sensors/cmds/motor_control.c
- platform/stm32f3_sensors/libactuators/motor.c
- platform/stm32f3_sensors/libactuators/motor.h
- platform/stm32f3_sensors/libsensors/gyro.c
- platform/stm32f3_sensors/templates/car/mods.config
- platform/stm32f3_sensors/templates/car/start_script.inc
The small vehicle now works somehow, not very well, but works.
> Fix stm32f3 vehicle

- src/arch/arm/armmlib/exception_handlers.c
Improve cortex-m exception info: Print out also MemManage and Bus fault address registers
> cortex-m: Add additional information about exceptions

- src/mem/vmem/Mybuild
- src/mem/vmem/mmap.c
- src/tests/mem/mmap.c
The most significant change is implementation for Idesc-specific `mmap()`.
> A bunch of fixes for memory-related functions

- platform/mesa/templates/mesa_x86_osmesa/build.conf
- platform/nuklear/templates/x86_qemu/build.conf
- templates/arm/omap-qt/build.conf
- templates/arm/omap-qt/mods.config
- templates/arm/ti816x-qt/build.conf
- templates/arm/ti816x-qt/mods.config
- templates/x86/qt-app/build.conf
- templates/x86/qt-vnc/build.conf
Add CXXFLAGS += -Wno-error=c++14-compat for some templates
> Cpp14 templates fix

- src/compat/cxx/core/new.cpp
- src/compat/cxx/include/standalone_new
Suppress some warnings to fit g++ 8.2.0
> gxx-8-compat

- src/cmds/help.c
- src/cmds/net/arping.c
- src/cmds/net/ifconfig.c
- src/cmds/net/telnetd/telnetd.c
- src/cmds/service.c
- src/cmds/wc.c
- src/compat/libc/string/strndup.c
- src/compat/libc/time/ctime.c
- src/drivers/block_dev/block_dev.h
- src/drivers/input/mouse/ps_mouse.c
- src/drivers/serial/uart_dev.c
- src/drivers/serial/uart_device.h
- src/fs/driver/ext4/ext4.c
- src/fs/driver/nfs/nfs.c
- src/fs/driver/nfs/nfs.h
- src/fs/vfs.c
- src/net/util/macaddr.c
- src/security/seculog/seculog.h
- src/tests/stdio/printf_test.c
* Fix `cmd/fs/wc`
* Fix a bunch of issues related to -O2 + GCC 8
> Fix -O2 builds

- src/drivers/block_dev/Mybuild
> Decrease default block dev quantity

- src/compat/libc/include/stdlib.h
- src/drivers/gpmc/Mybuild
- src/drivers/gpmc/omap_gpmc.c
- src/drivers/gpmc/omap_gpmc.h
- src/drivers/interrupt/omap3_intc/omap3_intc.c
- src/drivers/mtd/nand/Mybuild
- src/drivers/mtd/nand/gpmc_nand/Mybuild
- src/drivers/mtd/nand/gpmc_nand/gpmc_nand.c
- src/drivers/mtd/nand/nand.c
- src/drivers/mtd/nand/nand.h
- src/drivers/mtd/opennand/Mybuild
- src/drivers/mtd/opennand/opennand.h
- src/drivers/net/emac/Mybuild
- src/drivers/net/emac/emac.c
- src/drivers/net/emac/emac.h
- src/drivers/net/emac/emac_desc.h
- src/drivers/net/emac/emac_mdio.c
- src/drivers/serial/ns16550/Mybuild
- src/drivers/serial/ns16550/ns16550.c
- src/include/drivers/gpmc.h
- src/include/kernel/thread/types.h
- src/kernel/thread/Mybuild
- src/mem/vmem/Mybuild
- src/mem/vmem/mmap.c
- src/net/l3/ipv4/ip_fragment.c
- templates/arm/ti816x-qt/mods.config
- templates/arm/ti816x-qt/start_script.inc
- templates/arm/ti816x/mods.config
* Fix ti816x templates
* Fix ip fragmentation
* Fix ti emac net drivers
* Fix some omap drivers
> Ti816x improve

- templates/x86/test/net/mods.config
- templates/x86/test/net/start_script.inc
This is it. Just a little fix for new dropbear.
> x86/test/net: (template) modified for dropbear-2018

- templates/arm/stm32_vl/mods.config
- third-party/bsp/st_discovery_vl/Makefile
Fix build for `arm/stm32_vl` template
> template: Fix build stm32_vl

- src/arch/arm/armlib/exceptions/exception_handler.c
- templates/arm/minimal/build.conf
- templates/arm/minimal/lds.conf
- templates/arm/minimal/mods.config
- templates/x86/minimal/build.conf
- templates/x86/minimal/lds.conf
- templates/x86/minimal/mods.config
Add two minimal templates for x86 and arm.
> Minimal generic template

- src/include/mem/heap_bm.h
- src/mem/heap/heap_bm.c
- src/mem/heap/mspace_malloc.c
- src/tests/mem/heap/Mybuild
- src/tests/mem/heap/heap_bm_test.c
- src/tests/mem/heap/heap_extended_test.c
* Fix heap_extended_test
* Add realloc test
* Add heap_bm_test
> Malloc tests

- mk/image.lds.S
- src/cmds/msleep/msleep.c
- src/cmds/sys/Date.my
- src/cmds/sys/date.c
- src/compat/libc/stdio/Mybuild
- src/kernel/time/timer.c
During work on xen port in branch `xen18` a bunch of changes was made. They are not related to xen itself. So making a separate PR for them.
> General changes from xen18 branch

- .travis.yml
- src/drivers/console/fbcon.c
Fix issue #1292 and add x86/qt-app template to travis build
> Fix x86/qt-app template

- src/drivers/video/fb_devfs/fb_devfs_old.c
> Fix build for fb_devfs_old

- src/arch/e2k/Mybuild
- src/arch/e2k/e2k_interrupt.c
- src/arch/e2k/embox.lds.S
- src/arch/e2k/entry.c
- src/arch/e2k/include/asm/io.h
- src/arch/e2k/include/asm/ptrace.h
- src/arch/e2k/ipl_impl.h
- src/arch/e2k/kernel_entry.S
- src/drivers/clock/e2k/Mybuild
- src/drivers/clock/e2k/e2k.c
- src/drivers/interrupt/apic/lapic_regs_e2k.h
- templates/e2k/monocube/mods.config
- templates/e2k/monocube/start_script.inc
* Implement interrupts and exceptions handling
* ticker command now works on e2k
> Interrupt controller for e2k

- src/cmds/net/Netmanager.my
- src/cmds/net/telnetd/Telnetd.my
- src/drivers/net/fec/fec.c
- src/drivers/net/phy/phy.c
* Fix FEC RX operation
* Optimize PHY for faster autonegotiation
> Fix FEC driver

- scripts/continuous/fs/run.sh
- scripts/expect/fs_shell_commands_test.exp
- scripts/expect/fs_unit_tests.exp
- src/arch/arm/mmu/mmu_common.c
- src/cmds/testing/memtest/Mybuild
- src/cmds/testing/memtest/memtest.c
- src/include/mem/vmem.h
- src/kernel/task/resource/Mybuild
- src/kernel/task/resource/mmap_trivial.c
- src/lib/exec/Mybuild
- src/mem/vmem/vmem_mapper.c
- src/tests/mem/Mybuild
- templates/arm/var_som_mx6/mods.config
* Add implementation for `task.resource.mmap` to use single context for all tasks
* Add simple utility to measure memory performance
* Minor ARM-related fixes
> Fix some MMU issues

- src/drivers/usb/usb_whitelist_dev.c
- templates/x86/qt-app/mods.config
- templates/x86/qt-vnc/mods.config
- third-party/STLport/Makefile_cmake
- third-party/STLport/Mybuild
- third-party/STLport/include/stl/config/_embox.h
- third-party/STLport/stl_demo/algo/Mybuild
- third-party/STLport/stl_demo/algo/algostuff.hpp
- third-party/STLport/stl_demo/algo/sort1.cpp
- third-party/boost/Mybuild
- third-party/freedesktop/mesa/mesa/mesa_sw/Mybuild
- third-party/lib/openlibm/impl.h
- third-party/pjproject/Mybuild
- third-party/qpid/Makefile
- third-party/qpid/Mybuild
- third-party/qt/Makefile
- third-party/qt/Mybuild
- third-party/zeromq/Makefile
- third-party/zeromq/Mybuild
- Fix openlibm c++ compilation
- Fix usb_whitelist_dev after char_dev rework
- Use extbld script in STLport
- Add simple demo for STL using
> Stlport to extbld

- platform/etnaviv/templates/imx6/mods.config
- platform/mesa/templates/integratorcp/mods.config
- platform/mesa/templates/mesa_imx6/mods.config
- platform/mesa/templates/mesa_x86_osmesa/mods.config
- platform/nuklear/templates/arm_qemu/mods.config
- platform/quake3/templates/qemu/mods.config
- src/cmds/testing/fb_devfs_access/Mybuild
- src/cmds/testing/fb_devfs_access/fb_devfs_access.c
- src/cmds/testing/fb_direct_access/Mybuild
- src/cmds/testing/fb_direct_access/fb_direct_access.c
- templates/arm/iwave_imx6/mods.config
- templates/arm/iwave_imx6_etnaviv/mods.config
- templates/arm/sk_imx6q/mods.config
- templates/arm/var_som_mx6/mods.config
Also clean code and add missing dependencies.
> Move FB tests to embox.cmd.testing package

- src/drivers/serial/stm32_usart/stm32_usart_conf_f3.h
- src/drivers/serial/stm32_usart/stm32_usart_conf_f4.h
- src/drivers/serial/stm32_usart/stm32_usart_conf_f7.h
- src/drivers/serial/stm32_usart/stm_usart_cube_diag.c
- templates/arm/stm32f3cube/mods.config
- templates/arm/stm32f7cube/build.conf
Fix STM32 diag overruns.
Also fix builds for arm/stm32f7cube, arm/stm32f3cube
> Fix stm32 diag

- src/arch/e2k/context.c
- src/arch/e2k/context.h
- src/arch/e2k/context_switch.S
- templates/e2k/monocube/mods.config
* Fix build
* Do not use SBR register since it's not actually required for non-mmu mode.
> Fix some e2k issues

- platform/mesa/templates/mesa_imx6/build.conf
- platform/mesa/templates/mesa_imx6/mods.config
- platform/pjsip/templates/arm-qemu/build.conf
- src/drivers/char/char_dev_stub.c
- src/drivers/char/char_dev_stub.h
- src/drivers/tty/serial/Mybuild
- src/drivers/usb/usb_whitelist_dev.c
- src/fs/driver/devfs/devfs.c
- src/fs/dvfs/dvfs.c
- src/mem/mmap/mmap_nommu.h
- third-party/bsp/stmf7cube/Mybuild
Fix following templates
* arm/overo
* arm/qemu (-O2)
* arm/stm32f7cube (-O2)
* arm/sabrelite (-O2)
* arm/ti816x (-O2)
* Bunch of arm-related platforms
> Fix builds for some ARM platforms

- src/cmds/net/telnetd/telnetd.c
- src/drivers/audio/aaci_pl041/aaci_pl041.c
- src/drivers/char/char_dev.h
- src/drivers/usb/usb_whitelist_dev.c
- src/drivers/video/fb_devfs/fb_devfs_old.c
- third-party/freedesktop/mesa/mesa/mesa_sw/Mybuild
> Fix some builds

- src/cmds/sys/Env.my
- src/cmds/sys/env.c
Behavior is similar to GNU coreutils variant of env.
> cmds: env: Add ability to run program in modified environment

- src/arch/e2k/context.c
- src/arch/e2k/e2k_syscall_handler.c
- src/arch/e2k/entry.c
- src/arch/e2k/include/asm/io.h
- src/arch/e2k/include/e2k_api.h
- src/arch/e2k/include/va-e2k.h
- src/compat/libc/stdio/scanf.c
- src/drivers/clock/e2k/e2k.c
- src/drivers/interrupt/apic/ioapic.c
- src/drivers/interrupt/apic/ioapic_regs_e2k.h
- src/drivers/interrupt/apic/lapic_regs_e2k.h
- src/drivers/pci/pci_chip/pci_chip_elbrus.c
- src/drivers/serial/am85c30/am85c30.c
- src/drivers/video/fb.c
- src/drivers/video/lynxfb/ddk750_chip.h
- src/framework/test/run.c
- src/fs/driver/devfs/devfs_dvfs.c
- src/include/framework/test/assert.h
- src/include/kernel/spinlock.h
- src/mem/mmap/mmap_nommu.c
- src/mem/mmap/mmap_nommu.h
- src/tests/util/array_test.c
- src/tests/util/tree_test.c
- templates/e2k/monocube/build.conf
- templates/e2k/monocube/mods.config
* Clean e2k compilation flags
* Clean some e2k code
* Fix some code where pointers casting to integer types (It's incorrect for not 32 bits platforms перевод)
> E2k clean build

- src/compat/libc/include/inttypes.h
Fix PRId32 macro for some arch
> compat: Improve inttypes.h

- mk/image2.mk
- src/arch/arm/embox.lds.S
- src/tests/c++/exceptions.cpp
- third-party/STLport/stl_demo/algo/sort1.cpp
- third-party/gcc/Makefile
- third-party/lib/libsupcxx_toolchain/include/exception
* Fix gcc compiler segfaults when compiling with C++ exceptions
* Fix GCC and STL demo builds with new compiles
* Several small c++ fixes
> Fix arm cxx

- src/arch/arm/mmu/mmu_small_page.c
- src/drivers/clock/Mybuild
- src/drivers/clock/omap3_clk/omap3_clk.c
- src/drivers/clock/raspi_systick.c
- src/drivers/gpmc/Mybuild
- src/drivers/video/Mybuild
* Fix arm/overo
* Fix arm/bpi
* Fix arm/raspi
> Fix builds

- src/include/util/priolist.h
- src/net/lib/ntp.c
- src/util/priolist.c
Workarounds for accessing packed structures.
> Fixes for arm-none-eabi-gcc 9

- src/arch/mips/embox.lds.S
- src/compat/libc/include/inttypes.h
- src/compat/libc/math/math_builtins.c
- src/compat/libc/math/math_builtins.h
- templates/mips/qemu/build.conf
- templates/mips/qemu/lds.conf
- templates/mips/qemu/mods.config
Enable building with mips-linux-gnu-gcc
> Improve mips/qemu

- src/fs/dvfs/Mybuild
Remove annoying warning on build.
> dvfs: Fix dependency for rootfs

- src/drivers/gpu/drm/etnaviv/Mybuild
- src/drivers/gpu/drm/etnaviv/etnaviv_dev.c
Enable clocks before powering GPU up.
> etnaviv: Fix ininialization sequence

- scripts/app_diff.sh
Add support for various tar formats and zip, add ability to specify patches to apply before.
> scripts: Improve app_diff.sh

- src/cmds/bootloader/Goto.my
- src/cmds/bootloader/goto.c
Simple command to execute code from specified memory location
> cmds/goto: Initial implementation

- platform/opencv/cmds/version.cpp
- platform/opencv/templates/stm32f7discovery/build.conf
- platform/opencv/templates/stm32f7discovery/lds.conf
- platform/opencv/templates/stm32f7discovery/mods.config
- platform/opencv/templates/stm32f7discovery/readme
- third-party/bsp/stmf7cube/Mybuild
- third-party/lib/opencv/Makefile
- third-party/lib/opencv/Mybuild
- third-party/lib/opencv/patch.txt
Create OpenCV template for STM32F7Discovery
> OpenCV port for STM32 F7 Discovery

- src/fs/syslib/idesc_mmap/idesc_mmap.c
- templates/x86/qt-fb/build.conf
- templates/x86/qt-fb/lds.conf
- templates/x86/qt-fb/mods.config
- templates/x86/qt-fb/start_script.inc
- third-party/qt/plugins/platforms/Emboxfb.my
- third-party/qt/tree/src/plugins/platforms/emboxfb/emboxfb.pro
- third-party/qt/tree/src/plugins/platforms/emboxfb/emboxfbintegration.cpp
- third-party/qt/tree/src/plugins/platforms/emboxfb/emboxfbintegration.h
- third-party/qt/tree/src/plugins/platforms/emboxfb/main.cpp
New qt platform plugin which uses framebuffer only. It is helpful since emboxvc plugin is complex and messy.
> qt: Add new emboxfb plugin

- src/drivers/video/pl110/Mybuild
- src/drivers/video/pl110/pl110.c
- templates/arm/qt-fb-small/build.conf
- templates/arm/qt-fb-small/lds.conf
- templates/arm/qt-fb-small/mods.config
- templates/arm/qt-fb-small/start_script.inc
- templates/arm/qt-fb-small/system_start.inc
- templates/x86/qt-vnc/start_script.inc
- templates/x86/test/qt-vnc/start_script.inc
- third-party/qt/Makefile
- third-party/qt/Mybuild
- third-party/qt/pkg_patch_for_qconfig.txt
- third-party/qt/qconfig-small.txt
* Add Qt small build
* Fix pl110 video driver to specify display width/height
> Qt arm minimal

- src/include/kernel/task.h
- src/kernel/task/task_no_table.h
> Task foreach single

- Vagrantfile
- scripts/xen/gold_linux/README
- scripts/xen/gold_linux/alpine.cfg
- scripts/xen/gold_linux/run_alpine
- src/cmds/net/httpd/Makefile
- src/cmds/net/httpd/README
Modified httpd Makefile (start static build by specifying STATIC variable)
Modified VM (Vagrantfile) and domU (alpine.cfg) configs: allocate more memory
> Added guide for start nginx on domU

- src/cmds/fs/Uniq.my
- src/cmds/fs/uniq.c
- templates/x86/qemu/mods.config
> uniq: add utility uniq

- third-party/bsp/stmf3cube/Makefile
- third-party/bsp/stmf4cube/Makefile
- third-party/bsp/stmf7cube/Makefile
- third-party/e2fsprogs/Makefile
- third-party/fuse/ext2fuse/Makefile
- third-party/fuse/fuse/Makefile
- third-party/iperf/Makefile
- third-party/lib/cJSON/Makefile
- third-party/lib/pcre/Makefile
- third-party/tcl/tclsh/Makefile
- third-party/tcl/tcludp/Makefile
> third_party: Add mirrors for sourceforge downloads

- src/cmds/net/tftp.c
- src/drivers/serial/stm32_usart/hal_msp_f7.c
- src/drivers/serial/stm32_usart/stm32_usart_conf_f7.h
* Fix build for -Os
* Fix serial driver for stm32f7
> stm32f769i fix

- src/compat/libc/include/string.h
- src/compat/libc/string/Mybuild
- src/compat/libc/string/strcoll.c
- src/tests/posix/Mybuild
- src/tests/posix/strcoll_test.c
- templates/x86/qemu/mods.config
- third-party/gcc/include/string.h
- third-party/lua/lua/include/string.h
- third-party/qt/tree/mkspecs/qws/embox-generic-g++/qt_embox_compat.h
Add strcoll() and strcoll_test
> libs: strcoll()

- src/drivers/block_dev/stm32_sd/Mybuild
- src/drivers/block_dev/stm32_sd/stm32f7_discovery_sdio_sd.h
- src/drivers/block_dev/stm32_sd/stm32f7_sd.c
- templates/arm/stm32f769i/mods.config
Implement SD-card driver for STM32F7 boards
> stm32f7 sd

- platform/opencv/cmds/edges.cpp
- platform/opencv/templates/stm32f769idiscovery/mods.config
- src/cmds/fs/dd/Dd.my
- src/cmds/fs/dd/dd.c
- src/compat/posix/fs/dvfs/dirent.c
- src/compat/posix/fs/dvfs/open.c
- src/drivers/block_dev/stm32_sd/stm32f7_sd.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/dvfs/dvfs_dentry.c
- src/fs/dvfs/dvfs_util.c
- third-party/gcc/Mybuild
Also make a bunch of fixes (mostrly for file system)
> opencv/edges: Pass file as an argument

- platform/stm32f4_cnc/cmds/Mybuild
- platform/stm32f4_iocontrol/cmds/Flash_settings.my
- platform/stm32f4_iocontrol/cmds/Mybuild
- platform/stm32f4_iocontrol/cmds/libleddrv_ll.c
- templates/arm/stm32_modbus/mods.config
- third-party/bsp/stmf4cube/stm32f4xx_hal_conf.h
> stm32_modbus update

- src/drivers/serial/imx_uart/Mybuild
- src/drivers/serial/imx_uart/imx_uart.c
Add base addresses for i.MX8 board
> i.MX8 UART

- src/arch/aarch64/include/asm/hal/reg.h
- src/arch/aarch64/include/asm/modes.h
- src/arch/aarch64/kernel/context/context_switch.S
- src/arch/aarch64/kernel/exception_table.S
- src/arch/aarch64/kernel/ipl_impl.h
- src/drivers/clock/pl031/Mybuild
- src/drivers/clock/pl031/pl031.c
* Implement `ipl_init()`/`ipl_save()`/`ipl_restore()`
* Implement entry/exit for exceptions
* Implement IRQ handle
* Fix PL031 timer
> aarch64 interrupts

- src/arch/aarch64/include/asm/setjmp.h
- src/arch/aarch64/kernel/arch.c
- src/arch/aarch64/kernel/context/context.c
- src/arch/aarch64/kernel/context/context.h
- src/arch/aarch64/kernel/context/context_switch.S
- src/arch/aarch64/lib/Mybuild
- src/arch/aarch64/lib/setjmp.S
- src/drivers/clock/pl031/pl031.c
- src/drivers/serial/imx_uart/imx_uart.c
- src/include/framework/test/assert.h
- src/mem/heap/heap_bm.c
- src/tests/kernel/thread/thread_priority_test.c
- templates/aarch64/qemu/mods.config
- templates/aarch64/qemu/start_script.inc
Aarch64:
* Implement `context_switch()`
* Implement `setjmp()`/`longjmp()`
* Fix pl031
* Update template
Work on 64-bit compatibility:
* heap_bm
* thread_priotity_test
* framework/test
> Aarch64: Implement context_switch() and setjmp()

- src/arch/aarch64/include/asm/hal/reg.h
- src/arch/aarch64/kernel/exception_table.S
- src/compat/posix/proc/vfork_exchanged/exec_exchanged.c
- src/drivers/clock/gpt/Mybuild
- src/drivers/clock/gpt/gpt.c
- src/drivers/interrupt/gicv3/Mybuild
- src/drivers/interrupt/gicv3/gicv3.c
- src/drivers/interrupt/gicv3/gicv3.h
- src/drivers/serial/imx_uart/imx_uart.c
- src/include/hal/reg.h
- templates/aarch64/qemu/mods.config
* Implement ARM GICv3 (now it works only for qemu)
* Implement ARM General Purpose Timer
* Work on aarch64 boot
* Minor fixes
> Extending aarch64 support

- platform/stellaris/templates/lm3s811evb/mods.config
- src/kernel/thread/signal_stub.c
> Fix stellaris/lm3s811evb

- .travis.yml
- src/kernel/thread/sync/cond.c
- src/tests/posix/pthread/Mybuild
- src/tests/posix/pthread/pthread_cond_test.c
- src/tests/posix/pthread/pthread_cond_timedwait_test.c
- src/tests/posix/pthread/pthread_key_test.c
- src/tests/posix/pthread/pthread_mutex_test.c
- templates/x86/test/units/mods.config
fix pthread_key_test, pthread_cond_timedwait_test, pthread_cond_test, pthread_policy_test
> Pthread tests

- platform/efm32zg_sk3200/templates/debug/mods.config
- platform/stm32f4_cnc/templates/windows/mods.config
- src/cmds/shell/diag_shell/console/cmdline.c
- src/compat/libc/string/strxfrm.c
- templates/arm/bpi/mods.config
- templates/arm/nxt_bt_pnet/mods.config
- templates/arm/omap-qt/mods.config
- templates/arm/overo/mods.config
- templates/arm/raspi/mods.config
- templates/arm/stm32_vl/mods.config
- templates/arm/stm32_vl_light/mods.config
- templates/arm/ti816x-qt/mods.config
- templates/msp430/exp430g2/mods.config
- templates/msp430/mspdebug/mods.config
- templates/sparc/greth/mods.config
A bunch of fixes for templates
> Fix some templates

- platform/pjsip/templates/stm32746g/mods.config
- platform/pjsip/templates/stm32f769i-discovery/build.conf
- platform/pjsip/templates/stm32f769i-discovery/lds.conf
- platform/pjsip/templates/stm32f769i-discovery/mods.config
- platform/pjsip/templates/stm32f769i-discovery/start_script.inc
- src/drivers/audio/stm32/Mybuild
- src/drivers/audio/stm32/stm32_audio_f7.c
- src/drivers/audio/stm32/stm32f764g_discovery_audio.c
- src/drivers/audio/stm32/stm32f764g_discovery_audio.h
- src/drivers/audio/stm32/stm32f769i_discovery_audio.c
- src/drivers/audio/stm32/stm32f769i_discovery_audio.h
- third-party/bsp/stmf7cube/stm32f769i/Mybuild
- third-party/bsp/stmf7cube/stm32f769i/stm32f7xx_hal_conf.h
Porting pjsip to stm32f769i-discovery
> Pjsip stm32f769i discovery

- mk/image2.mk
- src/cmds/net/httpd/Httpd.my
- src/service/http_admin/Mybuild
- src/service/http_admin/http_admin_backend.c
- templates/arm/qemu/mods.config
- templates/arm/stm32f4-discovery/mods.config
- templates/arm/stm32f764g-discovery/mods.config
- templates/x86/qemu/mods.config
* Fix several templates with http_admin
* Fix `rootfs.cpio` creation. Before that fix initfs driver has not recognized folders in InitFs.
> Fix http_admin for stm32

- src/cmds/testing/fb_direct_access/Mybuild
- src/cmds/testing/fb_direct_access/fb_direct_access.c
- src/cmds/testing/fb_draw_image/Mybuild
- src/cmds/testing/fb_draw_image/fb_draw_image.c
- src/lib/fb_draw/Mybuild
- src/lib/fb_draw/fb_draw.c
- src/lib/fb_draw/fb_draw.h
add lib for working with fb and drawing in fb
fb_draw_image reworked for fb_draw lib
fb_direct_access reworked for fb_draw lib
> 16bpp screen

- src/cmds/fs/Mkdir.my
- src/cmds/fs/Mount.my
- src/cmds/fs/mkdir.c
- src/cmds/fs/mkfs.c
- src/cmds/fs/mount.c
- src/compat/posix/fs/dvfs/fsop.c
- src/drivers/block_dev/block_dev.h
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs_util.c
Number of minor fixes for FS commands and modules
> Improve FS usability

- src/arch/e2k/context.c
- src/arch/e2k/entry.c
- src/arch/e2k/include/asm/ptrace.h
- src/arch/e2k/include/asm/setjmp.h
- src/arch/e2k/kernel_entry.S
- src/arch/e2k/libarch/Mybuild
- src/arch/e2k/libarch/e2k_vfork.S
- src/arch/e2k/mmu/mmu.c
- src/cmds/testing/fb_devfs_access/fb_devfs_access.c
- src/drivers/video/lynxfb/lynxfb.c
- src/init/setup_tty.h
- src/init/setup_tty_devfs.c
- src/init/setup_tty_diag.c
- src/init/start_script.c
- src/init/system_start_service.c
- templates/e2k/monocube/mods.config
* Enabled tish for default
* Implemented vfork()
* Improve e2k/monokub template
* Fix stacks locations
> E2k monocub

- src/cmds/fs/dd/dd.c
- src/compat/posix/fs/open.c
> dd: add flag O_CREAT to ofd

- src/cmds/hardware/pin/Mybuild
- src/cmds/hardware/pin/pin.c
- src/drivers/gpio/dwapb/dwapb_gpio.c
- templates/arm/de0_nano_soc/mods.config
* Implement `dwapb_gpio_get()`
* Improve `pin` command
* Update template for De0 Nano SoC
> De0 nano soc GPIO support

- src/arch/riscv/embox.lds.S
- src/arch/riscv/include/asm/hal/arch.h
- src/arch/riscv/include/asm/hal/ipl.h
- src/arch/riscv/include/asm/interrupts.h
- src/arch/riscv/include/asm/limits.h
- src/arch/riscv/include/asm/regs.h
- src/arch/riscv/include/asm/types.h
- src/arch/riscv/kernel/Mybuild
- src/arch/riscv/kernel/arch.c
- src/arch/riscv/kernel/boot.S
- src/arch/riscv/kernel/context.c
- src/arch/riscv/kernel/context.h
- src/arch/riscv/kernel/ipl_impl.c
- src/arch/riscv/kernel/ipl_impl.h
- src/arch/riscv/kernel/setjmp.S
- src/arch/riscv/kernel/trap.c
- src/compat/libc/include/inttypes.h
- src/drivers/serial/Mybuild
- src/drivers/serial/sifive_uart.c
- templates/riscv/qemu-sifive-e/build.conf
- templates/riscv/qemu-sifive-e/lds.conf
- templates/riscv/qemu-sifive-e/mods.config
> add initial risc-v support

- platform/etnaviv/cmds/Mybuild
- platform/etnaviv/cmds/quad_tex/Mybuild
- platform/etnaviv/cmds/quad_tex/quad_tex.c
- platform/etnaviv/cmds/tri.c
* Add alpha channel for triangle example
* Add option for custom fragment shader compilation for texture example
> Improve Etnaviv example programms

- src/drivers/block_dev/stm32_sd/stm32f4_sd.c
Don't create block device if SD card is not inserted
> stm32f4_sd: Fix initialization

- src/drivers/mmc/core/Mybuild
- src/drivers/mmc/core/mmc.h
- src/drivers/mmc/core/mmc_card.h
- src/drivers/mmc/core/mmc_core.h
- src/drivers/mmc/core/mmc_host.c
- src/drivers/mmc/core/mmc_host.h
This module is a common part for MMC drivers.
> drivers: Add mmc/core

- src/cmds/testing/block_dev/Mybuild
- src/cmds/testing/block_dev/block_dev_test.c
- src/compat/libc/include/inttypes.h
- src/util/Mybuild
- src/util/pretty_print.c
- src/util/pretty_print.h
- templates/arm/qemu/mods.config
* Add support for raw block devices
* Add util to print binary buffer
* Minor fix for 64-bit format printing for ARM
> Work on cmds/block_dev_test

- src/drivers/mmc/host/pl181/Mybuild
- src/drivers/mmc/host/pl181/pl181.c
- templates/arm/qemu/mods.config
* Extend MMC subsystem
* Implement pl181 driver
> pl181 driver

- src/tests/math/Mybuild
Add missing dependency for `fpu_consistency_test`.
> Dependency fix

- third-party/bsp/st_discovery_vl/Makefile
- third-party/phoneme/Makefile
Add mirrors for packages hosted on dropbox.
> Third-party mirrors

- scripts/autotest/configs/default.sh
- scripts/autotest/configs/ide.sh
- scripts/autotest/configs/stm32.sh
- scripts/autotest/configs/usb.sh
- scripts/autotest/framework/core.exp
- scripts/autotest/framework/target_picocom.exp
- scripts/autotest/framework/target_telnet.exp
- scripts/autotest/run.sh
Add _picocom_ target (for testing stm32 currently)
> Autotest add picocom

- src/fs/driver/fat/fat.h
- src/fs/driver/fat/fat_common.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/driver/fat/fat_oldfs.c
Now works with FAT32.
Now autotests for echo and touch are passing.
> FAT rework

- third-party/lib/openlibm/Makefile
- third-party/lib/zlib/Makefile
Add mirrors for zlib and openlibm
> third_party: Add mirrors

- src/drivers/block_dev/Mybuild
- src/drivers/serial/stm32_usart/Mybuild
- src/drivers/serial/stm32_usart/hal_msp_l4.c
- src/drivers/serial/stm32_usart/stm32_usart_conf_l4.h
- src/fs/driver/devfs/Mybuild
- src/fs/driver/devfs/devfs_dvfs.c
- src/fs/driver/devfs/devfs_stub.c
- templates/arm/stm32l4-discovery/build.conf
- templates/arm/stm32l4-discovery/lds.conf
- templates/arm/stm32l4-discovery/mods.config
- templates/arm/stm32l4-discovery/start_script.inc
- third-party/bsp/stml4cube/Makefile
- third-party/bsp/stml4cube/Mybuild
- third-party/bsp/stml4cube/arch.c
- third-party/bsp/stml4cube/stm32l4xx_hal_conf.h
* Add module for STM32L4Cube
* Add serial driver
* Add template
* Added wiki page: https://github.com/embox/embox/wiki/STM32L4DISCOVERY
> Porting to STM32L4-Discovery

- src/arch/arm/imx/iomuxc/iomuxc.h
- src/drivers/mmc/core/mmc.c
- src/drivers/mmc/core/mmc_core.h
- src/drivers/mmc/core/mmc_host.c
- src/drivers/mmc/core/sd.c
- src/drivers/mmc/host/sdhci/sdhci.h
- src/drivers/mmc/host/sdhci/sdhci_ops.c
* Add mmc_try_sd() function to try detect SD card
* Fix SDHCI driver
Now SDHCI driver can read CID correctly (i.e. storage size, manufacturer id, serial number etc are correct); however, read/write operations still do not work.
> Work on MMC subsystem

- src/compat/posix/idx/pipe_pty.c
Fix `Execute "help" multiple times` autotest test case, which was failing from time to time due to pty <-> tty synchronization.
> pty: Fix synchronization with tty

- src/drivers/mmc/core/mmc_host.c
- src/drivers/mmc/core/sd.c
- src/drivers/mmc/host/sdhci/sdhci.h
- src/drivers/mmc/host/sdhci/sdhci_ops.c
* Bunch of fixes for MMC subsystem
* Add data transfer support for SDHCI driver
> Sdhci fixes

- src/compat/linux/include/asm-generic/dma-mapping.h
- src/drivers/mmc/core/mmc_core.h
- src/drivers/mmc/core/sd.c
- src/drivers/mmc/host/dw_mmc/dw_mmc.h
- src/drivers/mmc/host/dw_mmc/dw_mmc_socfpga.c
- templates/arm/de0_nano_soc/mods.config
MMC host driver is worked on **'de0_nano_soc'**. It's testing by **'dd'** and **'block_dev_test'** commands
> Add dw_mmc_socfpga

- src/drivers/common/Mybuild
- src/drivers/common/memory.c
- src/drivers/common/memory.h
- src/drivers/mmc/host/dw_mmc/dw_mmc.h
- src/drivers/mmc/host/dw_mmc/dw_mmc_socfpga.c
* Refactor & clean some code
* Fix data transfer error
> Fix DW MMC driver

- scripts/autotest/framework/cmd.exp
- scripts/autotest/testsuite/fs-ramfs/rm/test.exp
- scripts/autotest/testsuite/fs-vfat/rm
- src/fs/driver/fat/fat.h
- src/fs/driver/fat/fat_common.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/driver/fat/fat_oldfs.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs_util.c
* Add rm test for autotest-vfat/ramfs
* Fix some memory leaks in VFS
* Fix a number of FAT rm-related issues
> filesystem rm test

- src/fs/driver/fat/fat.h
- src/fs/driver/fat/fat_common.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/driver/fat/fat_oldfs.c
- src/fs/dvfs/file_desc.c
- src/fs/dvfs/file_desc.h
* Add more handlers for bitmask calculations
* Simplify `fatfs_open()`
> Fat refactor

- src/compat/posix/fs/dvfs/open.c
- src/compat/posix/fs/ftruncate.c
- src/compat/posix/fs/read.c
- src/compat/posix/fs/readv.c
- src/compat/posix/fs/write.c
- src/compat/posix/fs/writev.c
- src/compat/posix/idx/idesc_pipe.c
- src/compat/posix/idx/pipe_pty.c
- src/compat/posix/idx/poll.c
- src/compat/posix/sys/timerfd/timerfd.c
- src/drivers/char/char_dev.c
- src/drivers/char/char_dev_dvfs/char_dev_dvfs.c
- src/drivers/console/fbcon.c
- src/drivers/tty/serial/idesc_serial.c
- src/drivers/tty/serial/idesc_serial_oldfs.c
- src/fs/file_desc.c
- src/fs/idesc.c
- src/fs/syslib/idesc_mmap/idesc_mmap.c
- src/fs/syslib/kfile.c
- src/include/fs/idesc.h
- src/init/diag_fd.c
- src/kernel/task/idesc/index_descriptor.c
- src/net/socket/sock_factory.c
Use only 'idesc_flags' now instead of idesc_mode & idesc_flags fields
> fs: Rm 'idesc_mode' field from 'struct idesc'

- src/drivers/net/dwc_gmac/dwc_gmac.c
- templates/arm/de0_nano_soc/mods.config
Add 1gbit speed support and move speed-related stuff to `dwc_set_speed()`
> drivers/net/dwc_gmac: Add 1gbit support

- src/fs/driver/initfs/initfs_dvfs.c
Don't read beyond the file end
> Fix initfs driver

- src/cmds/hardware/spi/Mybuild
- src/cmds/hardware/spi/spi.c
- src/drivers/spi/spi.c
- src/drivers/spi/spi.h
- src/drivers/spi/stm32/Mybuild
- src/drivers/spi/stm32/spi_conf_f4.h
- src/drivers/spi/stm32/stm32.c
- src/drivers/spi/stm32/stm32_spi.h
- src/drivers/spi/stm32/stm32_spi1.c
- src/drivers/spi/stm32/stm32_spi2.c
- templates/arm/stm32f4-discovery/mods.config
* Implement SPI driver for STM32F4 (tested with 2 discovery boards)
* Add handler to set SPI mode (slave/master)
> STM32 SPI driver

- scripts/qemu/auto_qemu
- src/compat/libc/include/inttypes.h
- src/drivers/common/memory.c
- src/drivers/serial/ns16550/Mybuild
- src/drivers/serial/ns16550/ns16550.c
- templates/riscv/qemu-sifive-e/build.conf
- templates/riscv/qemu-sifive-u/build.conf
- templates/riscv/qemu-sifive-u/mods.config
- templates/riscv/qemu/build.conf
- templates/riscv/qemu/lds.conf
- templates/riscv/qemu/mods.config
* Clean some risc-v templates
* Add risc-v support to auto_qemu script
* Improve common memory for NOMMU version
> Clean risc-v support

- src/compat/posix/fs/dirent/dirent_oldfs.c
Make creation/deletion of inodes symmetric.
> compat/posix/fs/closedir: Fix resource free

- src/fs/dvfs/dvfs.c
> dvfs: Fix mount

- src/arch/riscv/include/asm/entry.h
- src/arch/riscv/include/asm/ptrace.h
- src/arch/riscv/kernel/context.c
- src/arch/riscv/kernel/context.h
- src/arch/riscv/lib/Mybuild
- src/arch/riscv/lib/ptregs_jmp.S
- src/arch/riscv/lib/vfork.S
- templates/riscv/qemu-sifive-u/mods.config
- templates/riscv/qemu-sifive-u/rootfs/network
- templates/riscv/qemu-sifive-u/system_start.inc
Add vfork and ptregs_jmp. Work on #1047
> riscv: add vfork and ptregs_jmp

- platform/fpga/cmds/hps_control_fpga_led/Mybuild
- platform/fpga/cmds/hps_control_fpga_led/hps_0.h
- platform/fpga/cmds/hps_control_fpga_led/led.c
- platform/fpga/cmds/hps_control_fpga_led/led.h
- platform/fpga/cmds/hps_control_fpga_led/main.c
- platform/fpga/templates/de0_nano_socfpga/build.conf
- platform/fpga/templates/de0_nano_socfpga/lds.conf
- platform/fpga/templates/de0_nano_socfpga/mods.config
- platform/fpga/templates/de0_nano_socfpga/rootfs/network
- platform/fpga/templates/de0_nano_socfpga/system_start.inc
- src/cmds/hardware/fpga/Mybuild
- src/cmds/hardware/fpga/fpga.c
- src/drivers/fpga/Mybuild
- src/drivers/fpga/fpga.c
- src/drivers/fpga/fpga.h
- src/drivers/fpga/socfpga/Mybuild
- src/drivers/fpga/socfpga/socfpga.c
- templates/arm/de0_nano_soc/mods.config
* Initial implementation for fpga subsystem
* Add driver for socfpga
* Add `fpga` command to write FPGA configuration
* Add `hps_control_fpga_led` command which can cooperate with HPS_CONTROL_FPGA_LED.rbf config to control FPGA leds
* Update `arm/de0_nano_soc` template
I'll write how to run this example in corresponding wiki page, it's in progress.
~~This branch is still in progress because of couple issues:~~
* ~~There are some issues with caching in `hps_control_fpga_led` example~~
* ~~There are still stubs in fpga idesc ops~~
~~socfpga driver and fpga subsystem are mostly done, so it can be reviewed already :)~~
upd: Functional changes are done for now, so now all the code may be reviewed.
**Known issue:** `dd if=config of=/dev/fpga0` fails if `dd` uses too much chunks. I'm not going …
> FPGA support

- Makefile
- mk/core/define.mk
- mk/extbld/lib.mk
- src/arch/usermode86/host/host_net.c
> mk: Add real fix for make 4.3

- src/arch/arm/armlib/boot/Mybuild
- src/arch/arm/armlib/boot/low_excpt_table_vmem_def.c
- src/drivers/interrupt/raspi.c
- src/drivers/serial/raspi_uart.c
- src/drivers/video/raspi_video.c
- templates/arm/raspi/lds.conf
- templates/arm/raspi/mods.config
- templates/arm/raspi/system_start.inc
Now it works on qemu as described on [wiki](https://github.com/embox/embox/wiki/Running-Embox-on-QEMU-emulated-Raspberry-Pi)
> Fix RasPi template

- src/mem/heap/heap_simple.c
Implement memalign function for heap_simple.c. #1713 
The function works similar to malloc but it aligns the address. I check if the block size is big enough for alignment and if the alignment is power of 2 and after finding the area - I will align it.
> [mem]Implement memalign for heap_simple memory allocator

- src/compat/libc/stdio/fprintf.c
- src/compat/libc/stdio/printf_impl.c
- src/compat/libc/stdio/printf_impl.h
- src/compat/libc/stdio/snprintf.c
- src/compat/libc/stdio/sprintf.c
- src/lib/printk.c
> Add error check in printf

- src/cmds/Tail.my
- src/cmds/tail.c
Fixes #1710 and implements the tail functionality.
> Implement 'tail' command 

- src/cmds/hardware/lsusb/lsusb.c
Closes #1714 with printing device, configuration and interface descriptors for -v flag.
> cmds/hardware/lsusb: Extending lsusb with -v flag

- src/cmds/fs/Du.my
- src/cmds/fs/du.c
- src/cmds/fs/ls.c
- templates/x86/qemu/mods.config
Implement 'du' command for regular and directories. #1729
>  Implement 'du' command

- src/cmds/net/arping.c
arping did not display how long it took to receive a reply
(issue #1723).
This makes arping show the amount of time in milliseconds.
neighbour_get_haddr() is called in a loop in order to be
able to measure the exact time when the reply has been received.
> cmds: Make arping output reply time

- src/arch/x86/lib/cpu_performance/cpu_counter.c
- src/arch/x86/lib/cpu_performance/cpu_info.c
- templates/x86/qemu/mods.config
* Fix compilation with recent GCC versions
* Add to x86/qemu template
> cpuinfo build fix

- src/cmds/fs/ls.c
command `ls` multiple arguments fix
Fixes #1755
> command `ls` multiple arguments #1755

- src/cmds/fs/cat.c
> x86/qemu: multiple argumets for cat command

- src/arch/riscv/kernel/boot.S
- templates/riscv/qemu-sifive-u/mods.config
> riscv: add multiple harts case handling

- scripts/autotest/testsuite/net/ping/test.exp
- scripts/expect/ping.exp
Fixes https://github.com/embox/embox/issues/1785
> Fix ping.exp test

- src/cmds/proc/thread.c
Added two fields in the thread command viz. Task name and Stack size.
> Updated the fields in thread command

- src/drivers/clock/epit/Mybuild
- src/drivers/clock/epit/epit.c
Add the driver for EPIT timer/counter for the I.MX boards.
This solves #1767 
> Drivers: clock: EPIT: Add driver for the EPIT

- scripts/qemu/auto_qemu
> scripts: Fix QEMU run as root

- third-party/e2fsprogs/patch.txt
fix issue #1843.
This is one of two possible solutions stated in the issue. I dont know if this is the right solution though.
> third-party: fix e2fsprogs undefined reference

- mk/script/loadable-build.mk
- src/cmds/load_app/load_app.c
* Fix entry point offset calculation
* Make sure to free all loadable section memory
> load_app: Fix ELF section parsing

- src/cmds/fs/file.c
- src/fs/file_format.c
- src/fs/file_format.h
Fixes #1730 
I've added PNG, GIF, ELF, XML file formats to the file command
> Extended PNG, GIF, ELF, XML format for file command

- src/include/sys/queue.h
- src/tests/bsd/Mybuild
- src/tests/bsd/queue_test.c
queue.h has been added. To make queue.h compatible necessary variables and functions have been added to cdefs.h.
> implemented macros/functions from BSD queue.h. (Fixed #1644)

- src/compat/posix/include/time.h
- src/compat/posix/time/Mybuild
- src/compat/posix/time/strptime.c
- src/tests/posix/time/Mybuild
- src/tests/posix/time/strptime_test.c
- templates/x86/test/units/mods.config
Added tests for strptime function
Added strptime im time.h library
Added module strptime and tests in config file
Last version of strptime function
> Added strptime function and tests

- src/compat/libc/stdio/scanf.c
- src/tests/stdio/scanf_test.c
Done the good first issue #1870 by adding %n for "scanf" and add its test
> 1870 add %n for scanf

- src/tests/stdlib/Mybuild
- src/tests/stdlib/strcmp_test.c
- templates/x86/test/units/mods.config
> Implemented unit tests for strcmp() and strncmp()

- src/tests/stdlib/Mybuild
- src/tests/stdlib/memcpy.c
- templates/x86/test/units/mods.config
Fixes https://github.com/embox/embox/issues/1857
> Add test cases for memcpy

- src/tests/stdlib/Mybuild
- src/tests/stdlib/memcmp_test.c
- templates/x86/test/units/mods.config
> Add Unit tests for memcmp

- src/compat/libc/include/string.h
- src/compat/libc/string/Mybuild
- src/compat/libc/string/memccpy.c
- src/tests/posix/Mybuild
- src/tests/posix/memccpy_test.c
- templates/x86/test/units/mods.config
closes #1840 (Good First issue)
After correcting my mistake in the first PR, I made this try and now I hope everything is ok.
I have fixed memccpy_test.c, renamed memccpy.c, so everyone can use it, and I think I have connected these with Mybuild correctly.
I ran embox emulator and it didn't get me any error. Please let me know if something is wrong or need to be fixed.
Thank you for your time
> 1840 memccpy implementation

- src/tests/stdlib/Mybuild
- src/tests/stdlib/strcasestr.c
- src/tests/stdlib/strstr.c
- templates/x86/test/units/mods.config
> Implemented unit tests for strstr() and strcasestr()

- src/tests/stdlib/Mybuild
- src/tests/stdlib/strcpy.c
- src/tests/stdlib/strncpy.c
- templates/x86/test/units/mods.config
> Added unit tests for strcpy() and strncpy()

- templates/x86/test/lang/start_script.inc
- third-party/lua/lib/luasocket/http_request.lua
* Small refactoring of http_request.lua
* Enable on CI
> Fix luasocket test

- templates/arm/stm32f746g-discovery-lua/build.conf
- templates/arm/stm32f746g-discovery-lua/lds.conf
- templates/arm/stm32f746g-discovery-lua/mods.config
- templates/arm/stm32f746g-discovery-lua/rootfs/network
- templates/arm/stm32f746g-discovery-lua/system_start.inc
- templates/arm/stm32f746g-discovery/mods.config
> Lua stm32f746g

- src/tests/stdlib/Mybuild
- src/tests/stdlib/strchrnul_test.c
- src/tests/stdlib/strrchr_test.c
- templates/x86/test/units/mods.config
> Added unit tests for strrchr and strchrnul

- src/cmds/net/arp.c
- src/include/net/l3/arp.h
- src/include/net/neighbour.h
- src/net/l3/arp.c
- src/net/neighbour.c
> net/arp: Refactor

- src/drivers/net/lan91c111/lan91c111.c
* Make sure to avoid parallel execution of xmit and rx operations as
they mess up inner state of net card
* Check for successfull packet allocation on xmit
* Check for non-empty FIFO on rx
* Other minor fixes
> drivers/net/lan91c: Rework

- src/drivers/net/lan91c111/lan91c111.c
* Use 8-bit register access to avoid unwanted clobbering neighbour bytes with 16-bit access
* Make interrupt enable/clear logic more clear
* Avoid double `skb_free()` when failed to alloc TX register
* Other minor changes
> drivers/net/lan91c: Fix packet miss for heavy network load

- src/drivers/net/lan91c111/lan91c111.c
- src/drivers/net/lan91c111/lan91c111.h
* Clean lan91c111 netcard
* Enable deferred sending if ALLOC_TX was not succed
> Clean lan91c111 netcard

- src/lib/readline/rl_linenoise.c
- third-party/lib/linenoise/linenoise.c
- third-party/lib/linenoise/linenoise.h
Closes #1946
It also fixes #1569
> third-party: Porting new version of linenoise

- platform/nuklear/templates/stm32f7/mods.config
- src/drivers/video/stm32f7_lcd/stm32f7_lcd.c
Fix nuklear examples running on stm32f7-discovery.
> Fix nuklear stm32

- src/compat/posix/proc/exec.c
This is an attempt to fix  https://github.com/embox/embox/issues/724
> exec: make execve initialize environment of new process

- src/drivers/virtual/Mybuild
- src/drivers/virtual/mem.c
Add a character driver that implements /dev/mem file and
helps in accessing physical memory using devfs.
closes #1914
> Drivers: virtual: mem: added virtual device /dev/mem

- src/drivers/serial/apbuart/apbuart.c
- src/drivers/serial/i8250/8250.c
- src/drivers/serial/ns16550/ns16550.c
- src/drivers/serial/pl011/pl011.c
- src/drivers/serial/stm32_usart/stm_usart_cube_diag.c
- src/drivers/serial/uart_device.h
> Expand uart ops api

- src/drivers/tty/serial/ttys_processing.c
Closes #1954 
Thanks @anton-bondarev
> added uart_irq_dis/uart_irq_en to clear buffer

- scripts/dialog/da14695/da14695_gdb_start_script
- scripts/dialog/da14695/flash_qspi.sh
- scripts/dialog/da14695/gdb_start.sh
- scripts/dialog/da14695/jlink_gdb_server_start.sh
- src/arch/arm/embox.lds.S
- src/arch/arm/platform/da146xx/Mybuild
- src/arch/arm/platform/da146xx/arch.c
- src/arch/arm/platform/da146xx/da1469x_quirk.lds.S
- templates/arm/da14680/mods.config
- templates/arm/da14695/build.conf
- templates/arm/da14695/lds.conf
- templates/arm/da14695/mods.config
https://github.com/embox/embox/wiki/Dialog-DA14695
> Porting to Dialog 14695

- src/cmds/net/sendmail.c
- src/compat/atomic/pseudo_atomic/pseudo_atomic.c
- src/compat/posix/pwd_grp/pwd_grp.c
Tested for `x86/qemu` and `arm/qemu` with `-O0` and `-O2` options
> Fix build for GCC 10

- src/drivers/diag/diag.c
> drivers: Fix diag getc with '\r' symbol

- src/arch/arm/subarch/armv5te/arm926ejs/Mybuild
- src/arch/arm/subarch/armv5te/arm926ejs/arch.c
> Add arch_idle() for arm/qemu

- src/drivers/interrupt/cortexm/irq_entry.S
- src/include/kernel/critical.h
- src/kernel/critical.c
Generate PendSV only if critical dispatch actually required
> Cortexm pendsv optimize

- templates/x86/test/packetdrill/mods.conf
- templates/x86/test/packetdrill/start_script.inc
- third-party/packetdrill/Makefile
* Remove slowdown from x86/test/packetdrill
* Fix build packetdrill with gcc9
> Improve test/packetdrill

- src/include/kernel/time/clock_source.h
- src/kernel/time/Time.my
- src/kernel/time/clock_source.c
- src/kernel/time/clock_tick.c
> 2012 rm slowdown module

- src/cmds/hardware/lsusb/lsusb.c
- src/drivers/usb/hc/usb_dwc.c
- src/include/drivers/usb/usb_desc.h
- templates/arm/da14695/mods.conf
- third-party/bsp/dialog/da14695/ccid/Makefile
- third-party/bsp/dialog/da14695/ccid/Mybuild
- third-party/bsp/dialog/da14695/sdk/sys_usb_patch.txt
ccid modules commented in mods.confi. You have to disable rndis first in order to enable ccid.
> ccid device

- src/cmds/net/telnetd/telnetd.c
Fixes https://github.com/embox/embox/issues/2050.
vfork()'ed parent has used local variable `ts`, which wasn't directly modified in child task, but because it was used only in parent gcc decided to use this local variable and corrupted it before parent started. So I fixed this in telnetd.
> telnetd: Fix running when compiling with -O2

- scripts/qemu/auto_qemu
- src/arch/riscv64/embox.lds.S
- src/arch/riscv64/include/asm/entry.h
- src/arch/riscv64/include/asm/hal/arch.h
- src/arch/riscv64/include/asm/hal/reg.h
- src/arch/riscv64/include/asm/interrupts.h
- src/arch/riscv64/include/asm/limits.h
- src/arch/riscv64/include/asm/ptrace.h
- src/arch/riscv64/include/asm/regs.h
- src/arch/riscv64/include/asm/setjmp.h
- src/arch/riscv64/include/asm/types.h
- src/arch/riscv64/kernel/Mybuild
- src/arch/riscv64/kernel/arch.c
- src/arch/riscv64/kernel/boot.S
- src/arch/riscv64/kernel/context.c
- src/arch/riscv64/kernel/context.h
- src/arch/riscv64/kernel/context_switch.S
- src/arch/riscv64/kernel/entry.S
- src/arch/riscv64/kernel/interrupt.c
- src/arch/riscv64/kernel/ipl_impl.c
- src/arch/riscv64/kernel/ipl_impl.h
- src/compat/libc/include/inttypes.h
- templates/riscv64/qemu/build.conf
- templates/riscv64/qemu/lds.conf
- templates/riscv64/qemu/mods.conf
- templates/riscv64/qemu/system_start.inc
Add minimal arch/riscv64 & riscv64/qemu template.
It can boot on qemu-system-riscv64(but stuck at initializing clock driver).
> add riscv64

- src/drivers/gpio/stm32/Mybuild
- src/drivers/gpio/stm32/stm32_gpio_conf_l4.h
- templates/arm/nucleo_l476rg/mods.conf
Add configuration file for GPIOs of STM32L4.
it closes #2056
> Drivers: GPIO: Add gpio driver for STM32L4

- src/drivers/diag/diag.c
- src/drivers/serial/sifive_uart.c
Close #2062  Fix qemu-sifive-u template
> Fix sifive uart

- src/tests/stdlib/Mybuild
- src/tests/stdlib/memmove_test.c
- templates/x86/test/units/mods.conf
> Testing memmove function

- src/tests/stdlib/memmove_test.c
Build fix after https://github.com/embox/embox/pull/2072
> Fix memmove_test build, but not the test itself

- mk/script/build/oldconf-gen.mk
> mk: set HOSTCC to cc

- mk/image2.mk
- mk/image3.mk
- mk/image_lib.mk
- mk/variables.mk
> Switch build system to absolute paths

- templates/arm/qt-stm32f7discovery/mods.conf
- third-party/qt/Makefile
- third-party/qt/examples/Animatedtiles.my
- third-party/qt/examples/Moveblocks.my
- third-party/qt/patch_cortex_m7.txt
- third-party/qt/pkg_patch.txt
- third-party/qt/pkg_patch_for_qconfig.txt
- third-party/qt/plugins/platforms/Emboxfb.my
- third-party/qt/plugins/platforms/Emboxvc.my
- third-party/qt/plugins/platforms/Minimal.my
- third-party/qt/plugins/platforms/Vnc.my
- third-party/qt/qconfig-small.txt
- third-party/qt/tree/src/plugins/platforms/emboxfb/emboxfbintegration.cpp
Very basic update without brushing.
> Qt update to 4.8.7

- src/arch/riscv64/kernel/arch.c
- src/arch/riscv64/kernel/boot.S
- templates/riscv64/maixbit/build.conf
- templates/riscv64/maixbit/lds.conf
- templates/riscv64/maixbit/mods.conf
- templates/riscv64/maixbit/system_start.inc
fix #2082.
add MAiX BiT template and fix riscv64 boot code.
> add MAiX BiT

- src/compat/posix/include/pthread.h
- src/compat/posix/pthread/pthread_mutex.c
- src/include/kernel/thread/sync/mutex.h
- src/kernel/thread/sync/mutex.c
- src/tests/posix/pthread/Mybuild
- src/tests/posix/pthread/pthread_mutex_timedlock_test.c
This patch should fix https://github.com/embox/embox/issues/2032
> compat: implement pthread_mutex_timedlock()

- src/drivers/serial/sifive_uart/sifive_uart.c
> fix: sifive_uart_putc

- src/cmds/hardware/lsblk/lsblk.c
- src/drivers/clock/Mybuild
- src/drivers/clock/riscv_clk/Mybuild
- src/drivers/common/device.h
- src/drivers/mmc/core/sd.c
- src/drivers/serial/ns16550/Mybuild
- src/drivers/serial/pl011/Mybuild
- src/include/kernel/sched/waitq.h
- src/kernel/lthread/Mybuild
- src/kernel/sched/Mybuild
- src/kernel/sched/boot_light.c
- src/kernel/sched/waitq.c
- src/kernel/thread/Mybuild
- src/kernel/time/Time.my
- templates/arm/minimal/build.conf
- templates/arm/minimal/mods.conf
- templates/riscv/minimal/build.conf
- templates/riscv/minimal/lds.conf
- templates/riscv/minimal/mods.conf
- templates/riscv64/minimal/build.conf
- templates/riscv64/minimal/lds.conf
- templates/riscv64/minimal/mods.conf
- templates/x86/smp/mods.conf
> 2120 create minimal riscv templates

- scripts/maixbit-flash.sh
> add: maixbit flash script

- src/tests/stdlib/Mybuild
- src/tests/stdlib/strtok_r.c
I have added tests for strtok_r(). It closes #1847 
Let me know if i should make any changes to code.
> added test for strtok_r

- src/arch/riscv64/include/asm/regs.h
- src/arch/riscv64/kernel/interrupt.c
- templates/riscv/qemu/mods.conf
> 2088 fix ticker on riscv

- src/compat/posix/include/sys/socket.h
- src/tests/posix/net/Mybuild
- src/tests/posix/net/socket_cmsg_test.c
Add `CMSG_` macros (https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_socket.h.html#tag_13_61).
> Add socket cmsg macros

- third-party/bsp/dialog/da14695/osal/Mybuild
- third-party/bsp/dialog/da14695/osal/osal.c
> Add log to da14695 osal

- src/include/kernel/thread.h
- src/include/kernel/thread/thread_alloc.h
- src/kernel/task/multi/main_thread_create.c
- src/kernel/task/multi/multi.c
- src/kernel/task/multi/multi.h
- src/kernel/task/single.h
- src/kernel/thread/Mybuild
- src/kernel/thread/core.c
- src/kernel/thread/thread_allocator/Mybuild
- src/kernel/thread/thread_allocator/thread_allocator_heap.c
- src/kernel/thread/thread_allocator/thread_allocator_pool.c
- src/kernel/thread/thread_allocator/thread_heap.lds.S
- src/kernel/thread/thread_none.h
- src/kernel/thread/thread_types.h
The main goal is to provide the ability to use different stack sizes for threads.
> Thread heap allocator

- project/pjsip/templates/stm32f746g-discovery/mods.conf
- project/pjsip/templates/stm32f746g-discovery/rootfs/network
- project/pjsip/templates/stm32f746g-discovery/rootfs/resolv.conf
- project/pjsip/templates/stm32f746g-discovery/start_script.inc
- project/pjsip/templates/stm32f769i-discovery/mods.conf
- project/pjsip/templates/stm32f769i-discovery/rootfs/network
- project/pjsip/templates/stm32f769i-discovery/rootfs/resolv.conf
- project/pjsip/templates/stm32f769i-discovery/start_script.inc
- project/pjsip/templates/x86-qemu/mods.conf
- project/pjsip/templates/x86-qemu/rootfs/resolv.conf
- src/cmds/net/netmanager/netmanager.c
- src/net/lib/dns/Mybuild
- src/net/lib/dns/dns_file.c
- templates/aarch64/qemu/mods.conf
- templates/aarch64/qemu/rootfs/resolv.conf
- templates/arm/qemu/mods.conf
- templates/arm/qemu/rootfs/resolv.conf
- templates/microblaze/qemu/mods.conf
- templates/microblaze/qemu/rootfs/resolv.conf
- templates/mips/qemu/mods.conf
- templates/mips/qemu/rootfs/resolv.conf
- templates/mips64/qemu/mods.conf
- templates/mips64/qemu/rootfs/resolv.conf
- templates/x86/qemu/mods.conf
- templates/x86/qemu/rootfs/resolv.conf
* Add `#` comments to netmanager
* Add resolv.conf:
```
nameserver 8.8.8.8
```
> Improve netmanager and resolv.conf

- src/drivers/i2c/i2c.c
- src/drivers/i2c/i2c.h
> Enable i2c combined transactions

- scripts/qemu/auto_qemu
Fixes https://github.com/embox/embox/issues/2215
> scripts: auto_qemu: Remove extra comma

- src/cmds/play.c
- src/cmds/record/record.c
Fixes https://github.com/embox/embox/issues/2204
> 2204 fix stm32 audio with -O0

- src/drivers/clock/cortexm_systick/cortexm_systick.c
Verify RELOAD value for cortex-m systick
> Add cortexm systick reload check

- src/net/neighbour.c
Start the neighbour timer only if there are neighbours in the ARP table and stop the timer otherwise.
> net: Start neighbour timer only if required

- src/compat/libc/wchar/Mybuild
- src/compat/libc/wchar/wchar_stubs.c
- src/compat/libc/wchar/wcstol.c
- src/compat/libc/wchar/wcstoll.c
- src/compat/libc/wchar/wcstoul.c
- src/compat/libc/wchar/wcstoull.c
Add implementation of wcstol() wcstoll() wcstoul() wcstoull()
> compat: Expend wchar support

- platform/dialog/templates/da14695/mods.conf
- platform/dialog/templates/da14695/start_script.inc
Add demo web-site to platform/dialog/da14695 template
> templates: Update platform/dialog/da14695

- platform/dialog/da14695/Mybuild
- platform/dialog/da14695/arch.c
- platform/dialog/da14695/clk.c
- platform/dialog/da14695/deepsleep/deepsleep.c
Update jiffies freq if system clock freq changed.
> Dialog tick freq

- src/kernel/thread/thread_allocator/thread_allocator_heap.c
> thread: Add more log_debug to thread_allocator_heap

- src/cmds/sys/Uname.my
- src/cmds/sys/uname.c
- src/lib/sysctl/Mybuild
- src/lib/sysctl/sysctl.c
- src/lib/sysctl/sysctl.h
Attempt on #1698. Please let me know if this is what you require. Also, I would like to know if there is a way to get the 'processor' details (from arch options). I have currently only refactored the existing code, with no new features
> Refactor uname cmd

- src/cmds/fs/echo.c
- src/drivers/block_dev/block_dev.c
- src/drivers/block_dev/block_dev.h
- src/drivers/block_dev/ide/cdrom.c
- src/drivers/block_dev/ide/harddisk_dma.c
- src/drivers/block_dev/ide/harddisk_pio.c
- src/drivers/block_dev/ramdisk/Mybuild
- src/drivers/block_dev/ramdisk/ramdisk.c
- src/drivers/block_dev/ramdisk/static_ramdisk.c
- src/drivers/block_dev/stm32_sd/stm32f4_sd.c
- src/drivers/block_dev/stm32_sd/stm32f7_sd.c
- src/drivers/flash/flash_fs.c
- src/drivers/mmc/core/mmc_host.c
- src/drivers/mmc/host/sdhci/imx6_sdhci.c
- src/drivers/scsi/scsi_disk.c
- src/drivers/scsi/scsi_disk_create.c
- src/fs/driver/devfs/devfs_oldfs.c
- src/fs/driver/ramfs/Mybuild
- src/fs/driver/ramfs/ramfs.h
- src/fs/driver/ramfs/ramfs_dvfs.c
- src/fs/driver/ramfs/ramfs_ops.c
- templates/arm/qemu/mods.conf
* Fix ramfs_dvfs
* Add static ramdisk
* Clean block dev
To checking 
* build 'arm/qemu'
.* run Embox
* create files on remfs
```
mkdir -v /tmp
mount -t ramfs /dev/static_ramdisk /tmp
touch /tmp/1.txt
echo "test" > /tmp/2.txt
```
* check contains /tmp/2.txt. It must be "test"
> Clean bdev

- scripts/qemu/auto_qemu
- src/drivers/usb/hc/Mybuild
- src/drivers/usb/hc/uhci.h
- src/drivers/usb/hc/uhci_pci.c
implementation of uhci host controller driver, correctly works with usb flash device
> Uhci driver

- board_config/nucleo_h745zi_q.conf.h
- platform/stm32/h7/nucleo_h745zi_q/Mybuild
- platform/stm32/h7/nucleo_h745zi_q/arch.c
- platform/stm32/h7/nucleo_h745zi_q/stm32h7xx_hal_conf.h
- platform/stm32/templates/h7/nucleo_h745zi_q/board.conf.h
- platform/stm32/templates/h7/nucleo_h745zi_q/build.conf
- platform/stm32/templates/h7/nucleo_h745zi_q/lds.conf
- platform/stm32/templates/h7/nucleo_h745zi_q/mods.conf
- platform/stm32/templates/h7/nucleo_h745zi_q/rootfs/network
- platform/stm32/templates/h7/nucleo_h745zi_q/system_start.inc
- src/compat/libc/math/math_builtins.h
- src/drivers/net/stm32cube/Mybuild
- src/drivers/net/stm32cube/stm32h7cube_eth.c
- src/drivers/net/stm32cube/stm32h7cube_eth.h
- src/drivers/serial/stm32_usart/Mybuild
- src/drivers/serial/stm32_usart/stm32_usart_conf_h7.h
- src/drivers/serial/stm32_usart/stm_hal_msp.c
- third-party/bsp/stmh7cube/Mybuild
- third-party/bsp/stmh7cube/cube/Makefile
- third-party/bsp/stmh7cube/cube/Mybuild
Fix #2283 
* Add STM32H7Cube 
* Add templates for [NUCLEO-H745ZI-Q board](https://github.com/embox/embox/wiki/NUCLEO-H745ZI-Q) (CM7 core )
> 2283 add nucleo h745zi q

- src/drivers/clock/mips_clk/mips_clk.c
Do you wish for something like this? Attempt on #2289
> Add MIPS counter device

- project/qt4/templates/x86_qemu/mods.conf
- project/qt4/templates/x86_qemu/system_start.inc
- src/cmds/testing/input/mouse_fb_test/mouse_fb_test.c
- src/init/Mybuild
- src/init/system_start_service.c
- third-party/qt/Mybuild
- third-party/qt/plugins/generic/EmboxInput.my
- third-party/qt/tree/src/plugins/generic/emboxinput/emboxinput.pro
- third-party/qt/tree/src/plugins/generic/emboxinput/main.cpp
- third-party/qt/tree/src/plugins/generic/emboxinput/qemboxinput.cpp
- third-party/qt/tree/src/plugins/generic/emboxinput/qemboxinput.h
- third-party/qt/tree/src/plugins/platforms/emboxfb/emboxfbintegration.cpp
Add embox mouse Qt plugin. Tested with animatedtitles demo for project/templatesqt4/x86_qemu
> Add Qt mouse plugin for emboxfb platform

- project/qt4/templates/stm32f746g_discovery/lds.conf
- project/qt4/templates/stm32f746g_discovery/mods.conf
- project/qt4/templates/stm32f746g_discovery/qt_bin_create.sh
- project/qt4/templates/stm32f746g_discovery/start_script.inc
- src/cmds/bootloader/qspi_loader.c
- third-party/qt/Makefile
- third-party/qt/Mybuild
- third-party/qt/animatedtiles_fullscreen_option.txt
- third-party/qt/tree/src/plugins/generic/emboxinput/qemboxinput.cpp
Run animatedtiles Qt app on stm32f746g-discovery. Comment moveblocks and uncomment animatedtiles in start_script.inc to verify.
> Qt animatedtiles stm32

- src/cmds/hardware/lshw/Mybuild
- src/cmds/hardware/lshw/lshw.c
- templates/x86/qemu/mods.conf
This merge request does the following:-
- Adds  partial `lshw` command implementation
- Closes #1717
> Add lshw partial implementation

- src/arch/arm/armmlib/cpu_cache/armv7m_cpu_cache.c
- third-party/qt/Makefile
- third-party/qt/examples/qt_app_qspi_starter.c
- third-party/qt/fb_base_touchscreen_cursor.txt
* Hide cursor for touch screen (stm32f7)
* Fix non-cacheable MPU attrs.
> qt: Hide cursor for touch screen

- README.md
> minior: Update README.md

- platform/raspberry_pi/rpi2-model-b/build.conf
- platform/raspberry_pi/rpi2-model-b/mods.conf
- src/arch/arm/subarch/armv7a/Mybuild
- src/arch/arm/subarch/armv7a/cpu_reset.S
Add multiprocessing option according to the suggestion in #2317
> arch: Improve halt for multicores of Raspberry Pi 2

- platform/stm32/f0/nucleo_f030r8/Mybuild
- platform/stm32/f0/nucleo_f030r8/arch.c
- platform/stm32/templates/f0/nucleo_f030r8/build.conf
- platform/stm32/templates/f0/nucleo_f030r8/lds.conf
- platform/stm32/templates/f0/nucleo_f030r8/mods.conf
- platform/stm32/templates/f0/nucleo_f030r8/system_start.inc
- src/drivers/gpio/stm32/Mybuild
- src/drivers/gpio/stm32/stm32_gpio_conf_f0.h
- src/drivers/gpio/stm32/stm32_gpio_f0.c
- src/drivers/serial/stm32_usart/Mybuild
- src/drivers/serial/stm32_usart/stm32_usart_conf_f0.h
- src/drivers/serial/stm32_usart/stm_usart_f0.c
- src/drivers/serial/uart_dev.c
I have added port for nucleo-f030r8. It contains driver for gpio and usart (with internal gpio init for initialising gpio in arch method). Without HAL. Only my code.
> Nucleo f030r8

- src/tests/posix/Mybuild
- src/tests/posix/mkdir_test.c
> tests/posix: Add mkdir_test

- src/drivers/clock/imx6_gpt/imx6_gpt.c
- src/drivers/clock/sp804_timer/sp804_timer.c
Cleaning sp804 and imx6_gpt timers code
> drivers: clock: Fix code to look cleaner

- src/arch/arm/armmlib/exception_table.S
Fixes https://github.com/embox/embox/issues/2327
> cortex-m: Fix default exception handler's sp value

- src/compat/posix/fs/dirent/dirent_oldfs.c
- src/fs/driver/cifs/cifs.c
- src/fs/driver/dfs/dfs.c
- src/fs/driver/ext2/ext2.c
- src/fs/driver/ext3/ext3.c
- src/fs/driver/ext4/ext4.c
- src/fs/driver/fat/fat_common.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/driver/fat/fat_oldfs.c
- src/fs/driver/fuse/fuse_fs_driver.c
- src/fs/driver/initfs/initfs_oldfs.c
- src/fs/driver/jffs2/jffs2.c
- src/fs/driver/nfs/nfs.c
- src/fs/driver/ntfs/ntfs.c
- src/fs/driver/pseudofs/pseudofs.c
- src/fs/driver/ramfs/ramfs.h
- src/fs/driver/ramfs/ramfs_dvfs.c
- src/fs/driver/ramfs/ramfs_oldfs.c
- src/fs/driver/ramfs/ramfs_ops.c
- src/fs/dvfs/dvfs_util.c
- src/fs/dvfs/inode.c
- src/fs/dvfs/inode.h
- src/fs/inode.c
- src/fs/inode.h
- src/fs/syslib/kfsop.c
- src/fs/vfs.c
- src/include/fs/fs_driver.h
- src/security/smac/smac_security.c
- templates/arm/qemu/mods.conf
* Clean fs
* Extract common code in fatfs & ramfs
> Improve fatfs

- mk/main-stripping.sh
- mk/mybuild/lang/CxxCmd.my
- mk/script/application_template.c
- mk/script/build/build-gen.mk
- mk/script/c-runtime-inject.mk
- src/cmds/testing/cxx/ctors/Mybuild
- src/cmds/testing/cxx/ctors/cxx_ctors_demo.cpp
- src/compat/cxx/core/cxx_constructors_global.c
- templates/arm/c++_demo/mods.conf
Automatically call ctors in C++ main() if `@CxxCmd` annotation specified.
> Automatically call ctors in C++ main()

- platform/raspberry_pi/rpi0/mods.conf
- src/drivers/mailbox/Mybuild
- src/drivers/mailbox/bcm2835_mailbox.c
- src/drivers/mailbox/bcm2835_mailbox.h
- src/drivers/mailbox/bcm2835_mailbox_property.c
- src/drivers/mailbox/bcm2835_mailbox_property.h
- src/tests/mailbox/Mybuild
- src/tests/mailbox/bcm2835_property.c
Add support for "new" Property interface for mailbox.  Frame buffer interface is actually depreciated.
> Mailbox property

- mk/extbld/lib.mk
mk/extbld/lib.mk: git:
- supported checking out particular SHA-1, branch or tag via PKG_VER parameter;
- fixed an issue with copying git directory (the EXTRACT phase).
> mk/extbld/lib.mk: git: supported checking out particular SHA-1, branch or tag via PKG_VER parameter

- README.md
> Remove travis-ci status from README

- src/cmds/dma/Mybuild
- src/cmds/hardware/spi/Mybuild
- src/drivers/dma/Mybuild
- src/drivers/dma/pl330/Mybuild
- src/drivers/dma/stm32_cube/Mybuild
- src/drivers/spi/Mybuild
> drivers: Fix dma module dependences

- src/cmds/hardware/ccid/ccid_cmd.c
- src/cmds/hardware/lshw/lshw.c
- src/cmds/hardware/lsusb/lsusb.c
- src/drivers/net/usbnet/usbnet.c
- src/drivers/usb/class/usb_hid.c
- src/drivers/usb/hc/ohci/ohci.h
- src/drivers/usb/usb_config.c
- src/drivers/usb/usb_hub.c
- src/include/drivers/usb/usb.h
Clean USB stack
Work on multi-configuration devices support for host USB mode
> Improve usbnet

- src/cmds/blockdev.c
- src/cmds/cpuinfo.c
- src/cmds/hardware/lshw/lshw.c
- src/compat/libc/include/inttypes.h
- src/fs/driver/initfs/initfs.h
> 2540 fix riscv64/qemu template

- project/pjsip/templates/stm32f746g-discovery/mods.conf
> templates: Fixed project/pjsip/stm32f746g-discovery

- src/cmds/hardware/lsusb/lsusb.c
PR made for related issues: #2529, #2532
Additions are derived from [usbutils](https://github.com/gregkh/usbutils/blob/master/lsusb.c) and tested on x86 qemu with 3 dummy usb drives.
> Add lsusb options

- .gitignore
- README.md
- confset
- mk/main.mk
'confset' feature allows fast switching between configs (templates)
> mk: Enable 'confset' feature in the build system

- templates/x86/test/units/mods.conf
> templates: minor: Update x86/test/units

- src/drivers/servo/Mybuild
- src/drivers/servo/stm32f7_pwm.c
- src/fs/Mybuild
- third-party/lua/lua/Mybuild
Implementation for STM32F764G-Discovery pwm driver
> stm32f7 servo

- third-party/cmsis/Makefile
- third-party/cmsis/Mybuild
- third-party/cmsis/example/Mybuild
- third-party/cmsis/example/cmsis_version.c
Add third_party CMSIS lib v5.9.0 from [official repo](https://github.com/ARM-software/CMSIS_5)
> Add cmsis v5.9.0

- src/tests/string/Mybuild
- src/tests/string/strerror_test.c
- templates/x86/test/units/mods.conf
> Add some tests for strerror

- src/compat/posix/include/grp.h
Just adding some missing header
> posix fs stubs

- mk/extbld/toolchain.mk
Fix EMBOX_IMPORTED_LDFLAGS_FULL for correct configuration of external programs
> mk/extbld: Fix EMBOX_IMPORTED_LDFLAGS_FULL

- project/paho_mqtt_cpp/templates/arm_qemu/system_start.inc
Commands: "service telnetd", "service httpd", "stl_demo_sort1" were removed
> removed not used cmds

- src/drivers/servo/stm32_servo_conf_f3.h
- src/drivers/servo/stm32_servo_conf_f4.h
> Missing servo conf

- third-party/bsp/stmf4cube/cube/Mybuild
- third-party/bsp/stml4cube/cube/Mybuild
-DSTM32F4_CUBE -DSTM32F4_CUBE_1_25_0 for stmf4cube
-DSTM32L4_CUBE -DSTM32L4_CUBE_1_14_0 for stml4cube
> third-party/bsp: Add defines using stmf4cube & stml4cube

- src/compat/posix/include/sys/resource.h
- src/tests/lib/libiconv/Mybuild
- src/tests/lib/libiconv/libiconv_test.c
- third-party/lib/libiconv/Makefile
- third-party/lib/libiconv/Mybuild
- third-party/lib/libiconv/patch.txt
1) Added patch for libiconv-1.17
2) Added tests for <iconv.h>
> add libiconv

- src/drivers/flash/qspi/stm32l4_qspi.c
https://github.com/embox/embox/wiki/QSPI-flash
> drivers: Adding qspi flash device for stm32l4-discovery

- project/paho_mqtt_cpp/templates/stm32f769i-discovery/build.conf
> templates: Fix project/paho_mqtt_cpp/stm32f769i-discovery

- project/mosquitto/templates/stm32769i-discovery/mods.conf
include third_party.cmd.mosquitto_pub
include third_party.cmd.mosquitto_sub
to  project/mosquitto/templates/stm32769i-discovery/mods.conf file
> Added mosquitto cmds:

- src/compat/posix/include/pthread.h
- src/compat/posix/pthread/pthread.c
- src/tests/posix/pthread/Mybuild
- src/tests/posix/pthread/pthread_attributes_test.c
- src/tests/posix/pthread/pthread_policy_test.c
- templates/x86/qemu/mods.conf
> pthread attr getstack

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/fmod_tests.c
- templates/x86/qemu/build.conf
> 2791 add tests for fmod

- src/compat/libc/math/tests/sqrt_tests.c
I have added some test cases for the sqrt() function based on the return cases in the link below. All the tests have been successful.
[https://man7.org/linux/man-pages/man3/sqrt.3.html](url)
> "Added test cases for sqrt()"

- src/arch/aarch64/embox.lds.S
- src/arch/aarch64/include/asm/hal/reg.h
- src/arch/aarch64/include/asm/modes.h
- src/arch/aarch64/mmu/mmu.c
- src/drivers/serial/pl011/pl011.c
- src/mem/vmem/vmem.h
Hello!
I've come around embox recently and faced some issues with current aarch64 state. 
I had issues with build and boot which I've fixed in scope of this PR. I've tried to separate each change logically to make things easier to revert just in case.
Tested locally on stock 6.2.0 qemu and self-built 8.0.1.
> aarch64: fix build and make it boot cleanly

- src/compat/libc/math/tests/fmod_tests.c
https://github.com/embox/embox/pull/2813
> fmod_tests: Comlete test cases for `fmod()`

- src/compat/libc/math/libm_simple/sqrt.c
sqrt root checks for negative Infinity and NaN arguments and respective returns as per standard
> fix sqrt to comply with standard on negative, NaN and Inf values

- src/cmds/service.c
- src/compat/posix/proc/exec.c
Added executable validation check, so it can return error in case executable not found(especially in vfork) and other minor execv refactoring.
In service.c service_run: handle when execution failed; service_run - service_add already running logic. General service.c refactoring.
> cmds/service:service refactor/minor execv refactor

- scripts/expect/ssh.exp
Now that dropbear accepts multiple connections and correctly interprets authentication success this test should pass
#1720
> test: continuous testing-multiple ssh logins test

- src/compat/posix/idx/idesc_pipe.c
- src/compat/posix/idx/tests/pipe_close_notify_test.c
Edited pipe status logic, so that now the reading end of the pipe is always ready to read when write-end is closed. The read buffer will be zero-length. (copying Linux behaviour, since, as stated earlier, POSIX doesn't seem to have strict directive for that)
Some additions to the test for that situation
fixed #2869
> idesc_pipe: added read-end wakeup on write-end close

- scripts/mandatory_img.sh
- scripts/trybuild
- scripts/uboot-uimage
Hi @anton-bondarev! Yet another PR in the series of PRs related to #2835. This time changes are a bit boring: just wrapping variables in double quotes.
> Quote variables containing paths in shell scripts

- scripts/app_diff.sh
Hi @anton-bondarev! Another PR in the #2835 series.
I believe this PR is the last one and #2835 may be closed after merging it.
This PR:
1. Wraps variables containing paths in double quotes to prevent them from globbing and word splitting.
2. Replaces `! -z` with `-n` in condition check (`-z` — is empty?, `-n` — is not empty?) — new condition does the same, but looks cleaner.
3. Replaces pushd/popd with `cd` in subshell. Workdir is changed in subshell and parent shell's workdir remains untouched.
4. Replaces implicit array-of-strings-to-string conversion with explicit array expansion.
> Fix app_diff.sh according to ShellCheck guidelines

- src/arch/arm/armlib/boot/Mybuild
- src/arch/arm/armlib/exceptions/dabt_handler.c
- src/arch/arm/armlib/exceptions/pabt_handler.c
- src/arch/arm/include/asm/cp15.h
- src/arch/arm/mmu/Mybuild
- src/arch/arm/mmu/mmu_common.c
- src/arch/arm/mmu/mmu_small_page.c
- src/arch/arm/mmu/mmuinfo.c
Now project/mesa3d/arm_qemu can be built :)
> [arm] Move cp15-related functions to cp15.h

- src/include/kernel/time/clock_source.h
- src/include/kernel/time/itimer.h
- src/include/kernel/time/time.h
- src/kernel/time/timeval.c
Hi! I had some spare time and added a couple of documenting comments here and there. I hope I didn't misunderstand the code. :)
> Extend kernel/time documentation

- scripts/autotest/testsuite/modbus/modbus_bits_read/make_test_client.sh
- scripts/autotest/testsuite/modbus/modbus_bits_read/test.exp
- scripts/autotest/testsuite/modbus/modbus_bits_read/test_client/Makefile
- scripts/autotest/testsuite/modbus/modbus_bits_read/test_client/mb_test_client.c
- src/cmds/modbus_server/Mybuild
- src/cmds/modbus_server/modbus_server.c
Simple modbus test server and client.
Client reads info from test server in loop 1000 times. Server alternates state bits every iteration.
Test is done in form of autotest test suite
> Modbus test

- src/cmds/net/netstat/netstat.c
-0 option for netstat to show tcp sockets grouped by parent-child hierarchy
some minor output edit so that everything is nicely lined up
> netstat: show tcp sockets grouped by hierarchy

- src/arch/arm/mmu/mmu_common.c
Fix build for   `arm/am3505` template
> arch/arm: Fix c15 registers name

- src/cmds/service.c
Service utility didn't take any action when service unexpectedly stopped after the last start.
Necessary checks added in this PR
> cmd: service: chk that service hasn't exited since start

- src/tests/stdlib/Mybuild
- src/tests/stdlib/memset.c
> tests: Add unit test for memset()

- src/fs/driver/initfs/initfs_dvfs.c
> fix initfs_lookup

- platform/stm32/templates/f4/nucleo_f410rb/build.conf
- platform/stm32/templates/f4/nucleo_f410rb/mods.conf
Improve template for stm32 Nucleo64-F410RB board - expand functionality and optimize compiler flags
> improve stm32/nucleo_f410rb template

- src/net/socket/tcp_sock.c
When listening socket gets closed established connections on accept queue never get closed, instead being released straight away. Commit addresses this issue, resetting these connections
> tcp: reset established but not accept()ed connections

- src/fs/dvfs/dvfs_kfile.c
- src/fs/syslib/kfile_node.c
> added st_blocks filling in stat()

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/pow_tests.c
- Create tests for pow().
- Add new module to Mybuild
> test: Add tests for pow() from math.h

- board_config/stm32f103_bluepill.conf.h
- platform/stm32/f1/stm32f103_bluepill/Mybuild
- platform/stm32/f1/stm32f103_bluepill/arch.c
- platform/stm32/f1/stm32f103_bluepill/stm32f1xx_hal_conf.h
- platform/stm32/templates/f1/stm32f103_bluepill/board.conf.h
- platform/stm32/templates/f1/stm32f103_bluepill/build.conf
- platform/stm32/templates/f1/stm32f103_bluepill/lds.conf
- platform/stm32/templates/f1/stm32f103_bluepill/mods.conf
This is based on similar board stm32vl_discovery.
Embox boots successfully and even prints out some info, but you can't input anything to console,
probably because clocks weren't adjusted for this MCU.
> Added partial support for stm32f103 bluepill board

- src/cmds/net/route/route.c
packetdrill in default configuration executes route utility with hostname containing CIDR nemask notation. Previous version of ip string address to binary conversion ignored whatever followed the address. With introduction of more accurate address conversion functions route became unable to correctly parse such a string, which lead for packetdrill and potentially others to fail.
This commit addresses CIDR notation handling in route utility
> utils: route CIDR netmask notation support

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/math_test_sin.c
> Added tests for sin()

- src/kernel/thread/core.c
> kernel: Fix thread creation from the 'boot' thread

- mk/flags.mk
- mk/script/build/build-gen.mk
- mk/script/incinst.mk
- mk/variables.mk
- project/libpcap/templates/x86_qemu/mods.conf
- src/arch/arm/fpu/fpv5/fpu.c
- src/drivers/mmc/core/mmc_host.c
- third-party/lib/glib/Makefile
- third-party/lib/libffi/Makefile
- third-party/lib/libiconv/Makefile
- third-party/lib/ncurses/Makefile
- third-party/lib/zlib/Makefile
- third-party/mc/Makefile
- third-party/xen/Makefile
Fix some typos and errors related to log levels
> log levels fixes

- src/cmds/testing/ktime_get_timeval_test/ktime_gettv_test.c
- src/kernel/time/clock_source.c
> clock_source_read() fix

- board_config/stm32vl_discovery.conf.h
- platform/stm32/templates/f1/stm32vl-discovery/mods.conf
- platform/vostok/templates/vostok_uno_vn035/mods.conf
- platform/vostok/templates/vostok_uno_vn035/start_script.inc
- src/drivers/serial/stm32cube_usart/stm_hal_msp.c
> 3029 fix stm32f1 uart

- platform/stm32/templates/f1/stm32f103_bluepill/mods.conf
fixed clock from 8 MHz to 48 MHz
> stm32f103_bluepill: clock fix

- project/server61850/templates/arm_qemu/mods.conf
- project/server61850/templates/arm_qemu/system_start.inc
- project/server61850/templates/x86_qemu/system_start.inc
- src/compat/posix/net/arpa_inet.c
- src/compat/posix/net/socket.c
- src/net/sock.c
> 3115 treat msg dontwait flag

- src/cmds/net/tftp/tftp.c
- src/drivers/flash/stm32cube_flash/stm32_flash_common.c
Add support for unaligned access, add logs for bad tftp options etc
> stm32 flasher/usability

- platform/banana_pi/templates/bpi_p2_zero/README.md
- platform/banana_pi/templates/bpi_p2_zero/boot.cmd
- platform/banana_pi/templates/bpi_p2_zero/bpi_p2_sdc.sh
- platform/banana_pi/templates/bpi_p2_zero/build.conf
- platform/banana_pi/templates/bpi_p2_zero/create_image.sh
- platform/banana_pi/templates/bpi_p2_zero/genimage.cfg
- platform/banana_pi/templates/bpi_p2_zero/lds.conf
- platform/banana_pi/templates/bpi_p2_zero/mods.conf
- platform/banana_pi/templates/bpi_p2_zero/system_start.inc
generally speaking, this is not so much a new platform as the experience of using u-boot
> append platform/templates/bpi_p2_zero. Use u-boot

- src/lib/crypt/des/tests/Mybuild
- src/lib/crypt/des/tests/des_test.c
Added new test case to des_test.c
Added embox.lib.libcrypt.des dependency to des_test module
> updated des test

- src/lib/crypt/Mybuild
- src/lib/crypt/b64/b64.c
- src/lib/crypt/b64/tests/Mybuild
- src/lib/crypt/b64/tests/b64_test.c
- src/lib/crypt/des/Mybuild
- src/lib/crypt/des/tests/Mybuild
- src/lib/crypt/md5/tests/Mybuild
- src/lib/crypt/md5/tests/md5_test.c
1) Added des to LibCrypt module
2) Fixed b64.c
3) Added tests for b64 and md5
> Tests for crypt module algorithms

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/math_test_atan.c
- templates/x86/test/units/mods.conf
> Add tests for atan

- platform/vostok/templates/vostok_vg015_dev/mods.conf
- platform/vostok/templates/vostok_vg015_dev/start_script.inc
- src/arch/riscv/embox.lds.S
- src/cmds/hardware/lsblk/lsblk.c
- src/drivers/flash/niiet_mflash/Mybuild
- src/drivers/flash/niiet_mflash/niiet_mflash.c
- src/fs/driver/dfs/Mybuild
- src/fs/driver/dfs/dfs.c
> Niiet mflash driver

- third-party/lua/lib/luasocket/Makefile
- third-party/lua/lib/luasocket/pkg_patch.txt
- third-party/lua/lua/Makefile
- third-party/lua/lua/pkg_patch.txt
> third-party: Update lua version to 5.4.6

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/math_test_sinh.c
- templates/x86/test/units/mods.conf
Modify the lib `math_simple` to `math_openlibm` in conf/mods.conf to make compiling correct
Resolve: #2991
See also: #2992, #2960
> compat: minor: Add tests for sinh() from math.h

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/math_test_cos.c
- templates/x86/test/units/mods.conf
#2964 I have resolved this issue. Please review this pull request.
> Added unit-tests for cos() functions (math.h)

- src/compat/libc/math/tests/math_test_abs.c
- src/compat/libc/math/tests/math_test_sinh.c
- src/compat/libc/math/tests/sqrt_tests.c
> chore: fix `@author` typo in libc tests

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/math_test_cosh.c
- templates/x86/test/units/mods.conf
Fixes issue : #3270 
This pull request adds unit tests for cosh() function.
> Added unit-tests for cosh() functions (math.h) 

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/asin_tests.c
> 2988 bug asin

- src/drivers/interrupt/sifive_plic/Mybuild
- src/drivers/interrupt/sifive_plic/sifive_plic.c
- src/drivers/interrupt/sifive_plic/sifive_plic.h
- src/include/drivers/irqctrl.h
#2079 
This pull request introduces the implementation of the Platform-Level Interrupt Controller (PLIC) driver for the SiFive U54-MC Core. The driver includes functionality for enabling, disabling, setting priority, and handling interrupts for multiple harts (hardware threads). 
[SiFive U54-MC Core Complex Manual v1p0](https://static.dev.sifive.com/U54-MC-RVCoreIP.pdf)
Please review this pull request and suggest required changes. Thank you!
> RISCV: Implement SiFive PLIC Driver

- src/arch/x86/include/asm/ap.h
- src/arch/x86/kernel/smp/ap_trampoline.S
- src/arch/x86/kernel/smp/smp.c
- src/drivers/interrupt/apic/lapic.c
changed the lapic driver and ap_trampoline storage
> Update with Multicore on x86

- .github/workflows/ci.yml
This reverts commit 3436061f8429d789c0d50917e0035fc271047d3b.
> Revert "github: Add pull_request_target event that triggers CI"

- src/arch/x86/lib/cpu_performance/cpu_counter.c
- src/arch/x86/lib/cpu_performance/cpu_info.c
- src/cmds/hardware/cpuinfo/cpuinfo.c
- src/lib/cpu_info/libcpu_info.h
- Add CPU number information
- Add judgment of max_cpuid_leaf
- Fix time stamp info on x86
Happy to update PR :)
> Update cpu_info command

- .gitignore
Add files to be ignored generated by cscope
> gitignore: Add cscope format files

- src/arch/x86/include/asm/ptrace.h
- src/arch/x86/kernel/irq_entry.S
- src/include/kernel/task.h
- src/kernel/sched/sched.c
- src/kernel/task/kernel_task.c
- src/kernel/task/multi/multi.c
- src/kernel/task/multi/multi.h
- src/kernel/task/task_resource.c
- src/kernel/thread/Mybuild
- src/kernel/thread/core.c
- src/kernel/thread/thread_switch.c
This PR actually is my personal opinion. Maybe somewhere is not good enough.
In fact, it doesn’t matter don’t merge.
> Add comments and debug informations

- src/arch/e2k/entry.c
- src/arch/x86/kernel/smp/smp.c
- src/include/hal/cpu.h
- src/kernel/Stack.my
- src/kernel/sched/boot_thread.c
This PR should be update with latest embox/master to change every place.
If you decide to add this option, please contact me
> kernel: define size of BSP and AP stack size separately

- src/drivers/clock/lapic_timer/lapic_timer.c
- src/drivers/interrupt/apic/ioapic.c
Modify init function to support initialization each APs
> driver:clock: Add SMP condition of lapic_clock

- board_config/stm32l152c_discovery.conf.h
- board_config/stm32l4discovery.conf.h
stm32l152c_discovery.conf.h & stm32l4discovery.conf.h
> board configs: minimal changes for REGMAP option testing

- project/openssl3/templates/arm_qemu/mods.conf
- project/openssl3/templates/arm_qemu/system_start.inc
- project/openssl3/templates/x86_qemu/mods.conf
- third-party/lib/openssl3/Makefile
- third-party/lib/openssl3/embox.conf
Edited embox.conf
Fixed arm template
> Openssl fix

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/log_test.c
- templates/x86/test/units/mods.conf
sorry about previous PR, i'm newbie at this
> 3335 add log tests

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/cbrt_test.c
- templates/x86/test/units/mods.conf
1. The test cases encompass all requisite conditions specific to the cube root function.
2. Implemented the necessary modifications in mods, conf, and mybuild to support cbrt_test.
> Added test cases for cbrt function of math lib for embox

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/modf_test.c
#3334 libc/math/tests. Added tests for modf()
> Tests for modf

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/copysign_test.c
- templates/x86/test/units/mods.conf
> add math testsuite: copysign

- src/compat/libc/math/math_builtins.h
- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/atanh_test.c
- templates/x86/test/units/mods.conf
> Add atanh() function test file

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/exp2_test.c
- templates/x86/test/units/mods.conf
Hi!! I made the tests for exp2() as requested in issue #3453 
Let me know if it needs any change, I did it based on previous accepted PRs!
> Add tests for exp2() from math.h

- src/arch/mips/kernel/exc_init.c
> mips: Check __mips_isa_rev when setting EBase register

- src/lib/libds/indexator/index_init.c
> libds: Fix cleanning memory in index_init()

- COPYRIGHT
> Happy 2025 year!

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/asinh_test.c
- templates/x86/test/units/mods.conf
And they even pass successfully!
> Add unit tests for asinh() from math.h

- platform/syntacore/templates/scr3_32/build.conf
- platform/syntacore/templates/scr3_32/lds.conf
- platform/syntacore/templates/scr3_32/mods.conf
- platform/syntacore/templates/scr3_64/build.conf
- platform/syntacore/templates/scr3_64/lds.conf
- platform/syntacore/templates/scr3_64/mods.conf
- scripts/qemu/auto_qemu
> Add templates for Syntacore (SCR3_32 & SCR3_64) platfroms

- templates/riscv/sifive_u/mods.conf
in  templates/riscv/sifive_u/mods.conf
> Adjust clock frequency parameters

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/llrint_test.c
- src/compat/libc/math/tests/lrint_test.c
- templates/x86/test/units/mods.conf
> math/tests: Adding llrint & lrint tests 

- platform/licheepi/templates/licheepi_4a/README.md
- platform/licheepi/templates/licheepi_4a/build.conf
- platform/licheepi/templates/licheepi_4a/lds.conf
- platform/licheepi/templates/licheepi_4a/mods.conf
- platform/licheepi/templates/licheepi_4a/system_start.inc
- src/arch/riscv/include/asm/regs.h
- src/drivers/clock/riscv_clk/Mybuild
- src/drivers/clock/riscv_clk/riscv_timer_csr.c
- src/drivers/interrupt/riscv_clint/Mybuild
- src/drivers/interrupt/riscv_clint/riscv_clint.c
Initial support yet. features such as ISA extendsion and smp are on the TODO list.
This PR based on #3573
> Add lpi4a riscv platform 

- src/cmds/net/ping/ping.c
add -p flag feature implementation - fill packet with specified pattern up to 16 bytes
(there was a switch case statement but this option did not work)
also complete /* TODO: get unique id */ by making id the same as pid of ping
> Ping: implement -p option and complete TODO

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/log1p_test.c
- templates/x86/test/units/mods.conf
Added test case for log1p function.
> Math : Adding log1p math function

- scripts/continuous/run.sh
- scripts/qemu/auto_qemu
- src/arch/riscv/kernel/smp/ap_trampoline.S
- src/arch/riscv/kernel/smp/smp.c
- src/tests/smp/simult_thread_test.c
Fix some mistakes might crash and update autoqemu scripts
> Prepare and fix smp 64bits bugs

- platform/licheepi/templates/smp/README.md
- platform/licheepi/templates/smp/build.conf
- platform/licheepi/templates/smp/lds.conf
- platform/licheepi/templates/smp/mods.conf
- platform/licheepi/templates/smp/smp-uboot.patch
- platform/licheepi/templates/smp/system_start.inc
- templates/riscv64/smp/build.conf
- templates/riscv64/smp/lds.conf
- templates/riscv64/smp/mods.conf
- templates/riscv64/smp/system_start.inc
> Add 64bit smp templates

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/ldexp_test.c
- templates/aarch64/test/units/mods.conf
- templates/riscv64/test/units/mods.conf
- templates/x86/test/units/mods.conf
> Add unit tests for math.h ldexp() function

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/trunc_test.c
- templates/x86/test/units/mods.conf
> Add trunc() unit tests

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/fdim_test.c
- templates/x86/test/units/mods.conf
fix issue: [#3645](https://github.com/embox/embox/issues/3645)
How about it? :)
> add unit tests for fdim() function in math.h

- .github/workflows/ci.yml
- Remove event "pull_reqeuest"
- Add event "push"
- Add event "pull_request_review" that triggers when a PR form fork is approved
> github: Change events that trigger workflows

- platform/syntacore/templates/scr5_32/build.conf
- platform/syntacore/templates/scr5_32/lds.conf
- platform/syntacore/templates/scr5_32/mods.conf
- scripts/qemu/auto_qemu
Add: platform/syntacore/scr5_32.
Also update scripts/qemu/auto_qemu
> Add syntacore platform/syntacore/scr5_32

- project/ism43362_eS_wifi/cmds/Mybuild
- project/ism43362_eS_wifi/cmds/ism43362.c
- project/ism43362_eS_wifi/cmds/ism43362.h
- project/ism43362_eS_wifi/cmds/ism43362_test.c
- project/ism43362_eS_wifi/templates/stm32l4-discovery/board.conf.h
- project/ism43362_eS_wifi/templates/stm32l4-discovery/build.conf
- project/ism43362_eS_wifi/templates/stm32l4-discovery/conf_setup.inc
- project/ism43362_eS_wifi/templates/stm32l4-discovery/lds.conf
- project/ism43362_eS_wifi/templates/stm32l4-discovery/mods.conf
- project/ism43362_eS_wifi/templates/stm32l4-discovery/rootfs/network
- project/ism43362_eS_wifi/templates/stm32l4-discovery/start_script.inc
Added ism433362_eS_wifi project to configure and test the wifi module on the stm32l4-discovery(B-L475E IoT 01A2c) board.
> Project to setup a wifi module on the B-L475E IoT 01A2c board

- project/ism43362_eS_wifi/drivers/eswifi_drv.c
Add setup values(ip and Mac address) for eth0
> Add setup ip and mac addr

- project/at/src/cmds/net/ws_client.c
- project/at/src/cmds/net/ws_client.my
- project/at/templates/x86_qemu/mods.conf
- src/lib/crypt/Mybuild
- src/lib/crypt/sha1/Mybuild
- src/lib/crypt/sha1/sha1.c
- src/lib/crypt/sha1/sha1.h
- src/lib/crypt/sha1/tests/Mybuild
- src/lib/crypt/sha1/tests/sha1_test.c
- src/net/lib/websocket/Mybuild
- src/net/lib/websocket/websocket.c
- src/net/lib/websocket/websocket.h
- src/net/lib/websocket/websocket_client.c
- src/net/lib/websocket/websocket_frame.c
New Library: 
`sha1`: for implement of sha1 algorithm.
`websocket`: for simple websocket support
Related command: 
`ws_client`
`-m [message]`: sending [message] after connecting
`-p`: sending ping every 5 seconds
Example:
```
root@embox:/#ws_client -m "Hello" ws://10.0.2.10:8080/
Connecting to ws://10.0.2.10:8080/...
Will send message: Hello
ws_connect: URL=ws://10.0.2.10:8080/
Parsed URL: host=10.0.2.10, port=8080, path=/
Resolving 10.0.2.10...
Connecting to 10.0.2.10:8080...
TCP connected, performing WebSocket handshake...
=== SENDING REQUEST (174 bytes) ===
GET / HTTP/1.1
Host: 10.0.2.10
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: J+DzDtwSECzZOjvnyQdrjA==
Sec-WebSocket-Version: 13
Origin: http://10.0.2.10
=== END REQUEST ===
=== RECEIVED 205 bytes (total: 205) ===
=== …
```
> net: Add simple websocket support
