- src/compat/posix/proc/vfork.c
Errno should always be positive, but negative error code was written
> Fix vfork errno value on error

- src/kernel/thread/Mybuild
There was NoRuntime dependency on thread_local, which could use
sysmalloc. There is no need to say, that allocator was not initialized.
> Fix obscure initialization bug

- .travis.yml
- README.md
This change makes Slack notifications less verbose, directs pushes to 'coverity' branch to the [proper](https://scan.coverity.com/projects/700) Coverity Scan project, and adds 2 more templates to test.
> Travis & Coverity

- platform/stm32f4_iocontrol/http_admin/app.js
- platform/stm32f4_iocontrol/http_admin/css/app.css
- platform/stm32f4_iocontrol/http_admin/partials/leds.html
- Use monospace font-family as default for .block-caption
- Add led.short_name field
> webui: Reduce too long led's name (maxlen is 9)

- third-party/lib/openlibm/Makefile
- third-party/lua/lib/luasocket/Makefile
- third-party/mruby/Makefile
It seems, that contents of zip archives has been changed somehow, causing builds to fail due to md5 sum mismatch.
Anyway, tgz is a better choice.
> extbld: Change .zip to .tar.gz for archives from GitHub

- src/drivers/block_dev/block_dev_common.c
The problem was in the block_dev driver. Now it should be fine.
> x86-test-fs-fix

- src/compat/posix/fs/dvfs/open.c
dvfs open fails to build, at least at arm/stm32_modbus
> dvfs: Fix dvfs open build

- mk/script/build/oldconf-gen.mk
The warning was introduced in e51a50a ("mk: oldconf: Remove processing of option.conf from scripts / macros") merged through #750.
> mk: oldconf: Fix an undefined 'config_h' variable warning

- src/arch/mips/kernel/ipl_impl.h
- src/arch/ppc/kernel/ipl_impl.h
- src/arch/usermode86/host/host_irq.c
- src/arch/x86/kernel/ipl_impl.h
- src/kernel/sched/sched.c
Previously the function restored ipl only in case disabled IRQs in several architectures, that might cause problems from time to time. This request fixes the issue for such architectures, namely mips, x86, ppc and usermode.
> Ipl restore fix

- mk/mybuild/lang/AddCflags.my
- mk/mybuild/lang/Cflags.my
- mk/script/build/build-gen.mk
The reason:
* It's needed when we want to add some extra clags to the end of the current Embox's CFLAGS when compiling an external library. Currently it is needed in branches stm32f3discovery-port and usbnet
What's done:
* New @Cflags annotation is added
! Please, be careful when reviewing this change, because of I am newbie in gnu make
> mk-addcflag-annotation: New Cflags annotation

- mk/ugly.mk
That is, given two modules:
module api {
option foo
}
module impl extends api {
option bar
}
There are two options defined for instances of module `impl`:
its own option `bar` and an inherited `foo` option.
Before this change, one could only use `OPTION(api, foo)` to access a
value of `foo` from C-code at compile time. Now it is also aliased
through `OPTION(impl, foo)`, even though `impl` doesn't define `foo`
explicitly.
> mybuild: gen: Define alises for options inherited from supertypes

- platform/lego_nxt/cmds/menu/Mybuild
- platform/lego_nxt/cmds/snake/Mybuild
- platform/lego_nxt/drivers/sensors/Mybuild
- platform/lego_nxt/example/box_around/Mybuild
- platform/lego_nxt/example/pendulum/Mybuild
- platform/lego_nxt/example/sensors/Mybuild
- platform/lego_nxt/example/wake_up/Mybuild
- src/cmds/fs/Mount.my
- src/cmds/fs/Umount.my
- src/cmds/shell/Mybuild
- src/cmds/shell/diag_shell/Mybuild
- src/cmds/shell/shell.h
- src/cmds/user/Login.my
- src/cmds/user/Su.my
- src/compat/libc/stdlib/Mybuild
- src/compat/posix/proc/Proc.my
- src/drivers/clock/Mybuild
- src/drivers/diag/Mybuild
- src/init/Mybuild
- src/kernel/thread/Mybuild
- src/kernel/time/Time.my
- src/kernel/time/timer/Mybuild
- src/mem/misc/Mybuild
- src/tests/kernel/Mybuild
- templates/arm/stm32_modbus/mods.config
Remove some rarely used features of Mybuild like imports or features. Also avoid clashes between module and package names that could only lead to ambiguity.
The only changes that affect the logic are in the last two commits. Though it'd be nice if you also check that I didn't miss anything when renaming modules (i.e. references to options in C code).
> Cleanup mybuild files

- src/drivers/interrupt/Mybuild
- src/drivers/interrupt/bpi_intc.c
- src/drivers/interrupt/bpi_intc.h
- templates/arm/bpi/mods.config
As discussed, this change provides basic support for SGI on BananaPi, successfully passing all IRQ tests.
> BananaPi port: working SGI

- mk/extbld/arch-embox-gcc
Now PWD occuriencies in middle of words aren't substituted.
Problem arise when repo cloned to /embox
> Fix extbld toolchain

- templates/arm/stm32_modbus/mods.config
diag_shell was in conflict by tish, diag_shell picked as shell
implementation. So background feature ('&') was not implemented.
> Fix arm/stm32_modbus template

- scripts/qemu/auto_qemu
- templates/arm/footprint_eval_qemu/lds.conf
- templates/arm/qemu/lds.conf
There were some problems with commented options. For example, it you will replace
@Runlevel(2) include embox.driver.net.virtio
with
//@Runlevel(2) include embox.driver.net.virtio
(i.e. comment this string), autoqemu will try to use nic type "//virtio"
1) Original regex was not correct
2) There is no need to analyze commented strings
This branch fixes this issue
> Autoqemu comments handling fix

- src/fs/driver/devfs/devfs_dvfs.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs.h
- src/fs/rootfs_dvfs.c
Implement automatic mount of required FS on system initialization.
Corresponding folders are now being created even if root file system is read-only.
> Rootfs automount

- src/drivers/block_dev/ramdisk/ramdisk.c
- src/drivers/block_dev/ramdisk/ramdisk.h
- src/drivers/block_dev/ramdisk/ramdisk_dvfs.c
- src/fs/driver/fat/fat_common.c
- src/fs/driver/fat/fat_dvfs.c
Fix error on file create. Error was related to ramdisk block size (default 4096, and fat was expecting 512).
> fatfs file create error fix

- mk/gensums.py
Centos/RHEL 7/6: default python 2.6.
> Python 2.6 doesn't support dict comprehension syntax

- mk/image2.mk
- mk/script/build/build-gen.mk
The necessary behavior is handled through `$(common_prereqs)` that contains a secondarily-expanded order-only `| $(@D)/.` prerequisite.
This should fix weird and floating bug reproduced during parallel builds, when (presumably) an initfs target rule was itself applied for creating its parent directory, inheriting the target-specific `$(src_file)`:
cp -r -T $(src_file) $@    # $@ is $(ROOTFS_DIR)/dst_file
Which depends on (order-only) `| $(ROOTFS_DIR)/`.
cp -r -T $(src_file) $@    # $@ is now $(ROOTFS_DIR)/.
Resulting in the following error:
cp: cannot overwrite directory .../rootfs//. with non-directory
An indirect reason of this behavior is a bogus double-slash ('//') as a separator that made Make choose the `$(ROOTFS_DIR)/%` rule instead of the proper `$(ROOTFS_DIR)/.` one. This is …
> mk: initfs: Remove explicit commands for creating parent directory

- mk/image2.mk
- mk/image_lib.mk
Fix a bug occurring on GNU Make >= 3.82 (reported by @Deryugin for gmake-4.0, reproduced on remake-4.1) due to the changed order of implicit rule search.
Also make a `/cygdrive/...` SHELL workaround conditional for Cygwin only. This one was breaking builds using Dash with the 'Bad substitution' error.
> Fix regression introduced in #856, fix Dash 'bad substitution' error

- platform/stm32f3_sensors/libactuators/motor.c
- platform/stm32f3_sensors/libactuators/motor.h
This reverts commit dc45665a59673c0b818698e0aba15cc8ba89b47f.
It breaks compiling and has only conflicts signs.
> Revert "fault-car: Add libactuators lib" contains only conflicts signs

- src/cmds/fs/Mkdir.my
- src/cmds/fs/mkdir.c
- src/cmds/fs/mount.c
- src/cmds/fs/umount.c
- src/compat/posix/fs/dvfs/fsop.c
- src/fs/driver/dfs/dfs.c
- src/fs/driver/dfs/dfs.h
- src/fs/driver/fat/fat.h
- src/fs/driver/fat/fat_common.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/dvfs/Mybuild
- src/fs/dvfs/compat.c
- src/fs/dvfs/dcache_no.c
- src/fs/dvfs/dcache_polynomial.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs.h
- src/fs/dvfs/dvfs_util.c
Umount was not very helpful, as it was a stub. Now it works fine with all bdev types, therefore ramdisk-related issue was closed.
Some VFS issues were fixed, e.g. double destroy of dentries, which led to inconsistency of dentries.
A number of fatfs issues were fixed. There were a bunch of typos and misusing sectors/clusters numbers. Now fatfs fully supports subdirectories, clears garbage on system volume data on disk format (previously FAT and root directory were not being erased).
> Implement umount for new VFS

- src/compat/posix/fs/dvfs/fsop.c
- src/drivers/block_dev/Mybuild
- src/drivers/block_dev/block_dev.c
- src/drivers/block_dev/block_dev.h
- src/drivers/block_dev/block_dev_common.c
- src/drivers/block_dev/block_dev_dvfs.c
- src/drivers/block_dev/block_dev_idesc_dvfs.c
- src/drivers/block_dev/flash/flash.c
- src/drivers/block_dev/ide/cdrom.c
- src/drivers/block_dev/ide/harddisk_dma.c
- src/drivers/block_dev/ide/harddisk_pio.c
- src/drivers/block_dev/ide/ide_drive.c
- src/drivers/block_dev/ramdisk/ramdisk.c
- src/drivers/block_dev/ramdisk/ramdisk_dvfs.c
- src/drivers/block_dev/scsi/scsi_disc.c
- src/drivers/block_dev/stm32_sd/stm32f4_sd.c
- src/drivers/char/char_dev_dvfs/char_dev.h
- src/drivers/char/char_dev_dvfs/char_dev_dvfs.c
- src/drivers/flash/flash_emu.c
- src/fs/bcache.c
- src/fs/driver/devfs/devfs_dvfs.c
- src/fs/driver/ext3/ext3.c
- src/fs/driver/ntfs/ntfs.c
- src/fs/driver/power_save/qnx6.h
- src/fs/dvfs/dvfs.c
- src/include/fs/bcache.h
- src/include/fs/buffer_head.h
- src/include/fs/journal.h
Enable 'dd' command in dvfs by adding idesc operations to block devices.
Clean block devices
> Block dev open in devfs

- src/drivers/block_dev/ide/ide_drive.c
'/dev/hda' hasn't been found before this fix
> Fix ide_drive after refactoring

- src/drivers/block_dev/ide/harddisk_pio.c
Properly calculate the size of an ide disk. This change fixes mke2fs util, as a goal.
> ide: Fix idedisk_init

- third-party/e2fsprogs/Makefile
There was an error on creating dir on sequential builds
> e2fs: Fix build

- src/util/log.h
Macros log_xxx had wrong condition 'if (!&mod_logger)'
and log messages didn't show at all
> util: Fix mod_logger macros

- src/cmds/md5sum.c
- src/compat/libc/stdio/fioctl.c
Now use proper address in RAM (fioctl was buggy) + print warning if fails.
Also fix issue #442
> md5sum fix

- src/fs/dvfs/dvfs.c
There was double freeing of the new_inode
> dvfs: Fix dvfs_create_new

- src/arch/arm/lib/debug/Mybuild
- src/arch/arm/lib/debug/stack_iter.c
- src/arch/arm/lib/debug/stack_iter.h
- templates/arm/qemu/build.conf
- templates/arm/qemu/mods.config
Implement stack unwind for ARM Procedure Call Standart frame format (-mapcs-frame option for gcc).
Now backtrace could be obtained correctly.
> ARM callstack

- src/arch/arm/include/asm/regs.h
- src/arch/x86/include/asm/regs.h
- src/kernel/irq_stack_protection.c
- src/kernel/sched/boot_thread.c
- src/kernel/thread/core.c
Fix irq_stack_protection() and enable it for ARM.
Routine thread_self() returns stackfull thread
> Fix irq_stack_protection()

- src/include/mem/misc/pool.h
- src/mem/misc/Mybuild
- src/mem/misc/pool_debug.c
- src/mem/misc/pool_debug.h
This version of pool is safe from double freeing (catches double freeing with asserts)
There is a bitmap of free blocks, so every time when somebody calls pool_free() it's checked whether the specified object was previously allocated.
> mem: Add debug version of pool

- mk/flags.mk
- mk/script/build/oldconf-gen.mk
- src/arch/x86/lib/debug/stack_iter.c
- src/mem/mmap/mmap_userspace.c
Make embox compatible with recent GCC versions
> gcc 6 compat

- .gitignore
It would probably be better to place these files in something like `build` or `run` directory, but it needs more investigating first.
> Ignore built img files in Git

- .travis.yml
This fixes PR builds missing the actual `make` step due to a bash syntax error in case when the `${COVERITY_SCAN_BRANCH}` expands to empty:
$ if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make && ./scripts/continuous/run.sh "$TEMPLATE"; fi
/home/travis/build.sh: line 45: [: !=: unary operator expected
The command "if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make && ./scripts/continuous/run.sh "$TEMPLATE"; fi" exited with 0.
The worst thing is that this error used to make PR builds effectively no-op, resulting in a green build without any check.
> travis: Fix unquoted ${COVERITY_SCAN_BRANCH} test

- src/util/array_spread/array_impl.h
> utils: Remove 'const' from ARRAY_SPREAD declaration

- templates/x86/test/fs/mods.config
- third-party/samba/Mybuild
mmap() failed to compile in this template, this issue was caused by rewriting mmap() in #952.
> Fix build for x86/test/fs

- src/init/diag_fd.c
nbyte was not initialized, so it led to some errors
> (init) diag_fd: Fix read/write ops

- mk/extbld/lib.mk
- third-party/bsp/st_f3/Makefile
- third-party/bsp/st_f4/Makefile
- third-party/phoneme/Makefile
There is an issue with deprecating web hosting support in Google Drive (https://gsuiteupdates.googleblog.com/2015/08/deprecating-web-hosting-support-in.html), which rejects download of files using direct links in usual google drive's style http://googledrive.com/host/<...>.
This PR fixes corrupted direct links to the correct ones.
> Fix google drive downloads

- mk/flags.mk
Disable -Wmisleading-indentation - "Warn when the indentation of the code does not reflect the block structure. Specifically, a warning is issued for if, else, while, and for clauses with a guarded statement that does not use braces, followed by an unguarded statement with the same indentation".
This option breaks some of third-party stuff (cJSON for instance), so we decided just to disable it for the whole project for a while.
> mk: Disable -Wmisleading-indentation gcc option

- mk/core/compiler.mk
- mk/extbld.mk
- mk/extbld/arch-embox-clang
- mk/extbld/arch-embox-gcc
- mk/extbld/lib.mk
- mk/flags.mk
- mk/main-stripping.sh
First of all it compiles and it doesn't break compilation with gcc.
Run COMPILER=clang make confload-arm/stm32f4cube all to get the image.
There are some difficulties about supporting two different compilers.
Maybe I did it not in optiomal way but it works. The main issue that
command line switcher are different for gcc and clang (the latter uses
-target switch to specify a triplet). Also we can't compiler with clang
and without gcc because clang is only a compiler and relies on cross
toolchain.
Also there some issues with clang codegeneration: generated object files
are bigger than with GCC. That's why some modules were commented out for
stm32f4cube.
> Starting clang support

- src/drivers/char/terminal/vt.h
- src/net/util/show_packet.h
- src/util/logging.c
This is re-based #1024 
@AntonKozlov commented log_level is not break any templates
> Fix some redundant checks for non-NULL values raised up by clang

- third-party/chibi-scheme/Makefile
- third-party/libcoap/lib/Makefile
- third-party/lua/lib/luasocket/Makefile
- third-party/mruby/Makefile
Add PKG_ARCHIVE_NAME for packages:
* chibi-scheme
* libcoap
* luasocket
* mruby
> third-party: Add PKG_ARCHIVE_NAME for some extern packages

- src/arch/arm/mmu/mmu_small_page.c
- src/compat/posix/proc/exec.c
- src/drivers/net/arasan/arasan.c
- templates/arm/imx6/mods.config
- templates/arm/iwave_imx6/mods.config
- templates/arm/vexpress-a9/mods.config
- Fix telnetd for cortex-a9 boards. execv was broken where setup task_name.
- Correct arm mmu-small pages cache flags
- Implement arasan net driver  (gemac)
> Arm telnetd

- src/arch/arm/lib/Mybuild
- src/cmds/net/ntpdate.c
- src/cmds/net/tftp.c
- src/cmds/play.c
- src/drivers/audio/aaci_pl041/aaci_pl041.c
- src/fs/driver/nfs/nfs.c
- src/mem/vmem/vmem_unmapper.c
- templates/arm/overo/mods.config
We had some problems with -O2 optimization as some variables could be used uninitialized in some cases. For some reason with -O0 these errors are not detected (even as warnings).
Now this problem is fixed for x86/qemu, arm/qemu, arm/overo.
Also fix minor dependency issues for arm/vfork.
> Optimized build

- src/drivers/interrupt/cortexm_nvic.c
- third-party/bsp/stmf4cube/arch.c
Fix stm32f4-cube -- clock was not initizalized. That was leading to some unpredicted behavior, for instance, network crash
> Fix stm32f4cube

- src/drivers/block_dev/Mybuild
- src/drivers/block_dev/ide/Mybuild
Ide drive registers itself during initialization via block_dev, and block_dev responsible to create entry in `/dev` corresponding to the drive.
However, `/dev` created by rootfs and if ide_drive initilized before rootfs, ide_drive entry is not created in dev.
The reason is in missing dependencies ide_drive -> block_dev and block_dev -> root_fs
Before the patch
```
$ make confload-x86/qemu && make && ./auto_qemu -hda some.img
embox> ls /dev
/dev/null
/dev/zero
/dev/ram0
/dev/ram1
/dev/ttyS0
```
After the patch
```
$ ./auto_qemu -hda some.img
embox> ls /dev
/dev/null
/dev/zero
/dev/hda
/dev/cd0
/dev/ram0
/dev/ram1
/dev/ttyS0
```
> Add missing dependencies to ide_drive

- src/drivers/serial/imx_uart/Mybuild
- src/drivers/serial/imx_uart/imx_uart.c
- templates/arm/imx6/mods.config
- templates/arm/iwave_imx6/mods.config
Configure pins on iwave rainbow g15s to use UARTs on 84-pin extension.
> Implement support for multiple UARTS on i.MX6

- src/arch/arm/include/asm/hal/mmu.h
- src/arch/arm/mmu/mmu_small_page.c
Use normal memory for code and data with write-back cache and device
memory for peripheral devices
> Fix ARM MMU flags

- src/arch/arm/armlib/exception_table.S
This is quick fix for arm data_abt_prepare:
1. data_abt_handler_addr holds arbitrary C function address, at least caller save register should be saved (r0-r3). 
But these are still not resolved: 
- abt_handler called still called in system ARM mode, 
- on IRQ stack
- without args (but set_fault_handler function of fault_handler_t type, which takes 2 arguments)
These all are wrong.
2. Exception return sequence was incorrect:
- should not kill `r0`.
- should return to `r14 - 8`, not r14 (ARM ARMv7 B1.8.3, Table B1-7)
- should atomically restore CPSR from SPSR during jump (interrupt mask either not reasserted or not restored). S flag in SUBS does this.
> Fix arm data_abt_handler

- src/drivers/interrupt/Mybuild
- src/drivers/interrupt/cortexm_irq_handle.S
- src/drivers/interrupt/cortexm_nvic.c
- src/tests/kernel/sched/Mybuild
- src/tests/kernel/sched/running_threads_test.c
There is a problem with interrupts handling on cortex-m. When we are inside an interrupt handler, another interrupts of the same priority (including the current one) are locked. The only way to enable it is to exit interrupt handle. One can check the issue using the test proposed in this PR and see that without this changes thread2 started only after thread1 finished.
This PR was tested on stm32f4-discovery with httpd and telnetd also
> Fix cortexm irq handling

- platform/stm32f4_multibots/cmds/Mybuild
- platform/stm32f4_multibots/cmds/gy_30.c
- platform/stm32f4_multibots/cmds/i2c_master.c
- platform/stm32f4_multibots/cmds/i2c_slave.c
- src/drivers/i2c/stm32f4/Mybuild
- src/drivers/i2c/stm32f4/i2c_hal_msp_f4.c
- src/drivers/i2c/stm32f4/stm32_i2c_conf_f4.h
- src/drivers/i2c/stm32f4/stm32f4_i2c.c
- src/drivers/i2c/stm32f4/stm32f4_i2c.h
Add 2 examples of stm32f4 i2c, based on the initial i2c support derived from ST Cube:
* master/slave (two boards)
* GY-30 light sensor
> Stm32f4 i2c

- src/drivers/serial/imx_uart/imx_uart.c
Fix exception for i.MX devices which use IOMUXC registers to configure UART
> i.MX6 UART driver fix

- src/arch/arm/imx/Mybuild
- src/arch/arm/imx/cpuinfo.c
- src/arch/arm/imx/cpuinfo.h
- templates/arm/imx6/mods.config
- templates/arm/iwave_imx6/mods.config
Now on system start there's info about current CPU model and revision.
> arm/imx: Initial implementation for cpuinfo module

- src/drivers/gpio/imx/Mybuild
- src/drivers/gpio/imx/imx.c
- src/drivers/gpio/imx/imx.h
- src/drivers/spi/imx6_ecspi/Mybuild
- src/drivers/spi/imx6_ecspi/imx6_ecspi.c
- src/drivers/spi/imx6_ecspi/imx6_ecspi.h
- src/tests/spi/Mybuild
- src/tests/spi/imx6_spi.c
- templates/arm/iwave_imx6/mods.config
Initial implementation for SPI driver. To make it work properly following things were done as well:
- Initial support for i.MX6 GPIO (it is required for some SPI devices to keep CS signal active)
- Simple test for SST25VF016B flash via SPI
- iwave_imx6 template is updated
> Initial support fot i.MX6 ECSPI controller

- src/mem/phymem.c
- src/mem/vmem/vmem_device_memory.c
- templates/x86/qemu/mods.config
After many unsucessfull atempts to embed anonymous maps along with normal maps, the most straightforward way appear to be just explicitly handle them in mmaps.
* anon mmaps and device_mem maps are only ways to create new map for now. 
* Anon mmap is handled almost outside of vmem subsystem, it's just interface for phymem_alloc
* anon mmaps can't be added to vmem maps for various reasons:
* phymem is mmaped, so anon mmap should get VMA outside of phymem to munmap later
* vmem (marea explicitly) can't handle different VMA and PA
* vmem_create_space while allocating pages to be used for new mapping unable to track not-linear sequence of pages in marea, unusable
* and finally, anyway, the only place `is_allocated` flag of marea handled is munmap itself. 
In general, I've failed to do it in …
> Fix anon munmap

- src/drivers/block_dev/sdhc/Mybuild
- src/drivers/block_dev/sdhc/imx6_sdhc.c
This driver is very simmilliar with embox.driver.block.sdhc.sdhc, but this one considers details of imx6 implementation. In future common parts should be moved to separate SDIO module.
> imx6_sdhc: Add initial implementation

- mk/flags.mk
Gcc should be called with --version flag to get machine-readable version
specifier.
Fixes #1093 
`gcc -v` gives hard-to-parse version format
```
$ GCC_VER="-v"; for loc in ru_RU fi_FI en_US; do echo == $loc; LANG=${loc}.UTF-8 gcc $GCC_VER 2>&1 | grep -e '^gcc' ; done
== ru_RU
gcc версия 7.1.1 20170528 (GCC) 
== fi_FI
gcc-versio 7.1.1 20170528 (GCC) 
== en_US
gcc version 7.1.1 20170528 (GCC) 
```
Using `gcc --version` gives better results
```
$ GCC_VER="--version"; for loc in ru_RU fi_FI en_US; do echo == $loc; LANG=${loc}.UTF-8 gcc $GCC_VER 2>&1 | grep -e '^gcc' ; done
== ru_RU
gcc (GCC) 7.1.1 20170528
== fi_FI
gcc (GCC) 7.1.1 20170528
== en_US
gcc (GCC) 7.1.1 20170528
```
> (mk) Fix gcc version determination

- src/drivers/tty/termios_ops.c
- src/drivers/tty/termios_ops.h
- src/drivers/tty/tty.c
First commit contain just whitespace fixes, second one really fixes build.
I think they are easier to review one by one
> Fix xen build

- .travis.yml
- scripts/codestyle/install_uncrustify.sh
Following https://github.com/embox/embox/pull/1102#issuecomment-318363959
Newer version of uncrustify doesn't produce such warning.
With this we could always get most fresh version. However, current release is hardcoded to avoid meeting with regressions in uncrustify
> (travis) Build fresh uncrustify

- .gitignore
- Vagrantfile
- src/arch/xen/include/traps.h
- src/arch/xen/kernel_init.c
- src/arch/xen/traps.c
- src/drivers/interrupt/Mybuild
- src/drivers/interrupt/xen.c
- src/drivers/interrupt/xen.h
- templates/xen/debug/mods.config
Exception generated and first stubs called. The output is 
```
Embox kernel start
runlevel: init level is 0
runlevel: init level is 1
unit: initializing embox.driver.interrupt.xen: done
test: running embox.test.kernel.irq_test xen force interrupt 10
DIVIDE ERROR called
ERROR_11
ERROR_11
ERROR_12
ERROR_12
ERROR_12
ERROR_12
ERROR_12
ERROR_12
ERROR_12
ERROR_12
ERROR_12
ERROR_12
...
```
To avoid exception disabling `irq_test` in config is sufficient. Probably behavior with exception is good as it shows point of further improvement
> Xen exception

- src/cmds/sys/Uname.my
- src/cmds/sys/uname.c
- src/net/lib/pop3.c
I'm a member of the Pinguem.ru competition on finding errors in open source projects. Warnings, found using PVS-Studio:
embox/src/net/lib/pop3.c	227	warn	V547 Expression 'p3s != NULL' is always true.
embox/src/cmds/sys/uname.c	78	warn	V560 A part of conditional expression is always false: processor.
embox/src/cmds/sys/uname.c	79	warn	V547 Expression 'processor' is always false.
> Fixed condtitions

- platform/mesa/cmds/fb_direct_access/fb_direct_access.c
- src/drivers/clk/ccm_imx6/Mybuild
- src/drivers/clk/ccm_imx6/ccm_imx6.c
- src/drivers/gpu/drm/dw_hdmi/Mybuild
- src/drivers/gpu/drm/dw_hdmi/dw_hdmi.c
- src/drivers/gpu/drm/dw_hdmi/dw_hdmi.h
- src/drivers/gpu/ipu_v3/Mybuild
- src/drivers/gpu/ipu_v3/ipu_disp.c
- src/drivers/gpu/ipu_v3/ipu_param_mem.h
- src/drivers/gpu/ipu_v3/ipu_priv.h
- src/drivers/gpu/ipu_v3/ipu_regs.h
- src/drivers/gpu/ipu_v3/ipuv3.c
- src/drivers/gpu/ipu_v3/ipuv3_fb.c
- src/drivers/gpu/ipu_v3/uboot_ipu_compat.h
- src/drivers/gpu/ldb/Mybuild
- src/drivers/gpu/ldb/ldb.c
- templates/arm/iwave_imx6/mods.config
Add support for graphic for i.MX6 board, this includes:
* LVDS driver for video output
* IPU driver for image processing
* CCM driver to configure clock
However, HDMI driver was not finished.
> i.MX6 graphic support

- scripts/docker/docker_rc.sh
Docker exec bins specific keys to detach from running process (Ctrl-p
Ctrl-q by default). Ctrl-p is emacs up, also is up in readline,
also shell previous command. To make use of container's interactive
shell more plesant, this commit adds abillity to pass extra args to
docker exec, thus remap detach keys to something else, like:
$ . ./scripts/docker/docker_rc.sh
$ EMDOCKER_EXEC_EXTRA_ARGS="--detach-keys ctrl-_"
> Add extra args option to docker run

- platform/stm32f4_multibots/cmds/Mybuild
- platform/stm32f7/cmds/Mybuild
- scripts/stm32/Mybuild_template
- scripts/stm32/embox_main_template.c
- scripts/stm32/import_stm32_cube_example.py
- src/drivers/clock/cortexm_systick.c
- src/drivers/video/stm32f7_lcd/Mybuild
- third-party/bsp/stmf4cube/Mybuild
- third-party/bsp/stmf7cube/Mybuild
The goal of this contribution is to simplify an importing STM32Cube examples  into Embox. scripts/stm32/import_stm32_cube_example.py imports Cube example and creates all required files in Embox to make it usual Embox module.
Example:
./scripts/stm32/import_stm32_cube_example.py f7 build/extbld/third_party/bsp/stmf7cube/core/STM32Cube_FW_F7_V1.5.0/Projects/STM32746G-Discovery/Examples/BSP/
Now you can see:
$ ls platform/stm32f7/cmds/BSP/
Inc  Mybuild  readme.txt  Src
> Stm32cube examples import

- mk/tsortdiag.awk
- mk/tsortdiag.mk
- mk/ugly.mk
Messages contain info about cycles found, but in mybuild internal
format. The patch turns this output
```
tsort: -: input contains a loop:
tsort: .bld502x
tsort: .bld429x
```
to this
```
Error: modules dependency cycle:
embox.compat.posix.proc.exit
embox.compat.posix.proc.vfork_exchanged
```
Every cycle is actually is a error in mybuild, but we aren't consider
them so for now. The patch also adds fatal_mode, which, when enabled,
produces next and halts build
```
Error: modules dependency cycle:
...
Error: stop after finding cycle(s)
mk/script/build/build-gen.mk:338: *** Mybuild stop.  Stop.
```
The mode should be considered as transitional, and should be
enabled from some point in time till forever.
> mk: Improve topsort diagnostic messages

- .travis.yml
- scripts/continuous/run.sh
- src/mem/mmap/Mybuild
- templates/x86/user_apps/mods.config
- templates/x86/user_apps/start_script.inc
For x86/user_apps:
* add `vfork` module in template
* restore dependency, omitting resulted in crash during boot, some allocator was not properply initialized prior calling allocation function
* add template to travis
> Fix x86/user_apps template

- src/arch/arm/armlib/context/Mybuild
- src/arch/arm/armlib/context/context.c
- src/arch/arm/armlib/context/context.h
- src/arch/arm/armlib/context/context_switch.S
- src/arch/arm/armlib/entry.S
- src/arch/arm/armlib/exception_handler.c
- src/arch/arm/armlib/exception_table.S
- src/arch/arm/fpu/Mybuild
- src/arch/arm/fpu/stub.h
- src/arch/arm/fpu/vfp.c
- src/arch/arm/fpu/vfp.h
- templates/arm/iwave_imx6/build.conf
- templates/arm/iwave_imx6/mods.config
- templates/arm/vexpress-a9/build.conf
- templates/arm/vexpress-a9/mods.config
Add support for VFP/NEON instructions. Currently it works only with NEON, but VFP is subset of NEON, so it's possible to cut it if necessary in future.
> ARM VFP/NEON support

- src/arch/arm/head.S
It turned out that memset() is 10 times slower than simple loop in assembly. This change allows to speed up the way more faster.
> arm: Zero bss in assembly, without memset()

- src/cmds/help.c
Now `help` works well with long-name commands
> help: Fix ugly output

- src/arch/arm/armmlib/exception_table.S
- src/arch/arm/embox.lds.S
- src/include/asm-generic/static_irq.h
Extend the common part of trap table for all cortex-m for both static and dynamic irqs. It is required bacause we want to have informative exceptions handlers for any Embox configuration. So we just extend the trap table.
> Fix static irq

- platform/stellaris/templates/lm3s811evb/build.conf
- platform/stellaris/templates/lm3s811evb/lds.conf
- platform/stellaris/templates/lm3s811evb/mods.config
- scripts/qemu/auto_qemu
- src/drivers/common/Mybuild
- src/drivers/common/memory_impl_stub.h
- src/drivers/serial/Mybuild
- src/drivers/serial/pl011/pl011.c
- src/drivers/tty/serial/Mybuild
- src/drivers/tty/serial/ttys_stub.c
- src/framework/mod/Mybuild
- src/framework/mod/embuild_light_impl.h
Add lm3s811evb (Cortex-M3), which is emulated by QEMU.
`make confload-platform/stellaris/lm3s811evb `
```
$ ./scripts/qemu/auto_qemu
qemu-system-arm -M lm3s811evb -kernel ./build/base/bin/embox -m 128 -nographic
Embox kernel start
runlevel: init level is 0
unit: initializing embox.driver.clock.cortexm_systick: done
unit: initializing embox.kernel.time.kernel_time: done
unit: initializing embox.kernel.time.jiffies: done
unit: initializing embox.kernel.sched.sched: done
unit: initializing embox.kernel.time.timer_handler: done
runlevel: init level is 1
unit: initializing embox.kernel.task.task_resource: done
unit: initializing embox.kernel.task.kernel_task: done
unit: initializing embox.cmd.shell: done
unit: initializing embox.driver.serial.pl011: done
runlevel: init level is 2
unit: …
```
> QEMU Stellaris lm3s811

- src/drivers/net/fec/fec.c
- src/drivers/net/phy/phy.c
- src/include/net/mii.h
Issues were related to bit-field interleaving
Also fixed FEC driver options to be able to select best speed
> Fix PHY initialization for 1Gbit links

- platform/pjsip/templates/stm32f4cube/build.conf
- platform/pjsip/templates/stm32f4cube/lds.conf
- platform/pjsip/templates/stm32f4cube/mods.config
- platform/pjsip/templates/stm32f4cube/start_script.inc
- platform/pjsip/templates/stm32f4discovery/mods.config
- src/arch/arm/armlib/boot/reset_handler.S
- src/arch/arm/armmlib/Mybuild
- src/arch/arm/armmlib/exception_handlers.c
- src/arch/arm/armmlib/ipl_impl_prio.h
- src/arch/arm/include/asm/regs.h
- src/drivers/audio/portaudio/Mybuild
- src/drivers/audio/portaudio/stm32f4_pa_cube.c
- src/drivers/interrupt/cortexm_nvic.c
- src/drivers/net/stm32cube/Mybuild
- src/drivers/net/stm32cube/stm32cube_eth.c
- src/kernel/Irq.my
- src/kernel/irq_static.h
- third-party/bsp/stmf4cube/Makefile
- third-party/bsp/stmf4cube/Mybuild
- third-party/bsp/stmf4cube/arch.h
- third-party/bsp/stmf4cube/patch.txt
- third-party/bsp/stmf4cube/pdm_filter_stub.c
- third-party/bsp/stmf4cube/stm32f4xx_hal_conf.h
- third-party/bsp/stmf7cube/Mybuild
- third-party/bsp/stmf7cube/stm32f7xx_hal_conf.h
Porting pjsip on stm32f4-discovery to STM32F4 Cube. The porting process incudes:
* Improvement of ethernet driver to xmit skbuff immediately without extra buffers allocation
* Add new ipl_impl_prio.h, which implements ipl_save and ipl_restore basing on the following logic. Let's change the prio of faults (mem fault, bus fault and usage fault) to 0. And all other interrupts and exceptions to 1. So we can allow generating of fault even inside ipl_lock/unlock without hard fault excalation.
* Add new stm32f4_pa_cube.c, which is a port of stm32f4_pa.c portaudio layer to Cube.
> Pjsip stm32f4 cube

- src/arch/arm/subarch/armv7a/cpu_reset.S
Repair build after 46cf8600131956ecbb3fca62202168117fde39ca
> arm: Fix build for i.MX

- src/arch/arm/armlib/context/context.c
It's neccessary to set all values to zero. For example, stack unwinding
fails if initial frame pointer is not zero.
> arm: Fix context init

- platform/stm32f4_iocontrol/http_admin/partials/leds.html
quick-fixed html misspelling indicated by eclipse
> fixed closing div html tag

- src/arch/arm/lib/debug/stack_iter.c
- src/arch/arm/lib/debug/stack_iter.h
- src/lib/debug/whereami.c
- templates/sparc/qemu/mods.config
* Make whereami(), traceback_dump() and traceback_dump_thread()  work in a common way for x86 and arm. Stack trace on sparc works too, but with bugs (in the master branch too). Probably, we can fix it later.
* Fix arm stack trace.
> Fix whereami

- src/compat/linux/include/asm-generic/dma-mapping.h
- src/compat/linux/include/err.h
- src/compat/linux/include/linux/idr.h
- src/compat/linux/include/linux/pagemap.h
- src/compat/linux/include/linux/types.h
- src/compat/linux/include/linux/wait.h
Extend Linux compatibility. This is mostly needed by etnaviv DRM driver (currently not merged to master).
Implemented functions are mostly stubs.
> Linux compat

- src/compat/posix/fs/dvfs/stat.c
Currently `stat` is not implemented for directories for some file systems, so this stubs helps to avoid some errors.
> dvfs/stat: Stub for directories

- src/tests/mem/heap.c
- src/tests/stdio/printf_test.c
Fix build for x86 templates for GCC 8.2.0
Fix #1205
> Add GCC8 compatibility

- third-party/qt/Mybuild
Fix #601 by changing build order. Previously, Qt was builded after the kernel (so fonts were not included in rootfs when built just after `make confload-...`), now it works properly.
> qt: Fix rootfs/fonts initialization

- src/arch/arm/mmu/mmu_small_page.c
This function is supposed to return physical address to which virtual
page points.
Fixing this function will fix some memory leaks
> arm: Fix mmu_pte_value()

- src/mem/pagealloc/bitmask.c
The problem was that in the `src/mem/mmap/mmap_mmu.c:132` called `mmap_clear(mmap);` and `vmem_free_context(mmap->ctx);`. 
This functions leads to the call of `src/mem/vmem/vmem_alloc.c:vmem_free_pgd_table` 2 times, which causes to free 2 pages instead of 1.
Fix was to check if current page already freed or not.
> Fix of pgd_allocator frees more than available space.

- scripts/app_diff.sh
Little fix, so it would be able to work .bz2 archives, not just .gz
> fix app_diff script

- platform/efm32zg_sk3200/templates/debug/mods.config
- platform/stellaris/templates/lm3s811evb/mods.config
- src/drivers/audio/stm32/stm32_audio_f7.c
- src/drivers/interrupt/cortexm_irq_handle.S
- src/drivers/interrupt/cortexm_nvic.c
- src/kernel/Irq.my
- src/kernel/irq_static.h
- src/kernel/irq_static_light.h
- templates/arm/stm32_vl/mods.config
- templates/arm/stm32_vl_light/mods.config
Fix `irq_static` to make test `embox.test.kernel.thread.thread_systimer_irq_test` work for both static and non-static vector table. Nevertheless, the old version of irq_static remained, since it is useful when we do not use threads, but only light threads. Now, this module is renamed to `irq_static_light`.
> Stm32 fix static irq

- scripts/continuous/net/forwarding/test_ping_forwarding.sh
- scripts/continuous/net/run.sh
- scripts/continuous/run.sh
- scripts/expect/framework/run_all.exp
- scripts/expect/framework/test_cmd.exp
- scripts/expect/framework/test_core.exp
- scripts/expect/framework/test_exec.exp
- scripts/expect/ntpdate.exp
- scripts/expect/ping.exp
- scripts/expect/rlogin.exp
- scripts/expect/telnet.exp
- scripts/expect/vfat.exp
- scripts/expect/x86_net_tests.config
The main objective was to get `x86/test/net` back to its previous old state (and possibly externd).
What's done:
* Autotest framework is significantly rewritten and improved. Several new tests on telnet and ping are added
* Enable old ping forwarding tests. Small improvements in net/run.sh
> Fix CI x86/test/net

- templates/x86/test/net/start_script.inc
Little change to be able to connect via ssh with only root password (though connection with authorized_keys still possible).
> x86/test/net: (template) change dropbear startup

- scripts/expect/framework/test_core.exp
- scripts/expect/ntpdate.exp
- scripts/expect/ssh.exp
- scripts/expect/telnet.exp
- scripts/expect/x86_net_tests.config
Several modifications to `x86/test/net`
* Disable telnet multiple times `help` execution
* Add ability to mark the specified test case as known to be failed instead of just using `if 0`. I think it probably can be convenient to see which test cases are required to fix
* Add ssh (dropbear) test
> Fix x86/test/net

- src/drivers/net/mipsnet/mipsnet.c
Enable interrupts only on net_driver->start instead of module init.
> Fix mipsnet network driver

- scripts/continuous/net/forwarding/test_ping_forwarding.sh
- scripts/continuous/net/run.sh
- scripts/qemu/auto_qemu
- src/net/socket/sock_hash.c
In newer QEMU versions (>= 2.9.0, I guess) there is no more `vlan=0` option for `-net nic`. So migrating to new options.
[Qemu](https://wiki.qemu.org/Documentation/Networking#The_legacy_-net_option) proposes to use `-netdev tap` instead of  `-net tap`, and `-device` instead of `-net nic`. But the problem here that we are using embedded (on-board) network cards while `-device` works only with user creatable. A newer version of QEMU [proposes](https://qemu.weilnetz.de/doc/qemu-doc.html#Network-options) to use `-nic tap,model=virtio...` to get on-board network card, but QEMU 2.5.0 (old, but not too old version) doesn't have this option. In this PR I propose to use `-netdev` together with legacy `-net nic` for backward compatibilities with older QEMU versions. In the future, it could be …
> Fixes due to new qemu 3.1.0

- scripts/expect/telnet.exp
- src/cmds/net/telnetd/Telnetd.my
- src/cmds/net/telnetd/telnetd.c
- src/compat/posix/proc/exec.c
- templates/x86/qemu/mods.config
- templates/x86/test/net/mods.config
Fix problem with zombie processes when "exit" sent from a client.
Rewrite telnetd. Use vfork() instead pthread_create() and handle SIGCHLD signal
> Telnet client exit

- .travis.yml
- scripts/continuous/build.sh
Fix the problem with `travis_wait`: it used status of the last executed command, that is of `tail`, not make.
> travis: Get correct build status after travis_wait

- src/cmds/Service.my
- src/cmds/service.c
- src/compat/posix/include/signal.h
- src/drivers/i2c/adapters/stm32/Mybuild
- src/kernel/task/resource/Mybuild
- templates/arm/stm32f4cube/mods.config
Telnetd and httpd were crashed with asserts. The problem was the tasks allocates resource about 2Kb , because of the signal table size about 1Kb. I add an option to set signal table size.
So now you can run "service telnetd" and "service httpd" well again.
Also additional small fixes:
* Services count as options
* I2c missing dependance
> stm32f4-discovery telnet fix

- platform/etnaviv/cmds/Mybuild
- platform/etnaviv/cmds/etnaviv_compiler_cmdline.c
- platform/etnaviv/cmds/quad_tex.c
- platform/etnaviv/cmds/tri.c
- platform/etnaviv/templates/imx6/mods.config
- platform/etnaviv/templates/imx6/start_script.inc
- src/compat/libc/assert/assert_impl.h
- src/compat/linux/include/linux/sizes.h
- src/compat/linux/include/linux/types.h
- src/compat/posix/include/sys/select.h
- src/drivers/char/char_dev_dvfs/char_dev.h
- src/drivers/gpu/drm/etnaviv/etnaviv_buffer.c
- src/drivers/gpu/drm/etnaviv/etnaviv_cmd_parser.c
- src/drivers/gpu/drm/etnaviv/etnaviv_cmdbuf.h
- src/drivers/gpu/drm/etnaviv/etnaviv_compat.h
- src/drivers/gpu/drm/etnaviv/etnaviv_dev.c
- src/drivers/gpu/drm/etnaviv/etnaviv_drv.h
- src/drivers/gpu/drm/etnaviv/etnaviv_gem.c
- src/drivers/gpu/drm/etnaviv/etnaviv_gem.h
- src/drivers/gpu/drm/etnaviv/etnaviv_gpu.c
- src/drivers/gpu/drm/etnaviv/etnaviv_gpu.h
- src/drivers/gpu/drm/etnaviv/etnaviv_mmu.c
- src/drivers/gpu/drm/etnaviv/etnaviv_mmu.h
- third-party/freedesktop/mesa/libdrm/etnaviv/Makefile
- third-party/freedesktop/mesa/libdrm/etnaviv/patch.txt
- third-party/freedesktop/mesa/mesa/mesa_etnaviv/Makefile
- third-party/freedesktop/mesa/mesa/mesa_etnaviv/Mybuild
- third-party/freedesktop/mesa/mesa/mesa_etnaviv/patch.txt
This branch contains a bunch of etnaviv-related fixes/improvements:
* Add commands: `quad_tex` for simple texture test, `etnaviv_compiler` for compiling TGSI shaders to low-level instructions.
* Add fix for etnaviv driver so it's now can be used with new chardev interface (previously, it wasn't present in /dev/)
* Clean etnaviv driver source code
* Fix `assert()` for bit fields
* Update mesa/libdrm patches
* Minor `compat/linux` improvements
> Work on etnaviv driver

- src/arch/e2k/include/asm/setjmp.h
- src/arch/e2k/include/e2k_api.h
- src/arch/e2k/ipl_impl.h
- src/arch/e2k/libarch/e2k_setjmp.S
- templates/e2k/monocube/mods.config
Implement setjmp/longjmp for e2k. Now unit tests run well, also setjmp test passed.
> e2k setjmp

- src/arch/e2k/Mybuild
- src/arch/e2k/context.c
- src/arch/e2k/context.h
- src/arch/e2k/context_switch.S
- src/arch/e2k/entry.c
- src/arch/e2k/include/asm/linkage.h
- src/arch/e2k/include/e2k_api.h
- src/arch/e2k/ipl_impl.c
- src/arch/e2k/ipl_impl.h
- src/arch/e2k/libarch/e2k_setjmp.S
- src/arch/e2k/libarch/e2k_syscall.S
- src/include/hal/context.h
- src/kernel/thread/core.c
- src/tests/hal/context/Mybuild
- src/tests/hal/context/context_switch_test.c
- templates/e2k/monocube/mods.config
Implement context_switch for e2k (elbrus).
The following tests on context_switch and threads passed (included in e2k/template):
```
@Runlevel(1) include embox.test.hal.context_switch_test(stack_sz = 0x4000)
@Runlevel(1) include embox.test.kernel.sched.running_threads_test
@Runlevel(1) include embox.test.kernel.thread.thread_priority_test(threads_quantity=10)
@Runlevel(1) include embox.test.kernel.thread.thread_systimer_irq_test
@Runlevel(1) include embox.test.kernel.thread.thread_test
```
> e2k context switch

- scripts/continuous/fs/run.sh
Something going wrong with our expect fs tests, random errors at the random tests and random places (probably due to embox telnet/shell/very fast tests execution or something else). So temporarily disable expect fs tests and starting figure out what's going on.
By the way, net tests are pretty OK. Also, these errors with fs depend on -no-kvm flag I guess.
> autotest: expect: Disable fs tests temporarily

- platform/etnaviv/cmds/Mybuild
- platform/etnaviv/cmds/quad_tex_animated/Mybuild
- platform/mesa/cmds/osdemo_fb/Mybuild
- src/arch/arm/armlib/exceptions/Mybuild
- src/arch/arm/armlib/exceptions/arm_undefined_exception_handler.c
- third-party/freedesktop/mesa/mesa/mesa_etnaviv/Mybuild
Use `@App` signature to reset MESA .bss and .data sections.
> Fix etna-related examples

- scripts/continuous/fs/run.sh
- scripts/expect/framework/test_exec.exp
- scripts/expect/fs_shell_commands_test.exp
- scripts/expect/fs_unit_tests.exp
- src/cmds/net/telnetd/telnetd.c
- src/drivers/tty/tty.c
- templates/x86/test/fs/mods.config
Previously, we disabled fs interactive tests, enable them back.
Several fixes that helped to enable tests back:
* Fix telnetd options handling. There can be intermixed cleint data and telnet options, so do smarter hadnling instead of dropping such intermixed packets.
* Fix tty raise condition
* Use telnetd_use_pthread=0 for x86/test/fs
> Fix fs autotests

- src/cmds/testing/memtest/Mybuild
- src/cmds/testing/memtest/memtest.c
- src/mem/heap/Mybuild
- src/mem/heap/heap_simple.c
This feature fixes problems with heap_simple on ARM, where memory access should be 4-byte aligned.
Also extend `memtest` command for heap stress test.
> heap_simple: Rework

- src/drivers/tty/serial/ttys_dvfs.c
- src/drivers/tty/serial/ttys_dvfs.h
arm/stm32f7cube
```
ASSERTION FAILED on CPU 0
at src/fs/driver/devfs/devfs_dvfs.c:225
in function devfs_open_idesc
dev->dev_open
```
> Fix ttys_dvfs dev_open assignment

- platform/etnaviv/cmds/quad_tex_animated/quad_tex_animated.c
- src/drivers/gpu/ipu_v3/ipu_param_mem.h
- src/drivers/gpu/ipu_v3/ipuv3_fb.c
- src/drivers/video/fb.h
- src/lib/fps/fps.c
- src/lib/fps/fps.h
Add handler for changing current buffer in fb_ops. It helps to increase performance by using additional buffers and reducing copying operation.
> FB back buffer

- src/compat/libc/math/Mybuild
- templates/arm/qemu/mods.config
- templates/mips/qemu/mods.config
- templates/mips64/qemu/mods.config
- templates/ppc/qemu/mods.config
- templates/x86/qemu/mods.config
* Switch default implementation of libm to math_builtins
* Remove third-party modules from <arch>/qemu templates
* Switch libm to 'math_builtins'
* Remove dash from x86/qemu
> Clean arch/qemu templates

- platform/etnaviv/cmds/quad_tex_animated/quad_tex_animated.c
- src/drivers/gpu/drm/etnaviv/Mybuild
- src/drivers/gpu/drm/etnaviv/etnaviv_dev.c
- src/drivers/power/imx/imx.c
- src/lib/fps/fps.c
- src/lib/fps/fps.h
- third-party/freedesktop/mesa/mesa/mesa_etnaviv/Mybuild
- third-party/freedesktop/mesa/mesa/mesa_sw/Mybuild
* Add functions to setup first/back frame base manually
* Use this feature in gallium examples to avoid use `memcpy()` and achieve high fps rate
> FPS: Work on double buffering

- src/compat/posix/include/grp.h
- src/compat/posix/pwd_grp/pwd_grp.c
- third-party/samba/samba_embox_compat.h
Also:
* Fix typos with incorrect buffer size passed to reentrant functions in getpwuid and getmaxuid
* getgrgid now returns pointer to correct internal data structure
* All getgrXXX functions return (or set errno to) ENOENT if no entry is found and corresponding errno value on other errors
> posix: Add missing getgrXXX functions

- platform/mesa/templates/integratorcp/mods.config
- platform/nuklear/templates/arm_qemu/mods.config
- src/arch/arm/imx/cpuinfo.c
- src/compat/posix/sys/mman/Mybuild
- src/compat/posix/sys/mman/mmap_stub.c
- src/drivers/char/char_dev_stub.h
- src/drivers/interrupt/cortex_a9_gic/cortex_a9_gic.c
- src/drivers/video/Mybuild
- src/drivers/video/fb_devfs/fb_devfs.c
- src/mem/vmem/Mybuild
- src/mem/vmem/vmem_device_memory.c
- src/mem/vmem/vmem_nommu.h
- third-party/qt/Mybuild
uint32_t was misused in printf. It's interpreted as long unsigned int,
so %d is unusable here
> arm: Fix warnings

- src/drivers/interrupt/integrator_pic/Mybuild
- src/drivers/interrupt/integrator_pic/integrator_pic.c
- src/drivers/net/lan91c111/Mybuild
- src/drivers/net/lan91c111/lan91c111.c
Use static `periph_memory_desc` instead of runtime `mmap_device_memory` to map device registers.
> IntegratorCP interrupt/net drivers refactor

- mk/extbld/arch-embox-gcc
- mk/extbld/toolchain.mk
- src/compat/libc/include/stdlib.h
- src/compat/libc/stdlib/Mybuild
- src/compat/libc/stdlib/mkstemp.c
- third-party/STLport/Makefile
- third-party/dropbear/Makefile
- third-party/e2fsprogs/Makefile
- third-party/lib/boost/Makefile
- third-party/qt/Makefile
- third-party/tcl/tclsh/Makefile
- third-party/tcl/tcludp/Makefile
Now arch-gcc contains all CPPFLAGS derived from module's BuildDependcies.
> Extbld minor improvements

- src/drivers/power/imx/imx.c
This commit fixes stall on etnaviv start when compiled with `-O2`
> power/imx: Replace busy wait with ksleep()

- src/drivers/cache/pl310/pl310.c
Replace annoying `while(t--);` with `ksleep(50)`. Without MMU turned on it takes too much time.
> pl310: Clean code

- platform/etnaviv/cmds/quad_tex/quad_tex.c
- src/drivers/gpu/drm/etnaviv/etnaviv_buffer.c
- src/drivers/gpu/drm/etnaviv/etnaviv_cmd_parser.c
- src/drivers/gpu/drm/etnaviv/etnaviv_cmdbuf.c
- src/drivers/gpu/drm/etnaviv/etnaviv_dev.c
- src/drivers/gpu/drm/etnaviv/etnaviv_gem_submit.c
- src/drivers/gpu/drm/etnaviv/etnaviv_gpu.c
- src/drivers/gpu/drm/etnaviv/etnaviv_gpu.h
Mark command buffer memory as non-cacheable, so some cases of blank screen are fixed
> Fix etnaviv

- src/compat/libc/include/inttypes.h
- src/compat/libc/include/stdint.h
A lot of software acts like `int32_t` is the same as `int` and it works
just fine for x86 platform, but for ARM it's not the case: it's `long`
We can either patch every 3rd-party library we use or just redefine
`uint32_t`/`int32_t` for 32-bit ARM systems. Second options seems to be
better solution
> stdint.h: Change 32-bit defines for compatibility

- mk/image.lds.S
- src/compat/cxx/core/cxx_invoke_constructors.c
- src/tests/c++/Mybuild
- src/tests/c++/exceptions.cpp
Previously .eh_frame was only included in lds script, but not used.
> Fix x86 exceptions

- src/drivers/flash/qspi/Mybuild
- src/drivers/flash/qspi/stm32f7_qspi.c
- templates/arm/stm32f7cube/mods.config
Initialize QSPI memory to access via system bus with stm32f7cube functions
> drivers/qspi/stm32f7_qspi: Initial implementation

- src/drivers/interrupt/cortexm/cortexm_nvic.c
- third-party/bsp/stmf7cube/arch.c
Problems could occur if kernel was not started by regular reboot, but
just with a jump to start symbol
> cortexm_nvic: Fix initialization

- mk/extbld/lib.mk
- third-party/bsp/st_discovery_vl/Makefile
- third-party/bsp/st_f3/Makefile
- third-party/bsp/st_f4/Makefile
- third-party/bsp/stmf3cube/Makefile
- third-party/bsp/stmf4cube/Makefile
- third-party/bsp/stmf7cube/Makefile
- third-party/chibi-scheme/Makefile
- third-party/dropbear/Makefile
- third-party/freedesktop/mesa/glu/libglu_imx6/Makefile
- third-party/freedesktop/mesa/glu/libglu_osmesa/Makefile
- third-party/freedesktop/mesa/libdrm/etnaviv/Makefile
- third-party/freedesktop/mesa/libdrm/sw/Makefile
- third-party/freedesktop/mesa/mesa/mesa_etnaviv/Makefile
- third-party/freedesktop/mesa/mesa/mesa_sw/Makefile
- third-party/freedesktop/mesa/mesa_demos/Makefile
- third-party/lib/coap/Makefile
- third-party/lib/nuklear/Makefile
- third-party/lib/openlibm/Makefile
- third-party/lib/stb/Makefile
- third-party/lua/lib/luasocket/Makefile
- third-party/mruby/Makefile
- third-party/packetdrill/Makefile
- third-party/phoneme/Makefile
* Remove multiple PKG_SOURCES/PKG_MD5. Now PKG_SOURCES is just a list of mirrors for a single package
* Get rid of PKG_ARCHIVE_NAME. Now each downloaded package will be saved to download/ folder with name combined of $(PKG_NAME)-$(PKG_VER).extension. Extension will be derived from url.
* When package downloading is failed for some reason remove partially downloaded package.
> Third party mirrors

- src/cmds/bootloader/Qspi_loader.my
- src/cmds/bootloader/qspi_loader.c
- src/cmds/net/Tftp.my
- src/cmds/net/tftp.c
- src/lib/tftp/Mybuild
- src/lib/tftp/tftp.c
- src/lib/tftp/tftp.h
- templates/arm/stm32f7cube/mods.config
* Move tftp protocol stuff to lib/tftp
* Rework `tftp` command:
* Add flag for saving files directly to memory
* Fix bug with getting files: now don't wait data from port 69
* Add more examples
* Minor refactor
* Add `qspi_loader` to write data to stm32f7qspi via tftp protocol
> Work on lib/tftp

- src/kernel/sched/boot_thread.c
Following error occurs:
src/kernel/sched/boot_thread.c:29:44: error: array subscript -31744 is outside
array bounds of 'char[1]' [-Werror=array-bounds]
29 |  bootstrap = thread_init_stack(&_stack_top - kernel_stack_sz, kernel_stack_sz,
|                                ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
So cast it to uintptr_t for pointer arithmetic
> boot_thread: Fix build for GCC 9 with -Os

- src/drivers/video/Mybuild
- src/drivers/video/fb.lds.S
- src/drivers/video/stm32f7_lcd/Mybuild
- src/drivers/video/stm32f7_lcd/stm32f7_lcd.c
- templates/arm/qt-stm32f7discovery/build.conf
- templates/arm/qt-stm32f7discovery/lds.conf
- templates/arm/qt-stm32f7discovery/mods.config
- templates/arm/qt-stm32f7discovery/start_script.inc
* Enable Qt to run faster on stm32f7discovery
* Optionally put framebuffer into a separate linker section, not at the specified fixed address.
> Qt stm32 optimization

- platform/nuklear/templates/stm32f7/mods.config
Since static_heap and fixed_heap can be used together, static_heap is included
by default as a dependence of embox.mem.heap_bm with size=1M. Just decrease this size.
> Buildfix nuklear/stm32

- src/drivers/clock/cortexa9_timer/cortexa9_timer.c
In commit 02e6bbeb3b82635eb6f71cf73e3acf713b76cb3b jiffies initization
was made as explicit call, which happened inside
clock_source_register(), while this driver supposed that jiffies were
intialized after module init, so changing order of function calls in
init helps to solve problem with timer
> cortexa9_timer: Fix after jiffies rework

- src/cmds/record/record.c
This commit fixes -O2 build for pjsip/x86-qemu template
> cmds/record: Fix build for GCC 9 with -O2

- src/drivers/clock/pl031/Mybuild
- src/drivers/clock/pl031/pl031.c
PL031 is ARM Real Time Clock. We need it for some QEMU machines (e.g. `virt`).
> pl031: Initial implementation

- src/net/neighbour.c
There is no need to send ICMP DISCARD messages about packets
we haven't sent. Linux just sends ARP's to the neighbor, there are no ICMP packets. 
From RFC 792:
```
If the gateway processing a datagram finds the time to live field
is zero it must discard the datagram.  The gateway may also notify
the source host via the time exceeded message.
If a host reassembling a fragmented datagram cannot complete the
reassembly due to missing fragments within its time limit it
discards the datagram, and it may send a time exceeded message.
```
> net: Remove ICMP discard when neighbour is not resolved

- platform/opencv/cmds/edges.cpp
```	
int t1 = clock();
for (int y = 0; y < cedge.rows; y++) {
const uchar *row = &cedge.at<uchar>(y, 0);
for (int x = 0; x < 3 * cedge.cols; x += 3) {
unsigned rgb888	=
0xFF000000 |
unsigned(row[x]) |
(unsigned(row[x + 1]) << 8) |
(unsigned(row[x + 2]) << 16);
}
}
int t2 = clock();
std::cout << (t2 - t1)/double(CLOCKS_PER_SEC) << std::endl;
int t3 = clock();
for (int i = 0; i < cedge.cols; i++) {
for (int j = 0; j < cedge.rows; j++) {
Vec3b intensity = cedge.at<Vec3b>(j, i);
unsigned rgb888	=
0xFF000000 |
intensity.val[0] |
((intensity.val[1]) << 8) |
((intensity.val[2]) << 16);
}
}
int t4 = clock();
std::cout << (t4 - t3)/double(CLOCKS_PER_SEC) << std::endl;
```
Program output:
Image: 1024x1024; Threshold=1
0.003581 <- optimized time (seconds)
0.014571 <- initial variant
> opencv/edges: pixel loop optimization

- src/arch/aarch64/include/asm/hal/env/traps_core.h
- src/arch/aarch64/include/asm/hal/mmu.h
- src/arch/aarch64/include/asm/hal/reg.h
- src/arch/aarch64/include/asm/hal/test/traps_core.h
- src/arch/aarch64/include/asm/modes.h
- src/arch/aarch64/mmu/Mybuild
- src/arch/aarch64/mmu/mmu.c
- src/arch/aarch64/mmu/mmu.h
- src/arch/microblaze/mmu/mmu.c
- src/cmds/hardware/mm/mmutrans/mmutrans.c
- src/drivers/clock/pl031/pl031.c
- src/drivers/common/memory.c
- src/drivers/interrupt/cortex_a9_gic/cortex_a9_gic.c
- src/include/hal/mmu.h
- src/mem/vmem/vmem.h
- templates/aarch64/qemu/mods.config
Now it supports 4KiB, 16KiB and 64KiB page granules.
Also this PR fixes some memory issues (i.e. hard-coded 4KiB page size or missing headers)
> Aarch64 MMU implementation

- src/arch/x86/include/asm/entry.h
- src/arch/x86/lib/ptregs_jmp.S
- src/arch/x86/lib/vfork.S
backtrace now work everywhere except a few lines in `ptregs_jmp`, because in this function we jump on previous frame and change values of stack and registers.
> X86 vfork stackframe

- src/drivers/pci/pci.c
- src/drivers/pci/pci.h
- src/drivers/pci/pci_chip/pci_chip_elbrus.c
- src/drivers/pci/pci_chip/pci_chip_x86.c
- src/drivers/pci/pci_chip/pci_utils.h
- src/drivers/pci/pci_chip/ti81xx.c
IRQ numbering can be complicated for PCI devices. Previously Embox drivers simply took `IRQ line` from PCI configuration space, but for some platforms that's not enough (e.g. qemu/aarch64).
I suggest to use different functions for different PCI chips. However, even this approach will not solve all problems as IRQ numbering can also depend on interrupt controller model according to [osdev wiki](https://wiki.osdev.org/PCI#IRQ_Handling).
> PCI refactor

- platform/opencv/templates/stm32f764g-discovery/mods.config
- third-party/lib/opencv/Makefile
* Fix build when host already has zlib preinstalled.
* Fix run on stm32f764g-discovery after 3246a20 (since `loader` now uses interrupts with priorities, embox with opencv should too).
> Fix opencv

- src/drivers/block_dev/stm32_sd/stm32f7_sd.c
To satisfy devfs mount, which fails if there is sd driver in config, but microSD Card is not inserted.
> drivers: stm32f7_sd: Return 0 if SD is not inserted

- src/arch/arm/fpu/armv7m/fpv5.h
- src/arch/arm/fpu/vfp.h
- src/arch/arm/fpu/vfp9_s.h
Without that fix I permanently get infinity backtrace in GDB. GDB thinks these labels are functions, not local labels.
https://sourceware.org/binutils/docs/as/Symbol-Names.html
> fpu: Use numerical labels instead of characters in assembler

- src/compat/libc/string/strnlen.c
Early: strnlen("helloworld", 4) == 5
Now: strnlen("helloworld", 4) == 4
> Fix strnlen bug. Now maxlen works correctly.

- src/cmds/hardware/ide.c
- src/drivers/block_dev/block_dev.h
- src/drivers/block_dev/block_dev_common.c
- src/fs/driver/ext2/ext2.c
- src/fs/driver/ext3/ext3.c
- src/fs/driver/iso9660/cdfs.c
- src/fs/driver/iso9660/iso9660.h
- src/fs/driver/ntfs/ntfs.c
- src/fs/driver/power_save/qnx6.h
- src/fs/driver/ramfs/ramfs.c
- templates/arm/stm32f4-discovery/mods.config
Avoid errors for block devices larger than 4GiB.
Also rework some block dev handling to avoid 32/64-bit mistakes.
> block_dev: Use 64-bit value for block device size

- mk/extbld/lib.mk
Now build should not stop when some garbage was downloaded from the
first mirror (e.g. it's 404-Error HTML file instead of plain 404 reply)
> mk: Fix third-party downlaod for multiple mirrors

- src/arch/x86/boot/multiboot_header.S
It is introduced to overcome Qemu's slow BSS loading.
See the comment in code.
> x86: Multiboot header uses address fields

- src/drivers/mmc/core/Mybuild
- src/drivers/mmc/core/mmc.c
- src/drivers/mmc/core/mmc_host.c
- src/drivers/mmc/core/mmc_host.h
- src/drivers/mmc/core/sd.c
- src/drivers/mmc/core/sdio.c
- src/drivers/mmc/host/pl181/pl181.c
- src/drivers/mmc/host/sdhci/sdhci_ops.c
Currently Embox supports only MMC cards, but it would be helpful to have separated implementation for different card types as command sets are quite different.
Essentially, this pull request introduces `mmc_scan()` function, which should detect card type. SD/SDIO cards use stubs, but further they may be implemented properly.
> Divide MMC/SD/SDIO initialization

- scripts/live-flash
Fix ./scripts/live-flash to try bootloaders with Embox on QEMU:
For example, on x86/qemu:
Grub2:
```
$ ./scripts/live-flash grub2 grub2.img
$ sudo qemu-system-i386 -hda grub2.img -m 256 -nographic
```
Syslinux:
```
$ ./scripts/live-flash syslinux syslinux.img
$ sudo qemu-system-i386 -hda syslinux.img -m 256 -nographic
```
x86/debug seems to be broken, so I only checked in non-graphic mode currently.
> Fix live flash for qemu

- src/compat/posix/fs/dvfs/open.c
- src/fs/driver/fat/fat.h
- src/fs/driver/fat/fat_common.c
- src/fs/dvfs/compat.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs.h
- src/fs/dvfs/dvfs_util.c
* Fix double usage increase counter for dentry when open existing files
* Handle `-ENOMEM` error or FS driver `create()` in a more sane way
* Fix mount() return value to be compatible with old VFS
* Fix FAT driver for long dentries
> Work on VFS

- Vagrantfile
Former version support ended, repos are unavailable
> Use Ubuntu LTS for Xen Vagrant

- src/compat/libc/stdio/fopen.c
- src/fs/dvfs/dvfs.c
* Fix `fopen()` (now "a" also gives r/w permission)
* Fix `dvfs_file_open_idesc()` (set position to the end of the file)
`./scripts/autotest/run.sh fs-vfat echo` finally works (tested on `x86/arm` with SD-card emulation).
> Fix O_APPEND flag handling

- src/drivers/block_dev/stm32_sd/stm32f4_sd.c
* Add ipl lock for read/write operations
* Add retry if operation fails
These changes are necessary beacause Cube SD driver sometimes fails to read FIFO registers in time, probably it's supposed to be compiled with `-Os`. DMA operations fail for some reason.
Current version is extremely slow (~30kB/s), but `block_dev_test` works fine.
> STM32F4 SD driver fix

- scripts/autotest/framework/core.exp
- scripts/autotest/run.sh
* Currenly prompts on QEMU "#" and stm32 ">" differ, so add the ability to setup prompt.
* Tests print all by default.
> Autotest fix prompt

- src/fs/driver/fat/fat_dvfs.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs.h
- src/fs/dvfs/dvfs_util.c
Now FAT works fine if you do multiple `mount`/`umount` commands, mostly those issues were related to memory leaks.
`./scripts/autotest/run.sh fs-vfat mount` now is passing.
> Fix some mount-related issues

- scripts/autotest/configs/mmc.sh
- scripts/autotest/run_scripts/run_qemu_mmc.sh
- scripts/autotest/testsuite/block_dev/partitions/test.exp
- scripts/disk/partitions.sh
- src/cmds/fs/chmod.c
- src/cmds/fs/ls.c
- src/cmds/fs/mount.c
- src/cmds/testing/block_dev/block_dev_test.c
- src/compat/libc/stdio/rename_dvfs.c
- src/compat/posix/fs/chown/chown_dvfs.c
- src/compat/posix/fs/dvfs/chmod.c
- src/compat/posix/fs/dvfs/xattr.c
- src/drivers/block_dev/block_dev.c
- src/drivers/block_dev/block_dev.h
- src/drivers/block_dev/block_dev_idesc_dvfs.c
- src/drivers/block_dev/block_dev_idesc_oldfs.c
- src/drivers/block_dev/partition/partition.c
- src/drivers/mmc/core/Mybuild
- src/drivers/mmc/core/mmc_host.c
- src/drivers/mmc/host/pl181/pl181.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/dvfs/compat.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs_xattr.c
- src/fs/fuse/fuse_linux.c
- src/fs/rootfs_dvfs.c
Extend support for block device partitions:
* Add intensive partition test to `block_dev_test`
* Create partitions in MMC subsystem
* Fix read/write operation for partitions
* Add script to generate disk image with partitions
Minor fixes:
* Change partition naming: if block device name is finished with digit, add 'p' prefix, so `mmc0` will have partitions like `mmc0p1`, not `mmc01`
* Fix memory leaks for FAT
* Fix `mount` output for new VFS
* Fix filetype check in some fs commands
* Fix some typos
To run partition test on QEMU, use `arm/qemu` template and pass `-sd card.img` option. Then run `block_dev_test -p mmc0`.
To generate card image with partitions, run `scripts/disk/partitions.sh`, for example:
`./scripts/disk/partitions.sh card.img 4 fat 16`
> Work on partition support

- platform/gpio_http_admin/templates/stm32f4_discovery/mods.config
- src/cmds/net/telnetd/Makefile
- src/cmds/net/telnetd/Mybuild
- src/cmds/net/telnetd/telnet.h
- src/cmds/net/telnetd/telnet_util.c
- src/cmds/net/telnetd/telnetd.c
- src/kernel/thread/signal/Mybuild
- src/kernel/thread/signal/siginfoq.c
- templates/arm/stm32f4-discovery/mods.config
- templates/arm/stm32f764g-discovery/mods.config
- templates/arm/stm32f769i-discovery/mods.config
- templates/arm/test/units/mods.config
- templates/microblaze/test/units/mods.config
- templates/mips/test/units/mods.config
- templates/x86/test/fs/mods.config
- templates/x86/test/net/mods.config
- templates/x86/test/units/mods.config
Rework telnet:
* This implementation creates only one task per one client connection instead of a task and pthread as it was before. So for example, having now pool with 4 threads on stm32 we can handle 3 parallel connections instead of 1 as it was before.
* Logic is unified - there are no more two implementations (with and without pthreads)
* You can compile, run and debug this telnetd on Linux:
```
$ cd src/cmds/net/telnetd
$ make
$ ./telnetd
telnetd started on port 3023
```
Then connect:
```
$ telnet localhost 3023
```
> Fix telnet

- src/cmds/net/telnetd/telnetd.c
- src/kernel/task/idesc/idesc_table.c
Fix cloexec handling and idesc table fork'ing. Index descriptors in child must be at the same position as in parent, so do not allocate minimal index but copy at the same position. btw, it fixes telnet exits, when there are multiple clients connections.
> vfork: Copy idesc at the same position as in parent

- scripts/autotest/run_scripts/run_qemu_mmc.sh
- scripts/autotest/testsuite/fs-vfat/mount/test.exp
- src/fs/driver/fat/fat_common.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs.h
- src/fs/dvfs/dvfs_util.c
- src/fs/syslib/kfsop.c
* Don't call fs->sb_clean_up() if root inode was not created due to
mount error
* Close bdev file desc on umount
* Reconnect "shadowed" dentry after umount
* Minor ref inc/dec balance fix
* Minor fix for autotest/mount script
As a result, `./scripts/autotest/run.sh fs-vfat mount` can be run successfully with at least 8192 iterations. Longer runs cause exceptions in `util/ring_buff` from time to time, but this seems to be terminal-related issue.
> Fix mount-related memory leaks

- scripts/continuous/run.sh
Sometimes kill_bg() is called with empty $sim_bg string, which causes
pstree to print every single process in the system, which leads to
killing all processes in the system.
Solution is to make sure $sim_bg is not empty before calling pstree
> scripts/continuous/run.sh: Avoid system crash on running this script

- mk/image2.mk
- mk/image3.mk
On NixOS:
```sh
$ which rm
/run/current-system/sw/bin/rm
```
> mk: Remove hardcoded path

- src/compat/posix/fs/dirent/dirent_oldfs.c
- src/fs/driver/devfs/devfs_oldfs.c
- src/fs/driver/ntfs/ntfs.c
- src/fs/mount_table.c
- src/fs/rootfs.c
- src/fs/syslib/kfsop.c
- src/fs/syslib/perm.c
Don't create /dev/ node in devfs driver itself, just mount it with regular mount() call in rootfs_mount()
As a little bonus, `devfs` is now listed in `mount` command for old VFS.
> Fix devfs mount

- src/drivers/usb/hc/ehci_hcd.c
- src/drivers/usb/hc/ehci_q.c
This PR fixes qemu warnings "update active QH" during block_dev_test.
IAA is used to unlink current QH. So it is more correct to use it when you need to delete QH safely (not used now, but should be used), not to monitor transfer completion. For transfer completion IOC interrupt is used - we just set up this interrupt for the last QTD in QH's qtds list, so IOC will be generated only after all qtds will be handled.
> ehci: Use IOC interrupt instead of IAA

- src/fs/Mybuild
- src/net/socket/tcp_sock.c
Now `arm/qt-stm32f7discovery` compiles and works with GCC 9.2.0 :)
> tcp_sock fix

- src/compat/libc/include/stdlib.h
* Double declaration of `strtod()` causes errors with some compiler options
* Group `strtoX()`/`atoX()` functions declarations
> stdlib.h minor refactor

- scripts/autotest/testsuite/fs-rootfs/finish.exp
- scripts/autotest/testsuite/fs-rootfs/ls/test.exp
- scripts/autotest/testsuite/fs-rootfs/setup.exp
- src/compat/posix/fs/dirent/dirent_dvfs.c
- src/compat/posix/fs/open/open_dvfs.c
- src/fs/dvfs/dvfs.c
Keep fixing stuff for FS.
* Decrease usage counter for previous dentry, not current in `readdir()`
* Fill `lookup` properly in `dvfs_iterate()`
* Make sure to free inodes that are not integrated to VFS
* Handle O_PATH for dvfs
* Add autotest to check this PR actually fixes something :)
> readdir() fix

- src/arch/aarch64/mmu/mmu.c
> aarch64: Fix mmu_pte_unpack() return value

- src/drivers/block_dev/block_dev_idesc.c
- src/drivers/char/char_dev.c
- src/fs/file_desc.c
Before these changes there was a bug that could be reproduced like this:
* Load `arm/qemu` conf
* Comment out new VFS modules, uncommend old VFS commends
* `make && ./scripts/qemu/auto_qemu -sd fat.img`, where `fat.img` is image with FAT FS
* `dd if=/dev/mmc0 format=hex_c` (`mmc0` should be the name of block device)
* `mkdir -v /mnt`
* `mount -t vfat /dev/mmc0 /mnt` On this step `mount` fails as there's a trash content in `/dev/mmc0` FS node due to invalid file close in `dd` which leads to duplicating nodes.
Now it works fine.
> Fix block and char devices close ops

- src/drivers/i2c/adapters/stm32/stm32_i2c.c
- src/drivers/sensors/gy_30/gy_30.c
There is a part of bad Cube API:
```
* @param  DevAddress Target device address: The device 7 bits address value
*         in datasheet must be shift at right before call interface
```
It means we need to shift the address before transmit. Moreover, we need to shift to _left_, not  _right_.
> Fix stm32 i2c

- src/fs/driver/ext3/ext3.c
- src/fs/driver/fs_driver.c
- src/fs/file_system.c
- src/fs/syslib/kfile_node.c
- src/fs/syslib/kfsop.c
- src/include/fs/file_system.h
- src/include/fs/fs_driver.h
As it turned out, we don't really need to create FS driver in runtime as
all of them are registered statically. This way we can remove a lot of
code.
Also declare drivers as const objects so they are not changed by
accident
> fs/fs_driver: Remove functions for dynamic fs driver allocation

- src/cmds/fs/mount.c
- src/fs/driver/devfs/devfs_dvfs.c
- src/fs/driver/dfs/dfs.c
- src/fs/driver/ext2fuse/ext2fuse.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/driver/initfs/initfs_dvfs.c
- src/fs/driver/ramfs/ramfs_dvfs.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs.h
- src/fs/dvfs/dvfs_util.c
- src/fs/dvfs/fs_driver.h
This field was never actually used in any FS and also doesn't seem to be
useful at all. It's used just to bass block device pointer, so getting
rid of this field simplifies code.
Also remove related unused functions.
> fs/dvfs: Get rid of bdev_file from super_block

- src/cmds/hardware/sensors/l3g4200d/Mybuild
- src/cmds/hardware/sensors/l3g4200d/l3g4200d.c
- src/drivers/i2c/adapters/stm32/Mybuild
- src/drivers/i2c/adapters/stm32/stm32_i2c.c
- src/drivers/sensors/l3g4200d/Mybuild
- src/drivers/sensors/l3g4200d/l3g4200d.c
- src/drivers/sensors/l3g4200d/l3g4200d.h
* Fix i2c driver for stm32 - use polling, irq variant seems to be broken in Cube (but it should be checked more accurate, probably with reworking the driver without using Cube)
With l3g4200d something was wrong with SDA line - there was not STOP i2c condition on that line after register reading
* Add l3g4200d gyro driver in I2C mode
> Add l3g4200d gyro driver

- src/fs/driver/ext2/ext2.c
- src/fs/driver/ext2/ext2_balloc.c
- src/fs/driver/ext2/ext2_xattr.c
- src/fs/driver/ext3/ext3.c
- src/fs/driver/ext4/ext4_balloc.c
- src/include/fs/ext2.h
Some function don't really need `nas` structure to be passed, in some
cases just passing `struct super_block` is fine
Most of `mount` handlers for old VFS drivers can be splitted into two parts:
1. Initilize FS-specific data (which corresponds to new VFS `fill_sb` handler)
2. Integrating all files into VFS tree
Due to VFS-specific ext2 function arguments it's hard to split it this way for ext2 (for example, `struct nas` is passed, while only corresponding bdev is required for function). So I fix some functions to become VFS-agnostic.
> ext2: Refactor some functions for further VFS rework

- src/cmds/fs/mkramdisk.c
This is helpful for two reasons:
1) You don't need to remember, what's the default name for ramdisk (ramX
vs ramdiskX vs whateverX)
2) If you create multiple ramdisks, you don't need to track indices
> cmds/fs/mkramdisk: Print name of the created device

- src/fs/driver/cifs/cifs.c
- src/fs/driver/ext2/ext2.c
- src/fs/driver/ext4/ext4.c
- src/fs/driver/fat/fat_oldfs.c
- src/fs/driver/jffs2/jffs2.c
- src/fs/driver/nfs/nfs.c
- src/fs/driver/ntfs/ntfs.c
- src/fs/driver/ramfs/ramfs_oldfs.c
- src/fs/syslib/kfsop.c
This function is called at the end of every .delete_node handler, so it
makes sense just to call it in common code after this handler.
This change allows to use the same delete handler for both VFS versions
> fs: Move vfs_del_node() from .delete_node to common VFS code

- src/fs/driver/binfs/binfs.c
- src/fs/driver/cifs/cifs.c
- src/fs/driver/devfs/devfs_oldfs.c
- src/fs/driver/ext2/ext2.c
- src/fs/driver/ext3/ext3.c
- src/fs/driver/ext4/ext4.c
- src/fs/driver/fat/fat_common.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/driver/fat/fat_oldfs.c
- src/fs/driver/initfs/initfs_oldfs.c
- src/fs/driver/iso9660/cdfs.c
- src/fs/driver/jffs2/jffs2.c
- src/fs/driver/nfs/nfs.c
- src/fs/driver/ntfs/ntfs.c
- src/fs/driver/ramfs/ramfs.h
- src/fs/driver/ramfs/ramfs_dvfs.c
- src/fs/driver/ramfs/ramfs_oldfs.c
- src/fs/driver/ramfs/ramfs_ops.c
- src/fs/inode.h
- src/fs/super_block.c
- src/fs/syslib/kfsop.c
- src/include/fs/fs_driver.h
- src/include/fs/super_block.h
Now use VFS-agnostic `fill_sb` handler to initliaze super block from given source (this handler can be used in both VFS implementations) and `mount` itself which mounts all the files.
> fs: Split VFS mount handlers

- src/cmds/hardware/sensors/l3g4200d/Mybuild
- src/drivers/sensors/l3g4200d/Mybuild
- src/drivers/sensors/l3g4200d/l3g4200d.c
- src/drivers/sensors/l3g4200d/l3g4200d_i2c.c
- src/drivers/sensors/l3g4200d/l3g4200d_spi.c
- src/drivers/sensors/l3g4200d/l3g4200d_transfer.h
- src/drivers/spi/stm32/spi_conf_f4.h
- src/drivers/spi/stm32/stm32.c
- src/drivers/spi/stm32/stm32_spi1.c
- src/drivers/spi/stm32/stm32_spi2.c
* Fix stm32 SPI
* Add SPI setup for l3g4200d
There can be both I2C and SPI module at once in one configuration, but it requires more complex sensors storage, so I currently add abstract module l3g4200d and two implementations - l3g4200d_i2c and l3g4200d_spi.
> l3g4200d gyro add SPI mode

- src/compat/posix/fs/dirent/dirent_oldfs.c
- src/fs/driver/cifs/cifs.c
- src/fs/driver/devfs/devfs_oldfs.c
- src/fs/driver/ext2/ext2.c
- src/fs/driver/ext4/ext4.c
- src/fs/driver/fat/fat_oldfs.c
- src/fs/driver/initfs/initfs_oldfs.c
- src/fs/driver/iso9660/cdfs.c
- src/fs/driver/jffs2/jffs2.c
- src/fs/driver/nfs/nfs.c
- src/fs/driver/ntfs/ntfs.c
- src/fs/driver/ramfs/ramfs_oldfs.c
- src/fs/vfs.c
When inode is created, `node->nas->fs` and `node->i_sb` are set in every FS driver, but it makes more sense to set it in `vfs_subtree_create_child()`, because it's called anyway to integrate new node into VFS tree.
> vfs: Set superblock pointer for inode in common code

- src/fs/driver/cifs/cifs.c
- src/fs/driver/ext2/ext2.c
- src/fs/driver/ext4/ext4.c
- src/fs/driver/fat/fat_oldfs.c
- src/fs/driver/iso9660/cdfs.c
- src/fs/driver/jffs2/jffs2.c
- src/fs/driver/nfs/nfs.c
- src/fs/driver/ntfs/ntfs.c
- src/fs/syslib/kfsop.c
Make super_block allocation/freeing symmetric: if it's allocated in `kmount()`, it probably should be freed in `kumount()`. Also it deduplicates some code in fs drivers.
> vfs: Free super block in kumount()

- src/fs/driver/devfs/devfs_dvfs.c
- src/fs/driver/devfs/devfs_oldfs.c
- src/fs/driver/ext2fuse/ext2fuse.c
- src/fs/driver/fat/fat_common.c
- src/fs/driver/fat/fat_dvfs.c
- src/fs/driver/fat/fat_oldfs.c
- src/fs/driver/fuse/fuse_fs_driver.c
- src/fs/driver/initfs/initfs_dvfs.c
- src/fs/driver/ramfs/ramfs_dvfs.c
- src/fs/driver/ramfs/ramfs_oldfs.c
- src/fs/dvfs/dvfs.c
- src/fs/dvfs/dvfs.h
- src/fs/dvfs/dvfs_dentry.c
- src/fs/dvfs/dvfs_util.c
- src/fs/dvfs/file_desc.h
- src/fs/dvfs/fs_driver.h
- src/fs/dvfs/inode.c
- src/fs/dvfs/inode.h
- src/fs/inode.c
- src/fs/inode.h
- src/fs/super_block.c
- src/fs/syslib/kfsop.c
- src/fs/vfs.c
- src/include/fs/inode_operation.h
- src/include/fs/super_block.h
A bunch of changes for VFS:
* Don't use dentries at all for FS drivers. It's achieved by:
* Now each superblock has inode root pointer instead of dentry pointer. Previously it was used just to reference to inode date (e.g. `sb->root->d_inode->data = new_data;`)
* `.lookup()` handlers now use inode as well
* Simplify `mount()`
* Create and destroy root inode during super_block_alloc()/super_block_free(), so no need to do it in every FS driver
* Get rid of `.mount_end()` handler. It turned out that all the stuff from this handler could be done in `.fill_sb()` if root inode is provided
* Finally, `struct super_block` is the same for both VFS versions
* Minor fixes for memory leaks and other bugs
> Mount rework

- src/drivers/gpio/dwapb/Mybuild
- src/drivers/gpio/dwapb/dwapb_gpio.c
- src/drivers/sensors/l3g4200d/l3g4200d_spi.c
- src/drivers/spi/dw_spi/Mybuild
- src/drivers/spi/dw_spi/dw_spi.c
- src/drivers/spi/dw_spi/dw_spi.h
- templates/arm/de0_nano_soc/mods.config
- templates/arm/el24d2/mods.config
Fix DW SPI driver - in polling mode without DMA we have to fill tx fifo with data faster than fifo becomes empty, because this SPI controller automatically controls CS line state and if tx fifo becomes empty CS go high (inactive) state. Also, spi1 and i2c1 share the same GPIO pins, so I commented spi1 in mods.config and added comments. L3G4200D gyro currently works on SPI1 on DE0 Nano SOC.
> Add l3g4200d gyro (spi mode) to DE0 Nano SOC

- Makefile
There's a known issue #1690 with make 4.3.
This is a temporary solution to print meaningful error if used with `make` 4.3.
> mk: Stop building if used with make 4.3

- src/drivers/usb/hc/ehci.h
- src/drivers/usb/hc/ehci_hcd.c
- src/drivers/usb/hc/ehci_mem.c
- src/drivers/usb/hc/ehci_q.c
- src/drivers/usb/usb_hub.c
Each ehci endpoint has its own preallocated QH (queue head), which is filled with qtds created from an incoming usb request (URB). There was a problem that ehci cannot handle multiple requests coming from several threads. Now it is solved in the following way - when the async queue is empty then current QH (made from incoming URB) will be added to the async queue and started immediately. When the async queue is not empty qtds will be created and QH will be deferred.
> Ehci multiple urbs

- src/drivers/spi/stm32/stm32_spi1.c
- third-party/bsp/stmf4cube/Mybuild
- third-party/bsp/stmf4cube/arch.c
Last bit on SPI1 with l3g4200d was wrong. Now it is fixed due to "STM32F40x and STM32F41x
Errata sheet" recommended workaround - "2.5.2 Corrupted last bit of data and/or CRC, received in Master mode with delayed SCK feedback"
> stm32f4: Add workaround for spi1 due to stm32f4 errata

- platform/etnaviv/templates/imx6/build.conf
- platform/fpga/templates/de0_nano_socfpga/build.conf
- platform/mesa/templates/integratorcp/build.conf
- platform/mesa/templates/mesa_imx6/build.conf
- platform/nuklear/templates/arm_qemu/build.conf
- platform/opencv/templates/arm-qemu/build.conf
- platform/pjsip/templates/arm-qemu/build.conf
- templates/arm/am3505/build.conf
- templates/arm/arria_v/build.conf
- templates/arm/bpi/build.conf
- templates/arm/c++_demo/build.conf
- templates/arm/de0_nano_soc/build.conf
- templates/arm/el24d2/build.conf
- templates/arm/iwave_imx6/build.conf
- templates/arm/omap/build.conf
- templates/arm/qemu/build.conf
- templates/arm/qt-app/build.conf
- templates/arm/raspi/build.conf
- templates/arm/sabrelite/build.conf
- templates/arm/sk_imx6q/build.conf
- templates/arm/test/units/build.conf
- templates/arm/var_som_mx6/build.conf
- templates/arm/vexpress-a9/build.conf
`-mapcs-frame` gcc option is used to make ARM stack frame in ACPS format, so we can do backtrace. It requires a bit of additional memory per each frame. So, I updated some of "big" ARM tempaletes so backtrace should work out of the box.
> tempates: Add -mapcs-frame flag to arm templates

- src/drivers/common/memory.c
- src/drivers/net/dwc_gmac/dwc_gmac.c
- src/drivers/net/dwc_gmac/dwc_gmac.h
Building this driver with `-O2` option led to few problems:
* Using `dcache_inval()` sometimes invalidated some unwanted data with address close to descriptor base
* `dcache_inval()`/`dcache_flush()` operations sometimes affected neighbor descriptors too which led to more bugs
This pull-request gets rid of `dcache_inval()`/`dcache_flush()` and replaces them with allocation of uncached memory and data/instruction barriers.
Also reset operation is improved and uses more bit fields (i.e. we're less reliant on initial network controller setup by u-boot).
> Fix DWC GMAC net driver for -O2 build

- src/fs/vfs.c
For some pathes `mnt_desc` field may be NULL, so it should be checked.
Otherwise it led to exception when getting path by node.
> fs/vfs: Fix if_root_follow_up()

- src/drivers/clock/integrator_pit/integrator_pit.c
The CLOCK_RATE is set to the cpu_core_freq which is supplied during the configuration of arm/qemu
Fixes #1708
> driver/clock: (minor) Adjust CLOCK_RATE in integrator_pit

- src/cmds/testing/block_dev/block_dev_test.c
The implementation currently uses optind to get follow-on parameter
of an option, but the problem with this is when getopt is returned,
optind contains the index of the next argv argument for a subsequent
call to getopt(). This commit replaces it with optarg: when getopt
encounters an option it's follow-on parameter is found in optarg.
Fixes: #1725
Signed-off-by: Mohana Datta Yelugoti <ymdatta.work@gmail.com>
> cmd: testing: fix incorrect parsing of command line arguments

- src/drivers/usb/hc/ohci_pci.c
Fix ohci to detect attached devices - it was cleared forever because of OHCI power off. Probably, it's qemu bug, since ehci the same logic works fine.
> Ohci disable "port power off" handling

- src/cmds/testing/block_dev/block_dev_test.c
This patch adds functionality for 'block_dev_test' command to
specify the block number at which the command should start. It also
adds information about this option to be displayed in the help
message. This fixes part of #1709.
Signed-off-by: Mohana Datta Yelugoti <ymdatta.work@gmail.com>
> [WIP] cmd: testing: add option for block_dev_test to start at given block number

- src/drivers/scsi/scsi.c
- src/drivers/scsi/scsi_disk.c
- src/drivers/usb/class/usb_mass_storage.c
- src/drivers/usb/class/usb_mass_storage.h
- src/drivers/usb/usb_core.c
- src/include/drivers/usb/usb.h
* Linearize mass storage request - no more callbacks, get rid of the state machine too.
* SCSI is also a bit simplified - no more waitq because of mass storage waits itself until request processed.
> Simplify mass storage and scsi

- src/cmds/fs/more.c
- src/compat/posix/curses/curses.c
Removed endwin call. Which was called before the screen write process.
Corrected the EOF detection which was faulty as random characters filled
the screen.
Replaced space with zero in function newterm in file curses.c
in the memset command.
more commands works correctly for short files.
> Solved Issue #1740 Incorrect output of more command on short files

- Makefile
Added code to change the stack size on a Mac without raising any error.
Code first checks if it is being run on a Mac. If so, it finds the maximum stack size limit allowed by the hardware and sets it with ```ulimit -s STACK_SIZE_LIMIT```.
```STACK_SIZE_LIMIT```is provided by ```ulimit -Hs```.
> mk: makefile: Fix stack-size error on Mac

- src/compat/posix/semaphore.c
POSIX semaphore value begins from its max available value, `sem_post()` decrements it and `sem_wait()` decrements it. The kernel semaphore module does in contrary.
Temporally resolve #1750
> posix: semaphore: Add an adaptive layer to get POSIX semaphore value

- src/fs/driver/initfs/initfs_dvfs.c
- src/fs/driver/initfs/initfs_fops.c
- src/fs/driver/initfs/initfs_oldfs.c
Fixed weird error codes when try write or create in initfs
`mkdir /tmp_dir`
or
`touch /tmp_file`
> fs: Fix odd error codes during write access to initfs

- src/drivers/scsi/scsi.c
- src/drivers/scsi/scsi.h
- src/drivers/scsi/scsi_disk_create.c
- src/drivers/usb/class/usb_mass_storage.c
The goal of this PR is just to simplify SCSI logic.
* Remove scsi per-command states. While the idea to have scsi state machine is undoubtedly good, introducing a state for each scsi command looks overcomplicated and creates additional troubles to debug and add new states. I would like to refer here to Linux `include/scsi/scsi_device.h`:
```
enum scsi_device_state {
SDEV_CREATED = 1,   /* device created but not added to sysfs
* Only internal commands allowed (for inq) */
SDEV_RUNNING,       /* device properly configured
* All commands allowed */
SDEV_CANCEL,        /* beginning to delete device
***
};
```
You can see here a state machine, but not for each scsi command. In Embox there are two states only - attached and detached for now (I mean the flag `dev->attached`).
* Make mass storage …
> Scsi simplify the logic

- src/arch/x86/lib/cpu_performance/cpu_info.c
- src/arch/x86/lib/cpu_performance/cpu_info.h
- src/cmds/cpuinfo.c
The cpuinfo command now displays base and max frequency along with FPU,
MMX, and SSE as mentioned in issue #1758.
> x86/lib: cmds: Extend `cpuinfo` command output

- src/tests/math/Mybuild
- src/tests/math/math_test_fp.c
wrote tests for fp functions and also replaced embox.libc.math_builtins with embox.compat.libc.math_openlibm.
> fixes #1745 math floating point tests

- src/tests/posix/pthread/Mybuild
- src/tests/posix/pthread/pthread_rwlock_test.c
Add unit tests for the following functions in posix/pthreads:
pthread_rwlock_destroy(pthread_rwlock_t *);
pthread_rwlock_init(pthread_rwlock_t *, const pthread_rwlockattr_t *);
pthread_rwlock_rdlock(pthread_rwlock_t *);
pthread_rwlock_tryrdlock(pthread_rwlock_t *);
pthread_rwlock_trywrlock(pthread_rwlock_t *);
pthread_rwlock_unlock(pthread_rwlock_t *);
pthread_rwlock_wrlock(pthread_rwlock_t *);
This fixes the issue #1747  
> tests: posix: pthreads: Add tests for pthread_rwlock_*

- src/arch/x86/kernel/acpi_shutdown.c
Replace the break statement to return statement in the acpi_shutdown
fuction.
> x86: kernel: acpi: Change break to return in function

- src/cmds/testing/block_dev/block_dev_test.c
This patch adds functionality for 'block_dev_test' command to
specify multiple read/write blocks in a single iteration. It also
adds information about this option to be displayed in the help
message. Default value of multiple blocks is set as 4, in case if
the argument is not given by the user but the flag is provided.
This fixes part of #1709.
Signed-off-by: Mohana Datta Yelugoti <ymdatta.work@gmail.com>
> cmd: testing: block_dev_test: add multiple read/writes blocks option

- platform/efm32zg_sk3200/templates/debug/build.conf
- platform/gpio_http_admin/templates/stm32f4_discovery/build.conf
- platform/nuklear/templates/arm_qemu/build.conf
- platform/pjsip/templates/stm32f746g-discovery/build.conf
- platform/pjsip/templates/stm32f769i-discovery/build.conf
- templates/arm/qt-stm32f7discovery/build.conf
- templates/arm/stm32f4-discovery-clang/build.conf
- templates/arm/stm32f4-discovery/build.conf
- templates/arm/stm32f746g-discovery/build.conf
- templates/arm/stm32f769i-discovery/build.conf
- templates/e2k/monocube/build.conf
*.conf files are parsed by C preprocessor (i.e. in
scripts/qemu/auto_qemu), so shell-style comments may break it
> (templates) Replace sh-style comments with C-style comments

- .github/workflows/ci.yml
- .travis.yml
- scripts/continuous/build.sh
- scripts/continuous/fs/img-manage.sh
- scripts/continuous/fs/run.sh
- scripts/continuous/net/run.sh
- scripts/continuous/prepare.sh
- scripts/continuous/run.sh
- scripts/continuous/touch-mk-cache.sh
- scripts/expect/ping.exp
- src/cmds/shell/Mybuild
- templates/test/buildgen/build.conf
- templates/test/buildgen/lds.conf
- templates/test/buildgen/mods.config
- templates/x86/test/net/mods.config
- templates/x86/test/net/start_script.inc
- templates/x86/test/ping-target/build.conf
- templates/x86/test/ping-target/lds.conf
- templates/x86/test/ping-target/mods.config
- templates/x86/test/ping-target/rootfs/hosts
- templates/x86/test/ping-target/start_script.inc
New Actions infrastructure can be used for CI
* flexible: multiple workflows and triggers, can provide
* long tests are started nightly
* shorter tests are started on PR/push
* 20 concurrent workers are provided by default
This PR adds Actions and makes a few changes to improve for CI cycle time. 
There are some thoughts on nightly/on-push a the bottom.
Travis before: 28:46 (https://travis-ci.org/embox/embox/builds/659590134)
Travis after: 25:30 (https://travis-ci.org/AntonKozlov/embox/builds/659745090)
Actions: 14:45 (https://github.com/AntonKozlov/embox/actions/runs/51646799)
(There is some time distribution, numbers are illustrative)
CI run organized in buildgen and actual test jobs. Buildgen only creates `mk/.cache` to avoid each test to do all Mybuilds parsing.
* this should improve …
> Use GitHub Actions for CI

- src/drivers/char/char_dev_stub.h
* Add MAX_CDEV_QUANTITY macro
* Remove cdev_idesc_alloc() declaration
> char_dev_stub: Unify interfaces with char_dev

- src/cmds/hardware/ide.c
I had written a patch fixing the main issue with cmds/hw/ide which had to do with printing the name of the device and not working on either dvfs nor oldfs(and coredumping).
the main issue was apparently fixed by 6bbb6c13e160c52b968347e5f6be8f4930fa1971.
This is what remains of that patch, fixing getopt(), which was missing the first argument.
> cmds: Fix hardware/ide getopt().

- src/arch/x86/kernel/Mybuild
Add the includes which are required for the successful build
of ACPI. This solves #1799 
> x86: kernel: ACPI: Fix build error

- src/drivers/scsi/scsi.c
- src/drivers/scsi/scsi.h
- src/drivers/scsi/scsi_disk.c
Remove `fixup` callbacks used to fill SCSI commands, it only makes the code more complicated.
> scsi: Make scsi commands filling linear

- src/compat/posix/semaphore.c
- src/tests/posix/Mybuild
- src/tests/posix/sem_test.c
- templates/x86/test/units/mods.config
Resolve #1748 Add some unit tests for:
```c
extern int    sem_destroy(sem_t *);
extern int    sem_getvalue(sem_t *, int *);
extern int    sem_init(sem_t *, int, unsigned);
extern int    sem_post(sem_t *);
extern int    sem_timedwait(sem_t *, const struct timespec *);
extern int    sem_trywait(sem_t *);
extern int    sem_wait(sem_t *);
```
Implement
```c
extern int    sem_timedwait(sem_t *, const struct timespec *);
```
> posix: semaphore: Add unit tests for POSIX semaphore

- scripts/expect/ping.exp
- templates/x86/test/net/start_script.inc
`ping 192.168.128.128.xip.io` fails too often for both expect tests and start_script:
https://github.com/embox/embox/runs/505471758#step:10:266 (start_script)
https://github.com/embox/embox/runs/505907968#step:10:208 (expect)
Because of too many re-launches and questions we are disabling the test. The issue is here - https://github.com/embox/embox/issues/1865
> ci: Disable ping xip.io tests

- src/drivers/usb/Mybuild
- src/drivers/usb/hc/Mybuild
- src/drivers/usb/hc/ehci.h
- src/drivers/usb/hc/ehci_hcd.c
- src/drivers/usb/hc/ehci_mem.c
- src/drivers/usb/hc/ehci_q.c
- src/drivers/usb/hc/ohci.h
- src/drivers/usb/hc/ohci_pci.c
- src/drivers/usb/usb_config.c
- src/drivers/usb/usb_core.c
- src/drivers/usb/usb_queue.c
- src/include/drivers/usb/usb.h
- src/include/drivers/usb/usb_queue.h
* Use lthreads to handle USB requests when they are completed.
* Refactor USB queue - now it has dlist interface but with irq_lock/unlock protection.
* Extract USB hub to a separate module.
> Use lthread to handle USB requests

- platform/nuklear/templates/stm32f7/mods.config
- platform/opencv/templates/stm32f746g-discovery/mods.config
- platform/opencv/templates/stm32f769i-discovery/mods.config
- platform/stm32f7/templates/stm32f7_discovery/mods.config
- src/include/embox/runlevel.h
- src/kernel/init.c
- templates/x86/test/units/mods.config
Old-style start_script init module was usually placed to 3-th runlevel. This module calls shell, so this resulted in avoiding running any 4-th level modules (being more specific,
But system_start_service is not runnable module on it's own, it's just being called from the kernel, so it doesn't have any run level and runs after all init levels; that means 4-th level modules are executed before opening the shell.
* Don't run 4-th runlevel on kernel init at all
* Move non-working tests in `x86/test/unitx` to `@Runlevel(4)`
> Fixing 4-th runlevel handle

- src/cmds/testing/block_dev/block_dev_test.c
This patch replaces the various return values with correct error
codes, which can further be used to identify exactly what went
wrong when the command fails.
Signed-off-by: Mohana Datta Yelugoti <ymdatta.work@gmail.com>
> cmds: block_dev_test: replace return values with correct error codes

- src/drivers/usb/usb_hub.c
Generally, power disable is not required when scanning USB ports. Also, it fixes OHCI hubs using in Qemu (`./scripts/qemu/auto_qemu_with_usb_hub` on x86/qemu)
> usb: Do not disable hub ports power

- third-party/lib/acpica/osemboxxf.c
Add call to mmap_device_memory in AcpiOsMapMemory function.
This solves Memory Map bug at issue #1835 
> x86: kernel: ACPICA: Fix memory map bug

- templates/arm/iwave_imx6/mods.config
Add vfat (tested with EHCI).
```
root@embox:/#lsblk                                                              
Block devices:
ID |  NAME          |    SIZE    | TYPE
0 |    sda         | 16055795200 | disk
root@embox:/#mkdir -v /mnt
root@embox:/#mount -t vfat /dev/sda /mnt                                        
root@embox:/#ls /mnt                                                            
/mnt/my.txt
/mnt/1.txt
root@embox:/#cat /mnt/1.txt                                                     
Hello embox! Test 123 456 Bye!
```
> templates: Add fat driver to imx6/iwave

- src/fs/driver/dfs/dfs.c
- templates/arm/stm32_dvfs/mods.config
- templates/arm/stm32_modbus/mods.config
Now `stm32_modbus` templates works and saves config to flash device.
> Fix DumbFS driver

- src/drivers/clock/Mybuild
- src/drivers/clock/riscv_clk.c
- templates/riscv/qemu-sifive-u/mods.config
The recommended frequency of sifive coreclk is 1.0 GHz.
`include embox.arch.system(core_freq=1000000000)`
`#define HZ 100000`
then the clock works correctly
> modified: riscv_clk.c and qemu-sifive-u/mods.config

- src/cmds/sys/env.c
- src/compat/posix/proc/exec.c
Closes #1335:
Behaves like execv in posix: returns -1 on failure and sets errno to the value of error that occurred. Seems to have fixed #1334, but does not seem to have helped #1702.
> execv: fix execv returns 0 and doesn't set errno

- src/cmds/hardware/lsblk/lsblk.c
Fixes #1699 
- This PR improves the available `lsblk` command in Embox. It mirrors the linux [lsblk](http://man7.org/linux/man-pages/man8/lsblk.8.html) command adding the `-b, --bytes` flags to choose the unit of displaying size.
_I tried multiple ways to round the value of size to the nearest integer but they all failed resulting in the error message posted on the issue page. The current behavior is typecasting the `float` to `uint64_t` (flooring)._
> Mirror Linux lsblk command

- src/drivers/serial/pl011/pl011.c
Fixes https://github.com/embox/embox/issues/1891
Occasionally I misunderstood what FIFO means, and enabled RX fifo which means to trigger RX irq only with trigger level (>= 2 incoming chars). So now I disabled fifo mode and irq happens per each incoming character.
> pl011: Disable back FIFO mode

- src/tests/stdlib/Mybuild
- src/tests/stdlib/strlwr.c
- src/tests/stdlib/strupr.c
- templates/x86/test/units/mods.config
Fixes #1849.
Added test cases for strlwr() and strupr() functions.
> Add tests for strupr() and strlwr()

- src/drivers/net/dwc_gmac/dwc_gmac.c
Make sure to avoid accessing TX descriptors in parallel threads with IRQ lock.
> drivers/net/dwc_gmac: Make xmit handler reentrant

- src/cmds/hardware/pin/pin.c
- src/drivers/gpio/gpio.h
- src/drivers/gpio/stm32/Mybuild
- src/drivers/gpio/stm32/stm32_gpio_conf_f3.h
- src/drivers/gpio/stm32/stm32_gpio_conf_f4.h
- src/drivers/gpio/stm32/stm32_gpio_conf_f7.h
- src/drivers/gpio/stm32/stm32_gpio_cube.c
- templates/arm/stm32f746g-discovery-lua/mods.config
- third-party/lua/lib/luasocket/Mybuild
- third-party/lua/lib/luasocket/udp_server.lua
* Add a very simple Lua example of how to toggle LEDs over the network.
* Split config for stm32 gpios because different boards have different gpio count.
On Linux:
```
$ lua5.3 echoclnt.lua 192.168.0.128 1027
Using remote host '192.168.0.128' and port 1027...
pin gpioi 1 toggle
pin gpioi 1 toggle
```
On Embox:
```
embox>lua udp_server.lua                                                        
Lua UDP server started on port 1027...
Execute 'pin gpioi 1 toggle' from 192.168.0.102:34300
Execute 'pin gpioi 1 toggle' from 192.168.0.102:34300
```
> Toggle led through Lua UDP server on stm32f7-disco

- mk/extbld/toolchain.mk
- mk/image3.mk
- src/arch/microblaze/kernel/traps_core.c
- templates/microblaze/debug/build.conf
- templates/microblaze/petalogix/build.conf
- templates/microblaze/qemu/build.conf
- templates/microblaze/test/units/build.conf
Fixes https://github.com/embox/embox/issues/1919.
Fix microblaze/qemu build by disabling linker relaxation (`--relax` option) for MicroBlaze only. The issue is here - https://github.com/embox/embox/issues/1929. Linker relaxation is a kind of target-specific optimization, so it seems to be safe to do not perform it for MicroBlaze.
> Fix microblaze build

- src/net/skbuff/skb.c
- src/net/skbuff/skb_data.c
Consider following situation: we have two `skb`, which have the same data.
If two parallel threads try to declone those `skb`, then it may result in memory leak (e.g. at first thread 1 checks that data is cloned, then thread 2 checks that data is cloned, and both checks are true as thread 1 didn't release resource yet).
This fix assures that such situation doesn't occur.
> net/skb: Fix race condition

- src/include/kernel/sched/affinity.h
- src/include/kernel/sched/runq.h
- src/include/kernel/sched/sched_timing.h
- src/include/kernel/sched/schedee_priority.h
- src/include/util/priolist.h
- src/kernel/lthread/lthread.c
- src/kernel/lthread/lthread.h
- src/kernel/sched/affinity/none.h
- src/kernel/sched/affinity/smp.c
- src/kernel/sched/affinity/smp.h
- src/kernel/sched/priority/inherit.h
- src/kernel/sched/priority/none.h
- src/kernel/sched/strategy/runq/list.c
- src/kernel/sched/strategy/runq/list.h
- src/kernel/sched/strategy/runq/list_array.h
- src/kernel/sched/strategy/runq/prioq.h
- src/kernel/sched/timing/none.h
- src/kernel/sched/timing/running_time.h
- src/net/l0/net_entry.c
Add `LTHREAD_DEF` macro, which declares lthread at compile time. Fix net_enrty as an example.
An example:
```
static LTHREAD_DEF(netif_rx_irq_handler, netif_rx_action, NETIF_RX_HND_PRIORITY);
```
> Add lthread static definition

- platform/mesa/templates/mesa_x86_osmesa/mods.config
- platform/quake3/templates/qemu/mods.config
- src/cmds/testing/keyboard_test/Mybuild
- src/cmds/testing/keyboard_test/keyboard_test.c
- src/cmds/testing/mouse_fb_test/Mybuild
- src/cmds/testing/mouse_fb_test/mouse_fb_test.c
- src/drivers/input/i8042/Mybuild
- src/drivers/input/i8042/i8042.c
- src/drivers/input/keyboard/Mybuild
- src/drivers/input/keyboard/keyboard.c
- src/drivers/input/mouse/Mybuild
- src/drivers/input/mouse/ps_mouse.c
- src/drivers/video/fb.c
- src/include/drivers/i8042.h
- templates/x86/qt-app/mods.config
- templates/x86/qt-fb/mods.config
- templates/x86/qt-vnc/mods.config
* Add mouse and keyboard simple tests.
* Fix PS/2 mouse
* Fix PS/2 mouse and PS/2 keyboard race condition and initialization order - now it doesn't matter in which order you included these modules in the config, moreover you can include only mouse or only keyboard.
To verify how these tests work, include the following modules in `x86/qemu`:
```
@Runlevel(1) include embox.arch.x86.boot.multiboot(video_mode_set=1, video_width=800, video_height=600, video_depth=16)
@Runlevel(1) include embox.driver.video.bochs
@Runlevel(1) include embox.driver.video.fb
@Runlevel(2) include embox.driver.input.keyboard.keyboard
@Runlevel(2) include embox.driver.input.mouse.ps_mouse
@Runlevel(3) include embox.init.GraphicMode
include embox.cmd.testing.mouse_fb_test
include embox.cmd.testing.keyboard_test
``` …
> Mouse and keyboard tests

- scripts/qemu/auto_qemu
- src/drivers/usb/class/Mybuild
- src/drivers/usb/class/usb_class_hid.c
- src/drivers/usb/class/usb_hid.c
- src/drivers/usb/class/usb_mass_storage.c
- src/drivers/usb/hc/ohci_pci.c
- src/include/drivers/usb/usb_hid.h
* Fix usb mouse (compilation and functioning).
* (minor) auto_qemu: Multiplex stdio and qemu monitor when running in graphical mode, so you can use qemu monitor in console (like for -nographic mode).
You can verify usb mouse on OHCI in the following way:
* Add to `x86/qemu`:
```
@Runlevel(1) include embox.arch.x86.boot.multiboot(video_mode_set=1, video_width=800, video_height=600, video_depth=16)
@Runlevel(1) include embox.driver.video.bochs
@Runlevel(1) include embox.driver.video.fb
@Runlevel(1) include embox.driver.usb.class.hid
@Runlevel(3) include embox.init.GraphicMode
include embox.cmd.testing.mouse_fb_test
```
* Run `./scripts/qemu/auto_qemu -device usb-mouse`
* `mouse_fb_test usb-mouse`. Then go to qemu graphical window, press there and move your mouse.
On wiki - …
> Fix usb mouse

- templates/arm/ti816x-qt/mods.config
- templates/arm/ti816x/mods.config
Fix after c4a96afe5cd7699dd3535534138e34272148b5ad
> templates: Fix input_test path

- src/cmds/hardware/input/Mybuild
- src/cmds/hardware/input/input.c
- src/cmds/testing/input/touchscreen/Mybuild
- src/cmds/testing/input/touchscreen/touchscreen_test.c
- src/drivers/input/input_dev.h
- src/drivers/input/touchscreen/Mybuild
- src/drivers/input/touchscreen/stm32/Mybuild
- src/drivers/input/touchscreen/stm32/stm32_cube_touchscreen.c
- src/drivers/input/touchscreen/stm32/stm32f746g_ts.h
- src/drivers/input/touchscreen/stm32/stm32f769i_ts.h
- src/drivers/input/touchscreen/touchscreen.h
- templates/arm/stm32f746g-discovery/mods.config
- templates/arm/stm32f769i-discovery/mods.config
- third-party/bsp/stmf7cube/stm32f769i/Mybuild
* Add touchscreen driver for STM32F7 (both f746g and f769i).
* Add testing command which handles touches (one or two fingers).
You can test it in the following way:
*
For STM32F746g add to `arm/stm32f746g-discovery`:
```
include embox.cmd.hw.input
@Runlevel(2) include embox.driver.input.touchscreen.stm32f746g_ts
include embox.cmd.testing.input.touchscreen_test
```
For STM32F69I add to `arm/stm32f769i-discovery`:
```
include embox.cmd.hw.input
@Runlevel(2) include embox.driver.input.touchscreen.stm32f769i_ts
include embox.cmd.testing.input.touchscreen_test
```
* In Embox:
```
embox> input                                                                     
Name        Type
stm32-ts touchscreen
embox> touchscreen_test stm32-ts
```
Expected behavior is black (first finger) and red (second …
> Stm32f7 touchscreen

- third-party/lib/openlibm/patch.txt
Fix the build error related to roundl() function by adding
mips to the list of architectures in patch file of openlibm.
Solves #1886  
> third-party: openlibm: add 'mips' in the patch file

- src/cmds/shell/tish.c
Now readline use sysalloc instead of malloc so it's required use sysfree
> cmds: Fix tish memory leak

- src/compat/posix/sys/mman/Mybuild
- src/compat/posix/sys/mman/mprotect.c
- src/tests/mem/Mybuild
- src/tests/mem/mprotect.c
The standard posix routine `mprotect()` was not
implemented before. This commit implements
`mprotect()` and closes #1815.
> compat: posix: Implement mprotect()

- src/cmds/net/ftp.c
- src/cmds/net/tftp.c
- src/compat/libc/include/stdio.h
- src/compat/libc/stdio/fopen.c
- src/compat/libc/stdio/fread.c
- src/compat/libc/stdio/fseek.c
- src/compat/libc/stdio/rename_dvfs.c
- src/compat/libc/stdio/scanf.c
- src/compat/libc/stdio/ungetc.c
- src/net/lib/dns/dns_file.c
- src/pnet/node/timer.c
I've been finding some issue with a few functions in stdio.h. Theses patches contain:
- fopen(): change mode parsing so it's complaint with POSIX. (also changes the two files which used the more carefree mode notation.
- fread(): A big issue triggered when has_ungetc is set, caused:
- useless calls to read() with size=0 (read(file->fd,buf,0).
-  the previous addition of F_EOF setup in 93ad52283 to break and set F_EOF always.
So fread() was refactored, to fix the previous issues and to return a 'short item count (or zero)' when error occurs, as POSIX states. (also adapted the few files which assumed the non-POSIX behavior).
- Clear F_EOF and F_ERR flags in all the corresponding functions. (along with some small fixes in the same functions).
- remove non-POSIX ungetchar(): It's basically …
> Refactor stdio

- platform/pjsip/templates/x86-qemu/mods.config
- third-party/pjproject/Makefile
- third-party/pjproject/sha256_error_fix.patch
Fix the problem of SIP account registration with sha256.
```
CSeq: 40584 REGISTER
Server: Flexisip/2.0.0-beta-57-gc9f98e9 (sofia-sip-nta/2.0)
WWW-Authenticate: Digest realm="sip.linphone.org", nonce="fsZS4gAAAAAMuwl4AAAt4vD7FUEAAAAA", opaque="+GNywA==", algorithm=SHA-256, qop="auth"
WWW-Authenticate: Digest realm="sip.linphone.org", nonce="fsZS4gAAAAAMuwl4AAAt4vD7FUEAAAAA", opaque="+GNywA==", algorithm=MD5, qop="auth"
Content-Length: 0
--end msg--
00:00:03.412    pjsua_acc.c  ....IP address change detected for account 0 (10.0.2.16:5060 --> 91.108.30.188:50580). Updating registration (using method 4)
00:00:03.414 sip_auth_clien  ...Unsupported digest algorithm "SHA-256"
00:00:03.415    pjsua_acc.c  ....SIP registration error: Invalid/unsupported digest algorithm (PJSIP_EINVALIDALGORITHM) …
```
> Fix pjsip sha256 registration failure

- third-party/lib/linenoise/linenoise.c
Decrease LINENOISE_MAX_LINE macro, this array is allocated on stack
> libs: Fix telnetd on stm32

- src/cmds/Blockdev.my
- src/cmds/blockdev.c
Current implementation of blockdev command lets us view the blocksize of a specified blockdevice. It also gives a report of the blocksize and total size of the overall block devices or a specified device
Rebased #1706
> cmd: Add blockdev command utlity

- src/drivers/serial/xuartlite/Mybuild
- src/drivers/serial/xuartlite/xuartlite.c
- src/kernel/time/timer/strategy/head_timer.c
- templates/microblaze/qemu/mods.config
* Fix xilinix uart implementation to be an uart, not just diag
* Add ipl locks to head timer strategy
This issue  closes partially https://github.com/embox/embox/issues/2011 - now telnet (and network) works well, but only with mmu disabled.
> Microblaze partially fix (working without mmu)

- src/tests/stdlib/Mybuild
- src/tests/stdlib/strpbrk.c
- templates/x86/test/units/mods.config
> tests: stdlib: Add unit tests for strpbrk()

- scripts/qemu/auto_qemu_with_usb_ccid
- src/cmds/hardware/ccid/Mybuild
- src/cmds/hardware/ccid/ccid_cmd.c
- src/cmds/hardware/lsusb/lsusb.c
- src/drivers/usb/class/ccid/Mybuild
- src/drivers/usb/class/ccid/ccid.c
- src/drivers/usb/class/ccid/ccid.h
- templates/x86/qemu/mods.conf
* Add CCID (host mode only).
* Add ccid_cmd to get smart card status, get ATR, and send raw command.
You can launch `./scripts/qemu/auto_qemu_with_usb_ccid` and use `ccid_cmd` to verify ccid.
> Usb ccid (host mode)

- .github/workflows/ci.yml
- scripts/continuous/touch-mk-cache.sh
In CI, Mybuild cache is prepared at the start and then distributed to testing jobs by using Actions Artifact.
There is actions/cache that is intended to cache data between runs and jobs, allows to eliminate the cache building and save time
A run from master: https://github.com/embox/embox/actions/runs/132366028
A run with actions/cache: https://github.com/embox/embox/actions/runs/133189816 (after the Mybuild cache was preparied)
* fast templates start on ~1.5 min earlier and do not take longer; first results appears after ~2min
* same for slow templates, overall run time is reduced to 14min
Downside is that earlier Mybuilds are parsed to create a cache, so cache always matched Mybilds. With this, cache is searched by hashing Mybuilds, so it's possible to get wrong cache for a set of …
> Use actions/cache in CI

- third-party/bsp/stml4cube/Makefile
- third-party/bsp/stml4cube/Mybuild
Change the download URL to
https://github.com/STMicroelectronics/STM32CubeL4/archive/v1.14.0.zip so
that the latest file can be downloaded.
Change paths in the Mybuild to solve build errors that occur due to the new version.
closes #2035
closes #2039  
> Third-party: bsp: stml4cube: Update the download URL

- src/drivers/serial/stm32_usart/stm32_usart_conf_l4.h
Solves the typo made in #2033 where f3 module was imported by mistake.
here correct module for l4 is included and it solved build errors.
> Drivers: serial: stm32: stm32l4 UART Config

- src/drivers/serial/stm32_usart/Mybuild
- src/drivers/serial/stm32_usart/stm32_usart_conf_l4.h
Add pin descriptions and IRQ details for UART2 in stm32l4 configuration
file.
This is the first step for porting Embox to Nucleo-L476RG #2034 
> Drivers: Serial: Stm32: Added support for UART2 in STM32L4

- src/drivers/serial/stm32_usart/hal_msp_l4.c
- src/drivers/serial/stm32_usart/stm32_usart_conf_l4.h
- templates/arm/nucleo_l476rg/build.conf
- templates/arm/nucleo_l476rg/lds.conf
- templates/arm/nucleo_l476rg/mods.conf
- templates/arm/nucleo_l476rg/start_script.inc
- third-party/bsp/stml4cube/nucleo_l476rg/Makefile
- third-party/bsp/stml4cube/nucleo_l476rg/Mybuild
- third-party/bsp/stml4cube/nucleo_l476rg/arch.c
- third-party/bsp/stml4cube/nucleo_l476rg/stm32l4xx_hal_conf.h
Add the BSP and template for the ST's Nucleo-l476rg Board.
This closes #2034
It builds correctly but I have to test it on the board.
> Third-party: BSP: Port Embox to Nucleo-l476rg

- src/drivers/char/char_dev_stub.h
A macro was causing build errors in the SPI driver, it has been solved
in this commit.
> Drivers: Char: Char_dev_stub: Fix build errors

- src/drivers/gpio/stm32/Mybuild
- src/drivers/spi/stm32/Mybuild
- src/drivers/spi/stm32/spi_conf_l4.h
- src/drivers/spi/stm32/stm32_spi.h
- src/drivers/spi/stm32/stm32_spi1.c
- templates/arm/nucleo_l476rg/mods.conf
- third-party/bsp/stml4cube/nucleo_l476rg/Mybuild
- third-party/bsp/stml4cube/nucleo_l476rg/stm32l4xx_hal_conf.h
Add configuration files for STM32L4 related to SPI
Make changes in HAL configurations to add SPI support
Change some other files for different reasons.
> Drivers: SPI: Add support for STM32L4

- src/arch/riscv64/kernel/entry.S
- src/arch/riscv64/kernel/interrupt.c
Fix #2064.
I thought timer initialization was not working but it was wrong.
In my previous PR(#2053), trap handler does not call interrupt handler.
So, a timer interrupt occurs after timer initialization cannot be handled and stuck(and "done" was not printed well).
> Fix riscv64 interrupt

- templates/x86/unikernel/build.conf
- templates/x86/unikernel/lds.conf
- templates/x86/unikernel/mods.conf
- templates/x86/unikernel/rootfs/network
- templates/x86/unikernel/system_start.inc
Config based on x86/qemu, optimized for httpd launch
Add -O3 to build.conf
Remove unnecessary commands from system_start.inc
Remove tests and unnecessary mods:
driver.ide, profiler.tracing, arch.x86.mmu, driver.usb.*
> templates: x86: Add httpd quick start config

- platform/pjsip/templates/stm32f746g-discovery/mods.conf
- platform/pjsip/templates/stm32f769i-discovery/mods.conf
- src/compat/posix/net/Net.my
- src/compat/posix/net/getaddrinfo.c
It was broken when trying to resolve sip.linphone.org even in previously working revisions in master. Maybe it's due to linphone changed something in their servers, I don't know for sure. But this fix helps.
> Fix pjsip templates

- src/drivers/usb/gadget/ecm/Mybuild
- src/drivers/usb/gadget/ecm/ecm_gadget.c
- src/drivers/usb/gadget/ecm/ecm_gadget.h
- src/drivers/usb/gadget/ecm/ecm_net_card.c
- src/drivers/usb/gadget/ecm/f_ecm.c
- src/drivers/usb/gadget/gadget.c
- src/drivers/usb/gadget/gadget.h
- src/include/drivers/usb/usb_defines.h
- third-party/bsp/dialog/da14695/udc/da1469x_udc.c
Add CDC-ECM (usbnet) function and gadget example:
```
@Runlevel(2) include embox.driver.usb.gadget.ecm_gadget
```
Tested only with `arm/da14695`. Also, there is a number of drawbacks labeled with TODOs, FIXMEs..
> Usb gadget cdc ethernet

- src/drivers/interrupt/cortexm/cortexm_nvic.c
- third-party/bsp/stmf3cube/arch.c
- third-party/bsp/stmf4cube/nucleo_f429zi/arch.c
- third-party/bsp/stmf4cube/stm32f4_discovery/arch.c
- third-party/bsp/stmf7cube/arch.c
- third-party/bsp/stml4cube/nucleo_l476rg/arch.c
- third-party/bsp/stml4cube/stm32l4_discovery/arch.c
> cortex-m: Remove nvic_table_fill_stubs from all platforms

- third-party/qt/Makefile
- third-party/qt/q_foreach_bug_g++9.txt
This PR fixes https://github.com/embox/embox/issues/1900 and fixes https://github.com/embox/embox/issues/2024
There is "buggy" `Q_FOREACH` in QT 4:
```cpp
#define Q_FOREACH(variable, container)                                \
for (QForeachContainer<__typeof__(container)> _container_(container); \
!_container_.brk && _container_.i != _container_.e;              \
__extension__  ({ ++_container_.brk; ++_container_.i; }))                       \
for (variable = *_container_.i;; __extension__ ({--_container_.brk; break;}))
```
It's compiled and works in different ways for gcc 8 and gcc 9. The problem here is that in GCC 8 this `break` breaks only out from the inner loop, while in GCC >= 9 it breaks out of the outer loop.
It's discussed here https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90617 …
> qt: Fix Q_FOREACH for gcc >= 9

- src/cmds/net/bootpc/bootpc.c
Set the device ip address to zero before bootp request, thus avoiding bootp reply ip packet to be forwarded.
> fixup!: cmds/net/bootpc

- src/drivers/net/stm32cube/stm32f7cube_eth.c
clean up repeated irq declaration in stm32f7 eth driver.
> drivers: stm32f7: remove duplicated irq declaration

- platform/nuklear/cmd/grfx_rawfb/Mybuild
- platform/nuklear/cmd/grfx_rawfb/grfx_rawfb.c
- platform/nuklear/cmd/grfx_rawfb/rawfb.h
- platform/nuklear/cmd/grfx_rawfb/rawfb_memcpy.c
- platform/nuklear/cmd/grfx_rawfb/rawfb_stm32_ltdc.c
- platform/nuklear/cmd/grfx_rawfb/rawfb_stm32_ltdc_alpha.c
- platform/nuklear/templates/stm32f746g-discovery/mods.conf
- platform/nuklear/templates/stm32f746g-discovery/start_script.inc
- platform/nuklear/templates/stm32f769i-discovery/mods.conf
- platform/nuklear/templates/stm32f769i-discovery/start_script.inc
- platform/nuklear/templates/x86_qemu/mods.conf
- src/drivers/dma/Mybuild
- src/drivers/dma/dma.h
- src/drivers/dma/stm32_cube/Mybuild
- src/drivers/dma/stm32_cube/stm32f7_dma.c
- src/drivers/video/stm32f7_lcd/Mybuild
- src/drivers/video/stm32f7_lcd/stm32f7_lcd.c
- templates/arm/qt-stm32f7discovery/board.conf.h
- third-party/bsp/stmf7cube/Mybuild
- third-party/bsp/stmf7cube/arch.c
- third-party/ntfs-3g/Makefile
Apply double buffering and LTDC features to optimize Nuklear rawfb example on stm32f7 up to 60 FPS.
> Nuklear optimize for stm32

- project/nuklear/cmd/grfx_rawfb/rawfb_stm32_ltdc.c
- project/nuklear/cmd/grfx_rawfb/rawfb_stm32_ltdc_alpha.c
- project/nuklear/templates/stm32f746g-discovery/mods.conf
- project/nuklear/templates/stm32f769i-discovery/mods.conf
- src/arch/arm/armmlib/cpu_cache/Mybuild
- src/arch/arm/armmlib/cpu_cache/armv7m_cpu_cache.c
- src/arch/arm/armmlib/cpu_cache/cpu_cache.h
- src/arch/arm/armmlib/cpu_cache/cpu_cache_none.h
- src/arch/arm/armmlib/cpu_cache/mpu_nocache_regions.lds.S
- src/arch/arm/cortexm3/Mybuild
- src/arch/arm/include/asm/arm_m_regs.h
- src/drivers/net/stm32cube/stm32cube_eth.c
- templates/arm/stm32f746g-discovery/mods.conf
- templates/arm/stm32f769i-discovery/mods.conf
- third-party/bsp/stmf7cube/Mybuild
- third-party/bsp/stmf7cube/arch.c
This PR aims to make the previous version of CPU caches for ARMv7-M cleaner. (it's a part of the issue https://github.com/embox/embox/issues/2016).
* Add I-Cache and D-Cache fo ARMv7-M in default write-back mode (basically for SRAM and SDRAM) with the ability to declare non-cacheable memory regions, instead of hardcoded write-through mode before.
* Use non-cacheable memory in stm32 ethernet driver
* Nuklear uses cache clean/ cache inval because it requires two frame buffers which cannot be marked as non-cachable. They were marked as write-through before, but it still requires cache invalidate.
btw, I do not enable d-cache for the stm32f7 basic templates (just add cpu cache commented) because new problems with SD card controller can arise - it uses DMA to work with Embox's block devices …
> ARMv7-M cpu cache enable

- src/drivers/serial/rpi_mini_uart/Mybuild
- src/drivers/serial/rpi_mini_uart/rpi_mini_uart.c
Mini UART is the default console device on Raspberry Pi models with
Bluetooth and WiFi. It's a NS16550-like UART. But some registers are
different. For example, we need enable manually the mini UART by
writting into <base-address> + 0x04 register.
This will help further ports for Raspberry Pi zero W, 3B, 3B+, etc.
> add: Raspberry Pi mini UART driver

- src/drivers/clock/integrator_pit/integrator_pit.c
This incorrect rate sometimes led to long nanosleep() calibration.
> drivers: Fix clock rate for integrator_pit

- mk/flags.mk
* Fix GDB corrupt stack with GCC >= 8 under QEMU by adding `-fcf-protection=none` GCC flag (more detail here https://github.com/embox/embox/issues/2054).
* Use `-fno-pic` to suppress position-independent executable code with newer GCC versions, which avoids:
```
(gdb) n
0x001a280b in __x86.get_pc_thunk.bx ()
```
> i386: Fix gdb corrupt stack under QEMU

- project/pjsip/templates/arm-qemu/mods.conf
- src/cmds/play.c
- src/drivers/audio/aaci_pl041/aaci_pl041.c
- src/drivers/audio/es1370/es1370.c
- src/drivers/audio/portaudio/Mybuild
- src/drivers/audio/portaudio/portaudio_lib.c
- third-party/pjproject/Makefile
* x86-qemu:
* Build fix
* Fix es1370
* arm-qemu build fix
* Improve audio play to handle chunks. Helps to play WAV's created with `ffmpeg -i file.mp3 file.wav` (before it was incorrect data length there)
> pjsip fix on qemu

- templates/x86/c++_demo/build.conf
- third-party/gcc/Makefile
This PR fixes GCC build for `x86/c++_demo` template. It was broken because of the install step changed in the previous gcc related PRs.
> X86 gcc build fix

- src/compat/libc/include/assert.h
- src/drivers/block_dev/ide/ide_drive.c
Improve `static_assert` and add `static_assertf` to print a message if it fails.
> Improve static assert

- src/net/l4/tcp.c
- third-party/packetdrill/sudden-close.pkt
Enable TCP timer only if required and stop the timer if there are no active TCP connections.
> tcp: Run tcp timer only if there are active connections

- src/compat/libc/math/math_builtins.c
- src/compat/libc/math/math_builtins.h
- src/compat/libc/time/Mybuild
- src/compat/libc/time/strptime.c
- src/compat/posix/include/time.h
- templates/x86/test/lang/mods.conf
- templates/x86/test/lang/start_script.inc
- third-party/duktape/Makefile
- third-party/duktape/Mybuild
- third-party/duktape/fib.js
- third-party/duktape/pkg_patch.txt
> Duktape is an embeddable Javascript engine, with a focus on portability and compact footprint.
https://github.com/svaarala/duktape
Build steps:
1. `make confload-arm/qemu`
2. Add `include third_party.cmd.duktape` to `conf/mods.config`
3. `make`
*NOTE*: `strptime` and `cbrt` are not implemented.
Run steps:
```
root@embox:/#duk ./fib.js                                                       
______
|  ____|                                            __          __
| |___  _ __ ___            ____  ____  ____  _____/ /   _____ / /
|  ___|| '_ ` _ \          / __ \/ __ \/ __ \/ ___/ /   |_____| |
| |____| | | | | |_ _ _   / /_/ / /_/ / /_/ (__  )_/    |_____| |
|______|_| |_| |_(_|_|_)  \____/\____/ .___/____(_)           | |
/_/                        \_\
ASSERTION FAILED on CPU 0
at …
```
> Add duktape

- src/drivers/virtio/virtio.h
There is a small typo in src/drivers/virtio/virtio.h.
Should read `wrong` rather than `wront`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, wront -> wrong

- src/drivers/net/stm32cube/stm32cube_eth.c
This fixes a strange situation when the ethernet starts working only after board rebooting. So now you don need to reboot your board to make the network working.
It fixes https://github.com/embox/embox/issues/2047
> drivers: Fix stm32 ethernet MAC setup

- platform/stm32/templates/f7/stm32f746g-discovery/mods.conf
- platform/stm32/templates/f7/stm32f769i-discovery/mods.conf
- src/cmds/hardware/pin/pin.c
- src/drivers/gpio/Mybuild
- src/drivers/gpio/gpio.c
- src/drivers/gpio/gpio.h
- src/drivers/gpio/gpio_driver.h
- src/drivers/gpio/omap3/omap3_gpio.c
- src/drivers/gpio/stm32/Mybuild
- src/drivers/gpio/stm32/stm32_gpio_cube.c
Fixes #2281 
You can verify gpio interrupts with `pin` command (more details here https://github.com/embox/embox/wiki/GPIO#pin-command)
> 2281 gpio input

- platform/stm32/templates/l4/nucleo_l476rg/mods.conf
Fixed system start on nucleo-l476rg (there was problem with irq_table_size, l47x have 82 interrupt channels, RM0351, p. 396). 
Also was removed char_dev_stub to avoid build error ```(Unknown):: error: Module embox.driver.char_dev extends module supertype already extended by incompatible embox.driver.char_dev_stub(conf/mods.conf:72:10)```
> fix max interrupt channels for nucleo-l476rg platform

- src/compat/libc/include/wchar.h
- src/compat/libc/wchar/Mybuild
- src/compat/libc/wchar/wcsnlen.c
- src/tests/stdlib/Mybuild
- src/tests/stdlib/wcslen.c
For simplicity of review, I have divided the PR into 2 commits.
Implements `wcsnlen()` function, which was missing in the compat layer. Referred to [this source implementation](https://android.googlesource.com/platform/bionic/+/ics-mr0/libc/wchar/wcsnlen.c)
Adds test case to test if `wcslen()` and `wcsnlen()` works correctly. Used the template from test in `stdlib/strlen.c`
> Added support for wcsnlen() in wchar module

- src/tests/stdlib/strlen.c
Earlier the strlen test cases, didn't use `strlen()`, rather only `strnlen()`. Changed it as dicussed with @alexkalmuk 
I had to update the commit message to include issue number, so had to force push :0
Edit: It failed on `x86/smp` platform, don't see the reason behind this.
> Updated strlen test cases to also test strlen() and not only strnlen()

- src/tests/string/Mybuild
- src/tests/string/strcat_test.c
- src/tests/string/strncat_test.c
- templates/x86/test/units/mods.conf
This PR implements tests for the `strcat` and `strncat` functions.
Fixes #1852.
> Add tests for the strcat and strncat functions

- project/opencv/lib/Mybuild
- project/opencv/lib/cv_embox_imshowfb.cpp
- project/opencv/lib/cv_embox_imshowfb.hpp
It's an analogue of `imshow`, which draws image directly to the framebuffer instead of a graphical window.
> opencv: Add imshowfb

- mk/extbld/arch-embox-gcc
Fix duplicating CPPFLAGS passed to third-party apps. Also, fix the order of CPPFLAGS and CFLAGS.
> Fix duplicating cppflags in extbld

- mk/gen_ld_section_symbols.sh
- mk/gen_sections_c.sh
- mk/script/build/oldconf-gen.mk
- project/opencv/cmds/Mybuild
- src/mem/Mybuild
- src/mem/loadsect/Mybuild
- src/mem/loadsect/loadsect.c
- src/mem/phymem.c
When you define linker sections in lds.conf like:
```
/* OpenCV */ 
section (cv_text, QSPI, QSPI)
phdr    (cv_text, PT_LOAD, FLAGS(5))
section (cv_rodata, QSPI, QSPI)
phdr    (cv_rodata, PT_LOAD, FLAGS(5))
section (cv_data, RAM, QSPI)
phdr    (cv_data, PT_LOAD, FLAGS(6))
section (cv_bss, RAM, QSPI)
phdr    (cv_bss, PT_LOAD, FLAGS(6))
```
these sections can be automatically loaded to the specified memories (e.g. to QSPI, SDRAM, RAM) if you specify
```
@Runlevel(1) include embox.mem.loadsect
```
in mods.conf
> Add loadsect module to automatically load sections in external memory

- mk/build.mk
- mk/image.lds.S
- mk/script/build/build-gen.mk
- mk/script/lds-apps.mk
- src/arch/usermode86/Mybuild
- src/arch/usermode86/apps.lds.S
- src/framework/mod/Mybuild
- templates/usermode86/debug/mods.conf
- templates/x86/test/ping-target/mods.conf
Combining module's/app's sections into a single one (that's what lds-apps.mk does) is only correct at the final linking when we get a non-relocatable object file. At the earlier stages attempts to perform such a linkage on a relocatable object file may lead to undefined behaviour.
> buildsystem: Move apps sections generation to the final stage

- mk/variables.mk
> mk: Fix md5sum output format on MacOS

- src/drivers/video/Mybuild
- src/drivers/video/raspi_video.c
fix memory mapping mode for pi zero on qemu
move parameters to MyBuild and add brief description
fix for bug #2453
> fb_direct_access fails for platform/raspberry_pi/rpi0 #2453

- platform/raspberry_pi/cmds/Mybuild
- platform/raspberry_pi/cmds/jtag.c
- platform/raspberry_pi/drivers/jtag/Mybuild
- platform/raspberry_pi/drivers/jtag/jtag.c
- platform/raspberry_pi/drivers/jtag/jtag.h
- platform/raspberry_pi/rpi0/mods.conf
- src/arch/arm/armlib/boot/reset_handler.S
- src/arch/arm/head.S
- src/arch/arm/include/asm/delay.h
- src/arch/arm/include/asm/modes.h
- src/arch/arm/lib/delay/Mybuild
- src/arch/arm/lib/delay/delay.S
- src/drivers/gpio/bcm283x/Mybuild
- src/drivers/gpio/bcm283x/bcm283x_gpio.c
- src/drivers/gpio/bcm283x/bcm283x_gpio.h
- src/drivers/interrupt/raspi_intc/raspi.c
- src/drivers/video/Mybuild
Adding GPIO support for RaspberryPi Zero (unit tested on) but also likely works for Pi 1, Pi B, ... (BCM283x) models.
Added option to enable configuration for JTAG debugger.
Added a command to call JTAG config for GPIO pins and output pin configuration for the 40-pin header.
Also, reverted an earlier change for default memory address for the frame buffer.  This could be a QEMU bug but text has been added to explain how one value works with QEMU and the other value works with an actual physical device.
This PR relates to ticket #2459
> add PiZero GPIO output, add comments for frame buffer, add JTAG command

- platform/raspberry_pi/rpi0/mods.conf
- src/arch/arm/Mybuild
- src/arch/arm/head.S
This is a non-critical change as it only executes on start-up.  With memory virtualization on (I think it is off now?) the memory copy could be faster in page swapping.
But, as you say, if this STMIA isn't supported on some sub-architectures, that becomes a pain to support unless it really has value. (Anybody want to test this?)
Regardless, it is here for your amusement.
> modify memory clear for faster execution, skip unnecessary memory copies

- scripts/qemu/start_script
The previous version could return two default gateways, so we need to pick the right (I decided it will be the first) one.
P.S. starting qemu fails later because of weird message `qemu-system-i386: Error loading uncompressed kernel without PVH ELF Note`, but it is very likely a separate issue
> Fix detection of default tunnel on QEMU startup

- src/lib/bmp/bmp.c
I realize it probably doesn't matter at all since nobody uses 16bpp BMPs, 
but for the love of God...
> Correctly close file descriptor on failure

- platform/raspberry_pi/rpi0-hw/mods.conf
- src/cmds/hardware/spi/Mybuild
- src/cmds/hardware/spi/spi.c
- src/drivers/mailbox/bcm2835_mailbox_property.c
- src/drivers/mailbox/bcm2835_mailbox_property.h
- src/drivers/spi/bcm283x/Mybuild
- src/drivers/spi/bcm283x/bcm283x_spi0.c
- src/drivers/spi/bcm283x/bcm283x_spi0.h
- src/drivers/spi/spi.h
SPI polling and interrupt are supported now in this PR.  Also incorporated all of your suggestions from last review.
SPI command incorporates interrupt tests, default data, and mode switch tests.  There is an interrupt wait for input test but it seems to have a rather short wait time before reporting zero value bytes received.  Don't have a use case for this right now, so will leave it at that.
Maybe somebody else will extend support in stm32 targets for selecting Mode 1/2/3 or interrupts?
> add support for spi (poll and interrupt) for bcm2835

- mk/extbld/lib.mk
corrected mk/extbld/lib.mk to check md5sum only for source archives and skip the check for git repos.
> mk/extbld/lib.mk: check md5sum only for source archives and skip the check for git repos

- platform/raspberry_pi/rpi0-hw/mods.conf
- src/cmds/hardware/spi/Mybuild
- src/cmds/hardware/spi/spi.c
- src/drivers/spi/bcm283x/Mybuild
- src/drivers/spi/bcm283x/bcm283x_spi0.c
- src/drivers/spi/bcm283x/bcm283x_spi0.h
- src/drivers/spi/spi.c
- src/drivers/spi/spi.h
Here is DMA supported transfers with SPI (and likely other devices).
There is still a bug with the DMA completion.  The test is configured to trigger an interrupt but it is not firing.  So, the busy wait loop is also polling until DMA is completed.
I'm thinking it is still worthy of sharing.  A smaller update can follow with fixing that.  (I did having it working at one point but something has changed .. possibly panic levels or mid to high water marks).
Regardless, all bytes transfer as expected.
> Bcm spi dma

- third-party/lib/curl/Mybuild
`gmtime` provided by `embox.compat.posix.time.time` is required for `Curl_gmtime`.
> third-party: fix curl deps

- src/drivers/usb/hc/ohci/ohci_pci.c
fixed #1960 
It seems a 'reset' has been needed.
> drivers: Fix work when usb-net & usb-ms work together

- src/arch/mips/kernel/arch.c
> arch: Add 'wait' instruction into arch_adle for MIPS

- src/arch/x86/embox.lds.S
> x86: Add region for multiboot section in arch/x86/embox.lds.S

- src/tests/string/Mybuild
- src/tests/string/memchr_test.c
- src/tests/string/memrchr_test.c
This PR implements some test cases for the ```memchr``` and ```memrchr``` functions.
Fixes #1850
> Add tests for the memchr and memrchr functions

- README.md
The `-no-kvm` option was [removed](https://github.com/qemu/qemu/blob/master/docs/about/removed-features.rst#-no-kvm-removed-in-52) in qemu version 5.2
> Updated flags for debugging

- src/arch/msp430/include/asm/limits.h
- src/compat/libc/include/limits.h
- src/include/asm-generic/limits32.h
SCHAR_MIN and SHCAR_MAX have [incorrect](https://learn.microsoft.com/en-us/cpp/cpp/integer-limits?view=msvc-170) value
> Changed SCHAR_MIN and SCHAR_MAX constant

- src/kernel/task/idesc/index_descriptor.c
On Linux `fcntl` with F_SETFL can [change](https://linux.die.net/man/2/fcntl) only the O_APPEND, O_ASYNC, O_DIRECT, O_NOATIME, O_NONBLOCK flags.
In [Linux](https://github.com/torvalds/linux/blob/master/fs/fcntl.c) `SETFL_MASK = (O_APPEND | O_NONBLOCK | O_NDELAY | O_DIRECT | O_NOATIME)`. 
O_NOATIME is not defined in Embox
> Changed operation fcntl with F_SETFL flag

- third-party/efm/Makefile
- third-party/efm/Mybuild
There is a corrected path to the efm sources in the thirdparty/efm/Makefile now.
> third-party: efm: changed the path to the sources archive

- platform/stm32/f7/stm32746g_discovery/Mybuild
- platform/stm32/f7/stm32f769i_discovery/Mybuild
- third-party/bsp/stmf7cube/components/Mybuild
- third-party/bsp/stmf7cube/cube/Makefile
- third-party/bsp/stmf7cube/cube/Mybuild
- third-party/bsp/stmf7cube/middlewares/Mybuild
- third-party/bsp/stmf7cube/utilities/Mybuild
third-party\bsp\stmf7cube\cube\Mybuild:
changed version 1.16.0 to 1.17.0
third-party\bsp\stmf7cube\cube\Makefile:
commented out code related to 1.16.0, uncommented code for 1.17.0
third-party\bsp\stmf7cube\components\Mybuild
changed version 1.16.0 to 1.17.0
platform\stm32\f7\stm32746g_discovery\Mybuild
changed version 1.16.0 to 1.17.0.
platform\stm32\f7\stm32f769i_discovery\Mybuild
changed version 1.16.0 to 1.17.0.
third-party\bsp\stmf7cube\utilities\Mybuild
changed version 1.16.0 to 1.17.0.
third-party\bsp\stmf7cube\middlewares\Mybuild
changed version 1.16.0 to 1.17.0.
> stmf7cube: updated to version 1.17.0

- scripts/gdb_load_stm32.sh
- src/drivers/input/input_dev_devfs.c
This is simple script to check if current config has QSPI. If it has no SPI, then it can be loaded to the board with simple GDB command
> Issue 2665 fix stm32 qt

- src/compat/libc/math/Mybuild
- src/compat/libc/math/exp.c
- src/compat/libc/math/math_builtins.h
1. Added file src\compat\libc\math\exp.c with implementation for exp function.
2. Added extern definition for exp function to src\compat\libc\math\math_builtins.h.
3. Updated embox.compat.libc.math_simple module in src\compat\libc\math\Mybuild with addition of: source "exp.c" statement.
> add-exp-to-math

- src/compat/libc/stdlib/sysconf.c
- src/compat/posix/include/unistd.h
1. Added #define _SC_OPEN_MAX (The maximum number of open files per process) with minimum value 20 to src\compat\posix\include\unistd.h file.
2. Updated switch statement in src\compat\libc\stdlib\sysconf.c file with added case statement for _SC_OPEN_MAX.
> add-_SC_OPEN_MAX-to-unistd-h

- project/paho_mqtt_cpp/templates/arm_qemu/mods.conf
- project/paho_mqtt_cpp/templates/arm_qemu/paho_mqtt_cpp_publish.inc
- project/paho_mqtt_cpp/templates/arm_qemu/paho_mqtt_cpp_subscribe.inc
- project/paho_mqtt_cpp/templates/arm_qemu/system_start.inc
1. Updated project/paho_mqtt_cpp/templates/arm_qemu/mods.conf: 1.1. added networking modules (udp modules can be removed for mosquitto client) 1.2. added embox.compat.posix.idx.select module
2. Updated project/paho_mqtt_cpp/templates/arm_qemu/system_start.inc. Added: 2.1. "netmanager"
2.2. "service telnetd"  - (why is it needed?)
2.3. "service httpd" - (why is it needed?)
2.4. "stl_demo_sort1" - (why is it needed?)
3. Added two configuration files: 3.1. project/paho_mqtt_cpp/templates/arm_qemu/paho_mqtt_cpp_publish.inc with
3.1.1. MQTT_SERVER_ADDRESS     "tcp://10.0.2.10:1883"
3.1.2. MQTT_SERVER_TOPIC       "hello"
3.2. project/paho_mqtt_cpp/templates/arm_qemu/paho_mqtt_cpp_subscribe.inc with
3.2.1. MQTT_SERVER_ADDRESS     "tcp://10.0.2.10:1883"
3.2.2. MQTT_SERVER_TOPIC       "hello"
> fix build for confload-project/paho_mqtt_cpp/arm_qemu

- src/lib/debug/Mybuild
- src/lib/debug/ubsan.c
- templates/x86/qemu/build.conf
- templates/x86/qemu/mods.conf
Output in qemu for x86/debug template:
```
...
unit: initializing embox.driver.tty.serial: done
pci: Apple OHCI usb host driver inserted
UbSan shift out of bounds /home/dde/src/embox/src/mem/vmem/mapper.c:26
UbSan shift out of bounds /home/dde/src/embox/src/mem/vmem/mapper.c:26
UbSan shift out of bounds /home/dde/src/embox/src/mem/vmem/mapper.c:26
UbSan shift out of bounds /home/dde/src/embox/src/mem/vmem/mapper.c:26
UbSan shift out of bounds /home/dde/src/embox/src/mem/vmem/mapper.c:26
UbSan shift out of bounds /home/dde/src/embox/src/mem/vmem/mapper.c:26
UbSan shift out of bounds /home/dde/src/embox/src/mem/vmem/mapper.c:26
UbSan shift out of bounds /home/dde/src/embox/src/mem/vmem/mapper.c:26
UbSan shift out of bounds /home/dde/src/embox/src/mem/vmem/mapper.c:26
UbSan shift out of …
```
> lib/debug/ubsan: Initial implementation

- src/cmds/testing/block_dev/block_dev_test.c
m_blocks is derived from user input (a command-line argument). If m_blocks is large enough, the multiplication to calculate malloc() size could overflow.
> cmds: Fix integer overflow involving m_blocks

- src/cmds/net/tftp/tftp.c
- src/drivers/serial/uart_dev.c
fwrite() returns a size_t, which means that 0 > fwrite(...) will never hold.
Similarly, the type of uart->idx is unsigned char. Thus, the comparison uart->index < 0 is always false.
> Fix comparisons that are always false

- src/include/mem/phymem.h
- src/mem/phymem.c
A 'const' modifier on a function return type is useless and should be removed for clarity.
> mem: Remove 'const' modifier on a function return type

- src/drivers/gpio/gpio.h
define `GPIO_MODE_OUT ` used 16th bit, but `GPIO_MODE_OUT_SECTION` allow to use only 15-8 bit. PR is fixing that.
> fix wrong bit in GPIO_MODE_OUT

- src/compat/libc/string/Mybuild
- templates/arm/qemu/build.conf
It looks like gcc has a bug, and 'stpcpy' function name is a problem 🤷
This function is not used in the OS itself, so just extract it to a separate module, and it works fine
Minimal example to reproduce this bug:
```
> cat stpcpy.c
char *stpcpy(char *, const char *) {
return 0;
}
> arm-none-eabi-gcc -fsanitize=undefined -c -o stpcpy.o stpcpy.c -save-temps
stpcpy.s: Assembler messages:
stpcpy.s:52: Error: expected comma after name `' in .size directive
```
> Ubsan compilation

- third-party/lib/acpica/Mybuild
third-party: -fno-sanitizer=undefined flag for acpica to silence UBSan
During boot time output is stuffed with UBSan output. Temporary shutdown undefined behavior tracking to silence sanitizer. Probably needs a clean fix in the future
> third-party: -fno-sanitizer=undefined flag for acpica to silence UBSan

- scripts/autotest/testsuite/net/rlogin/test.exp
Added rlogin test to autotest system, however not to much automated
Rlogind has to be running on the host and test needs the user to provide username and password for rlogind
Further improvements needed
> autotest: rlogin test added

- src/cmds/shell/Mybuild
- src/cmds/shell/tish.c
- templates/x86/test/lang/mods.conf
Fix #2263
In linux bash, `sh_unset_nodelay_mode()` is called when bash starts. There `fcntl` is called. Also in interactive mode if cmd sets `O_NONBLOCK` to stdin, bash unsets it before next cmd call.
Now `x86/test/lang` works correctly
> Enable tish read from keyboard correctly

- mk/flags.mk
--debug-prefix-map was being used which worked, but according to gcc documentation should have been -fdebug-prefix-map
It is used to substitute the absolute pathnames to source files connected with debug symbols with relative to the root directory of embox. 
Arguments are now passed in more correct manner ("-fdebug-prefix-map=\`pwd\`=." instead of "--debug-prefix-map=\`pwd\`="). In previous version debug information about pathnames was ending up in the relative path looking like absolute (for instance /src/some/command.c instead of ./src/some/command.c) which gdb successfully (and smartly) parsed, but some gdb plugins (nvim-gdb for instance) would find invalid, ending up in not finding the source.
Some code for easier switching off of this flag also added. If you need debug information …
> makefile: -fdebug-prefix-map with correct argument

- src/cmds/shell/shell.c
- src/compat/posix/proc/exec.c
One probable scenario: after execv gained ability to return back when executable couldn't be found, an issue in dropbear that otherwise wouldn't have come up, showed itself. On connection dropbear executes '/bin/sh/' which execv answered is unavailable, after which dropbear came to a series of unfortunate events, which need further investigation, and embox laid down flat.
Hardlinking /bin/sh to tish solved that problem(at least temporary).
Additional check in execv, fixing previous commit, added.
> shell:hardlink /bin/sh for dropbear. execv add chk

- templates/x86/test/net/mods.conf
In x86/test/net template configuration environment structure for a task(struct task_env) had default env_str_len value equal to 32. Because of that new version of dropbear crashed trying to write long environment variable.
> templates: x86/test/net templ fix(ci crashed)

- src/cmds/sys/date.c
Fix https://github.com/embox/embox/issues/2492
```
date -s 202307251757.40
date -s 202301251757.40
date -s 202312251757.40
date -s 202307301757.40
date -s 202307311757.40
date -s 202307321757.40
```
```
2023-07-25 17:57:40
2023-01-25 17:57:40
2023-12-25 17:57:40
2023-07-30 17:57:40
2023-07-31 17:57:40
2023-08-01 17:57:40
```
> date: In set_date() read correct tm_mon field

- scripts/continuous/prepare.sh
- scripts/continuous/run.sh
- scripts/continuous/touch-mk-cache.sh
- scripts/continuous/tsim_run.sh
Hi @anton-bondarev
This PR offers double-quoting mostly, but also it has a couple of changes which possibly can change code semantics.
Here I've added an extra case when default variable value is used:
```diff
-TIMEOUT=${CONTINIOUS_RUN_TIMEOUT-60}
+TIMEOUT=${CONTINIOUS_RUN_TIMEOUT:-60}
```
Explanation in Bash manual:
>When not performing substring expansion, using the form described below (e.g., ‘:-’), Bash tests for a parameter that is unset or null. Omitting the colon results in a test only for a parameter that is unset. Put another way, if the colon is included, the operator tests for both parameter’s existence and that its value is not null; if the colon is omitted, the operator tests only for existence. 
Here I renamed a variable to make its name reflect its purpose and also changed …
> Fix continuous/* shell-scripts according to ShellCheck

- templates/x86/test/net/mods.conf
Clean out x86/test/net template of old modules hindering vfork functioning. Because of them Dropbear in multi-process mode didn't function properly
> templates: x86/test/net mods.conf-vfork depr mods

- src/compat/posix/idx/tests/Mybuild
- src/compat/posix/idx/tests/pipe_close_notify_test.c
Although POSIX doesn't seem to pose it directly, we find that third-party programs might be relying on it. As it happens in case of dropbear. Linux man page on select() do mention, that on end-of-file readfs descriptors in select() should be ready to read. So it might be a good idea to stick to it.
This test should pass in case select()'s readfs descriptors are notified on close() event
> test: pipe() close should notify read-end

- src/compat/posix/idx/tests/pipe_close_notify_test.c
More correct result interpretation and a minor naming typo correction
> test: pipe close() test more correct interpretation

- scripts/disk/img2vdi.sh
- scripts/disk/make_img.sh
- scripts/disk/partitions.sh
Hi @anton-bondarev!
As the name of PR states it changes files in `scripts/disk` folder. The file `partitions.sh` has the majority of changes while others mostly have two or three lines changed. Below I will comment on some parts from `partitions.sh`
```diff
-PARTS=$2 
-FS=$3
-SIZE=$4
+PARTS=${2:-4}
+FS=${3:-fat}
+SIZE=${4:-128}
-[ "$PARTS" == "" ] && PARTS=4
-[ "$FS" == "" ] && FS="fat"
-[ "$SIZE" == "" ] && SIZE=128
```
I've replaced explicit check-and-assignment of default values with parameter expansion feature
>${parameter:-word}
>
>    If parameter is unset or null, the expansion of word is substituted. Otherwise, the value of parameter is substituted. 
>(https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html)
Simplified bounds-check:
```diff
-if [[ ! …
```
> Fix disk/* shell scripts according to ShellCheck

- scripts/autotest/run.sh
Hi @anton-bondarev! This PR continues the series of PRs related to #2835. It introduces a lot of changes in a single file:
1. Adds comments here and there
2. Rewrites listing of testsuites and testcases. Original approach used global variables to initialize and store lists of testsuite and testcase names which in turn were printed out by special functions. Thus these functions depended heavily on global state. I've tried to reduce this dependence and moved all listing logic into the body of this functions. So this
```diff
-TESTSUITE_LIST=$(ls $TESTSUITE_DIR)
```
has moved here
```diff
show_available_testsuites() {
echo "Available testsuites:"
-       echo $TESTSUITE_LIST
+       ls "$TESTSUITE_DIR"
}
```
And this
```diff
-TESTCASE_DIR=
-TESTCASE_LIST=
… …
```
> Refactor autotest/run.sh

- scripts/ld_map_info.sh
- scripts/usermode_start.sh
Hi @anton-bondarev! Yet another PR in the series. 
Changes are not very complicated:
1. Wrapping in double quotes here and there
2. Simpler condition in `usermode_start.sh`:
```diff
-if [ ! -z "$(ip addr | grep $TAP)" ]; then
+if ip addr | grep -q "$TAP"; then
```
This is direct check if `ip addr` contains `$TAP` — `grep -q` terminates on first match with zero exit-code.
3. Extensive comments on embedded AWK scripts in `ld_map_info.sh`.
> Fix ld_map_info & usermode_start according to ShellCheck

- third-party/dropbear/Makefile
- third-party/dropbear/dropbear-mpr.patch
After #2873 fixed pipe close notification, return to the dropbear original authentication success notification method by closing corresponding pipeline
> third-party: dropbear: original auth notif. method

- scripts/docker/container/bin/gdbwrapper2
- scripts/docker/container/bin/killgdbwrapper
- scripts/docker/docker_start.sh
- scripts/docker/gdbhostwrapper
Hi @anton-bondarev!
As usual, most of the changes is wrapping variables containing paths in double quotes and also
1. Checking the exit-code of a command directly
```diff
-       mount | grep -q $PROJECT_LOC
-       if [ $? != 0 ]; then
+       if ! mount | grep -q "$PROJECT_LOC"; then
```
2. Removing obsolete trick (https://www.shellcheck.net/wiki/SC2268)
```diff
-if [ x0 = x$started ]; then
+if [ 0 = $started ]; then
```
3. Removing useless command substitution. There is no need to catch `pwd`'s output and pass it as argument to `echo`. We can use `pwd`'s output as is.
```diff
-       (cd "$1" && echo "$(pwd -P)")
+       (cd "$1" && pwd -P)
```
> Fix shell scripts in scripts/docker according to ShellCheck

- scripts/gdb_erase_stm32h7.sh
- scripts/gdb_load_stm32.sh
- scripts/gdb_run_stm32f7_qspi.sh
- scripts/gdb_run_stm32h7_qspi.sh
Hi @anton-bondarev! Another portion of the #2835. This PR is about `gdb*.sh` scripts.
Changes are of two types:
1. Wrapping in double quotes the variables containing paths 
2. Replacing patterns like this:
```bash
echo "…" >> some-file
echo "…" >> some-file
echo "…" >> some-file
```
with group commands:
```bash
{
echo "…"
echo "…"
echo "…" 
} >> some-file
```
It gives the same result but looks cleaner (an example of group command's output redirect and pipelining: https://onlinegdb.com/7dQabeEcoF).
These changes don't modify code semantics, so I think there is no need to check the scripts with real hardware.
> Fix gdb* scripts according to ShellCheck

- scripts/mqtt/auto_qemu
- scripts/mqtt/qemu_with_disk.sh
- scripts/mqtt/up_bridge.sh
Hi @anton-bondarev! Another piece related to #2835 
Changes are:
1. Wrapping variables in double quotes
2. Rewriting if-conditions to check exit codes directly, e.g.:
```diff
-               dmesg | tail | grep "kvm: disabled by bios" > /dev/null
-               if [ $? -eq 0 ]; then
+               if dmesg | tail | grep -q "kvm: disabled by bios"; then
```
3. Removing unused variables
> Fix mqtt/* shell scripts according to ShellCheck

- scripts/codestyle/format_files.sh
- scripts/codestyle/install_uncrustify.sh
- scripts/codestyle/run_uncrustify.sh
- scripts/codestyle/travis_uncrustify.sh
Hi @anton-bondarev! Another part of #2835. This PR:
1. Quotes variables in paths, links and echo args to protect them from globbing and word splitting
2. Rewrites loop with reading a file line by line instead of cat'ing its contents into variable
```diff
-files=$(cat $1)
-
-for item in $files ; do
-
-       dn=$(dirname $item)
-       mkdir -p out/$dn
-       uncrustify -f $item -c uncrustify_cfg.ini > out/$item
-
-done
+while read -r item;
+do
+       dn=$(dirname "$item")
+       mkdir -p "out/$dn"
+       uncrustify -f "$item" -c uncrustify_cfg.ini > "out/$item"
+done < "$1"
```
3. Rewrites implicit arrays-of-strings-to-string conversion with explicit array expansion
```diff
-diffargs="$@"
+diffargs=( "$@" )
…
-git diff --no-prefix $diffargs …
+git diff --no-prefix "${diffargs[@]}" … …
```
> Fix codestyle/*.sh according to ShellCheck guidelines

- src/compat/posix/curses/curses.c
This PR  closes #2405 by removing a do-nothing block from `curses.c`
> posix/curses: Remove do-nothing block

- scripts/autotest/testsuite/modbus/modbus_bits_read/test.exp
timeout got missing in previous commit
> autotest: add missing timeout for modbus autotest

- src/include/net/l4/tcp.h
- src/net/l4/tcp.c
- src/net/socket/tcp_sock.c
Dynamic allocation of sockets in backlog queue. Still needs further testing, but at the moment seems to work more or less fine.
Minor addition - in tcp.c layer added TCP_PRINT_STATE_INFO define, just in case one would like to see how states are changed in tcp sockets, for debugging purposes, decided to keep it, might be handy in the future.
> net: TCP dynamic alloc of sockets for backlog queue

- scripts/autotest/testsuite/modbus/modbus_bits_read/test_client/mb_test_client.c
- src/tests/net/inet_stream_socket_test.c
On of the sock_stream tests hung an unclosed socket, close() added
In modbus test client output formatting slightly changed
> tests: Minor changes to net tests

- src/net/socket/tcp_sock.c
There was no check for having new socket successfully allocated. When the pool is empty leads to crash
> net: TCP dynamic backlog alloc critical addition

- src/net/l4/Mybuild
- src/net/l4/tcp.c
Socket may be stuck in FINWAIT_2 state waiting for fin from the remote host forever, so although it violates specification, seems reasonable to have timeout for it
Anyway it is possible to set timeout option in Mybuild to 0, so that it will wait for fin forever
> net: tcp FINWAIT2 state timeout added

- platform/stm32/templates/f4/nucleo_f410rb/build.conf
- platform/stm32/templates/f4/nucleo_f410rb/lds.conf
- platform/stm32/templates/f4/nucleo_f410rb/mods.conf
**platform/stm32/f4/nucleo_f410rb:** `(template)` Fix non-working out-of-box config template for `nucleo_f410rb`
> fix stm32/nucleo_f410rb template

- platform/stm32/templates/f4/nucleo_f410rb/mods.conf
Add ticker command to stm32/nucleo_f410rb template, also add some compat.libc stuff and static heap
> Improve stm32/nucleo_f410rb template - add ticker command and heap

- src/cmds/sys/time/Time.my
Fix time.my depends on `embox.compat.libc.stdlib.system` because time.c uses `system()`
> fix Time.my depends

- src/compat/libc/stdio/fflush.c
fflush(0) is absolutely valid invocation and it means "flush all output streams". Since embox does not track output streams right now, it takes some effort to implement it properly. But at least it should not dereference NULL.
fflush(0) is heavily used in iperf third-party tool.
> Fix NULL pointer dereference in fflush()

- src/drivers/tty/serial/ttys_term.c
- src/drivers/tty/tty.c
- src/include/drivers/tty.h
workaround for tty device not cause shutdown if it tries to setup several times
> tty: add workaround fix in tty_ioctl()

- scripts/continuous/fs/run.sh
This pull-request should fix failure of the test/fs template in CI when testing cifs file system, that appeared after improving the behavior of inet_*ton functions. The assumption that failure is caused by erroneous colon in mount command for cifs file system in scripts/continuous/run.sh
> template: CI test/fs template cifs fix

- src/arch/riscv/include/asm/entry.h
- src/arch/riscv/include/asm/interrupts.h
- src/arch/riscv/include/asm/regs.h
- src/arch/riscv/kernel/Mybuild
- src/arch/riscv/kernel/boot.S
- src/arch/riscv/kernel/context.c
- src/arch/riscv/kernel/context_switch.S
- src/arch/riscv/kernel/entry.S
- src/arch/riscv/kernel/exception.h
- src/arch/riscv/kernel/interrupt.c
- src/arch/riscv/kernel/ipl_impl.c
- src/drivers/clock/riscv_clk/riscv_clk.c
- src/drivers/interrupt/riscv_plic/Mybuild
- src/drivers/interrupt/riscv_plic/riscv_plic.c
- templates/riscv64/qemu-smode/build.conf
- templates/riscv64/qemu-smode/lds.conf
- templates/riscv64/qemu-smode/mods.conf
- templates/riscv64/qemu-smode/system_start.inc
Add support for building embox for running in S mode
Tested with OpenSBI under `virt` platform in QEMU
Exact command: `qemu-system-riscv64 -nographic -M virt -kernel embox`
> riscv: Add support for S mode

- src/cmds/fs/mkramdisk/mkramdisk.c
Fixed error handling in mkramdisk command
If system has no available memory for ramdisk, ramdisk_create function will return an error code, which will be used as address of ram disk, which is incorrect.
This patch fixes this problem, now error code is being extracted and checked, before any actions made with ram disk.
> Fixed mkramdisk cmd error handling

- src/drivers/serial/uart_dev/uart_dev.h
Macros for creating uart param mask from uart_param_flags produce incorrect masks since they first extract lower bits of flags and shift them, but they should create mask by shifting necessary bits and only then extract bits from flags
Test program to illustrate the problem
```
#include <uart_dev.h>
#include <stdio.h>
int main() {
struct uart_params params = {
.baud_rate = 9600,
.uart_param_flags = UART_PARAM_FLAGS_PARITY_NONE | UART_PARAM_FLAGS_HWCRTL_RTS |
UART_PARAM_FLAGS_2_STOP | UART_PARAM_FLAGS_8BIT_WORD | UART_PARAM_FLAGS_DEV_TYPE_RS485,
};
printf("Parity: Expected 0x%x, got 0x%x\n", UART_PARAM_FLAGS_PARITY_NONE, UART_PARAM_FLAGS_PARITY_MASK(params.uart_param_flags));
printf("Hwctrl: Expected 0x%x, got 0x%x\n", UART_PARAM_FLAGS_HWCRTL_RTS, …
```
> Fix uart param flags macros (wrong order of operations)

- src/compat/posix/util/environ.c
Now if user tries to add a variable without name,
system will print an error message
> Added message on incorrect input for export cmd

- templates/x86/test/units/mods.conf
Modules that cause compilation errors are commented out in mods.conf
> Fix build templates/x86/test/units on gcc (GCC) 13.2.1 20230801

- README.md
In 2022 Arch removed python2 from its repository.
I suggest to install precompiled python2 from yay.
I also updated the corresponding lines in the Wiki's Quick Start.
> docs: Add python2 installation for Arch in README

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/math_test_abs.c
- templates/aarch64/qemu/mods.conf
This solves issue #3266 and enable two math.h tests on aarch64 platform.
> test: add unit test for abs in math.h

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/math_test_ceil.c
- templates/aarch64/qemu/mods.conf
- templates/x86/test/units/mods.conf
Added unit tests for ceil() in `libc/math/tests`. Closes #3269
> TST: Add test for ceil() in libc tests

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/atan_tests.c
- templates/x86/test/units/mods.conf
This test module is also added to the x86 template
closes #3268
> Add unit-tests for atan() functions (math.h) 

- mk/extbld/toolchain.mk
When compiling the pjsip project,the -MMD -MP flags was interpreted as an error.
Resolve:#3287,#3258
> mk: extbld: Fix imported flags

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/fabs_tests.c
- src/compat/libc/math/tests/floor_tests.c
- src/compat/libc/math/tests/round_tests.c
- src/compat/libc/math/tests/tanh_tests.c
- templates/x86/test/units/mods.conf
Added test cases to tanh(), round(), floor() and fabs() as per issues #3337 , #3336 , #3331 and #3330 respectively. 
After adding test cases also added them in the Mybuild inside `src/compat/libc/math/tests/Mybuild` as per the sqrt_tests.
Then to test I added these in mods.conf (this is not included in the commit as I assumed the master won't include them)
```
@Runlevel(1) include embox.compat.libc.test.round_tests
@Runlevel(1) include embox.compat.libc.test.fabs_tests
@Runlevel(1) include embox.compat.libc.test.floor_tests
@Runlevel(1) include embox.compat.libc.test.tanh_tests
```
And when I build `make` and run `./scripts/qemu/auto_qemu` I see all the tests pass.
Below is the screenshot showing that.
This is my first issue, if anything more is required like if the test cases are not …
> Added tests for math.h fabs, floor, round and tanh

- src/drivers/interrupt/riscv_clint/Mybuild
- src/drivers/interrupt/riscv_clint/riscv_clint.c
- src/drivers/interrupt/riscv_clint/riscv_clint.h
This PR introduces the implementation of the RISC-V Core Local Interruptor (CLINT) for interrupt control and timer management. By referring to this [**document**](https://chromitem-soc.readthedocs.io/en/latest/clint.html). Please review it and advise on any additional elements that need to be added?
I have implemented the following features:
- **CLINT Initialization:** Clears the MSIP (Software Interrupt) and sets MTIMECMP to its maximum value.
Software Interrupt Configuration: Allows configuration of the MSIP by writing a specific value (0 or 1) to its address.
- **MTIMECMP Register:** Sets the MTIMECMP register to the provided 64-bit value.
- **MTIME Retrieval**: Reads and returns the current value of MTIME.
> drivers: interrupt: Implement RISC-V CLINT for Interrupt Control and Timer Management.

- src/arch/Mybuild
- src/arch/generic/Mybuild
- src/arch/x86/include/asm/gdt.h
- src/arch/x86/include/asm/linkage.h
- src/arch/x86/kernel/smp/Mybuild
- src/arch/x86/kernel/smp/ap_trampoline.S
- src/arch/x86/kernel/smp/smp.c
add max_sipported_cores option to allocate __AP_SP size for user to config
> arch: Add max_supported_cores option in smp module

- src/drivers/interrupt/riscv_clint/Mybuild
This PR corrects the base address format in the riscv_clint module. The previous format used '0X2000000', which has been changed to '0x2000000' to adhere to proper hexadecimal notation.
> fix: Correct base address format in riscv_clint module

- src/include/sys/cdefs.h
Openlib uses non-standard macro `__strong_alias`:
```c
#if  LDBL_MANT_DIG == DBL_MANT_DIG
__strong_alias(cpowl, cpow);
#endif  /* LDBL_MANT_DIG == DBL_MANT_DIG */
```
It's not defined for gcc, so I get compilation error
```
src/s_cpow.c:77:1: warning: data definition has no type or storage class
77 | __strong_alias(cpowl, cpow);
| ^~~~~~~~~~~~~~
src/s_cpow.c:77:1: error: type defaults to 'int' in declaration of '__strong_alias' [-Wimplicit-int]
src/s_cpow.c:77:1: error: parameter names (without types) in function declaration **[-Wdeclaration-missing-parameter-type]**
```
Let's juse reuse the same macro for clang
> __strong_alias for all the compilers

- src/arch/riscv/pmp/Mybuild
- src/arch/riscv/pmp/pmp.c
- src/arch/riscv/pmp/pmp.h
- templates/riscv/qemu/mods.conf
- Implement PMP initialization and configuration functions
- Support for TOR, NA4, and NAPOT entry types
- Provide utility functions for PMP register access
This driver enables memory protection on RISC-V systems to enhance security. Tested with the riscv/qemu template.
Please review and suggest any required changes.
> Add RISC-V PMP Driver for Memory Protection

- src/arch/riscv/pmp/pmp.c
- src/arch/riscv/pmp/pmp.h
1. Removed the unnecessary code for manually clearing PMP registers, as it disrupted existing configurations and was found to be redundant.
2. Deleted the pmp_init function declaration from the header file, since it is initialized using EMBOX_UNIT_INIT(pmp_init) and does not need to be exposed in the header.
3. Changed the functions definition of write_pmpcfg and write_pmpaddr from static inline to public to enable its use outside the .c file by including the .h file.
> Fix: PMP Module (Update PMP Register Management and API Declaration)

- src/arch/x86/kernel/smp/smp.c
- src/drivers/interrupt/apic/ioapic.c
- src/drivers/interrupt/apic/ioapic.h
- src/drivers/interrupt/apic/lapic.c
- src/drivers/interrupt/apic/lapic.h
Previous physical destination mode is not good in SMP system, because physical mode could only delivey inerrupt to one CPU once a time.
> driver:interrupt: Change apic to logical dest mode

- src/kernel/lthread/lthread.h
if not set type explicitly, the default type is SCHEDEE_THREAD
In that case, it always attemp to context_switch
> kernel:lthread: Add static lthread schedee type

- mk/main-stripping.sh
macOS 14.5 seems not support the order version definition.
> mk: Replace the definition method of CXX_CMD macro

- src/arch/riscv/pmp/test_pmp/test_pmp.c
- templates/riscv/qemu/mods.conf
This PR addresses an issue in the PMP test case where checks involving registers (REG32_LOAD) were causing errors. Since the set_pmp_entry function only computes values for pmp_addr and pmp_cfg without setting the registers, the checks for register values are redundant and unnecessary.
The existing assertions (test_assert_equal(pmp_addr[0], base >> 2); and test_assert_equal(pmp_cfg[0], flags);) are sufficient for validating the function's behavior. This PR removes the redundant checks to prevent errors.
Changes:
Removed unnecessary REG32_LOAD checks in the PMP test case.
Re-added test suite into riscv/qemu template 
Changes have been tested using the riscv/qemu template to ensure correctness:
> riscv:Fix PMP_Test suite

- src/include/drivers/irqctrl.h
With smp support, the meaning of irq APIs is somewhat unclear. Please discuss further and come up with a more reasonable API.
And do we really need the `irqctrl_eoi_in_cpu` API. I think we can include the self CPUID information when calling the `irqctrl_eoi` function. SInce each CPU only needs to send its own eoi signal. There seems to be no situation where CPU 1 needs to send the eoi signal instead of CPU 2.
> drivers: Describes irqctrl APIs in more detail

- src/arch/x86/kernel/irq_handler.c
- src/tests/smp/Mybuild
- src/tests/smp/simult_thread_test.c
- src/tests/smp/test_smp.c
- templates/x86/smp/build.conf
- templates/x86/smp/mods.conf
- templates/x86/smp/system_start.inc
- Currently SMP on x86 arch can set affinity to specify which CPU to execute. Two may running simultaneously and individually or one is in `idle` and another is running thread. The latter may occur when set all threads' affinities to one CPU.
- Each CPU can handle interrupt individually, which can be set in `startup_ap()`. Only clock interrupt is be set in this PR. 
Comments on any commit are welcome!
> Prepare Multiprocessor on x86 arch with testing modules

- src/tests/smp/simult_thread_test.c
`<asm/ap.h>` is only exsit in x86 currently
> tests: remove unused header file

- src/arch/riscv/kernel/context_switch.S
When thread is created, original context contains a sp which points to next thread. The addtional modification to sp register will cause memory leaking when context switching, which will change the data belongs to next thread.
> arch:riscv: Fix context_switch bug

- src/kernel/sched/sched.c
In some archs such as RISCV, dereferencing NULL will crash. But in some case, x86 will not.
When `runq_get_next()` returns NULL,  which means there is no other threads in `rq` queue. So we can just delete the `sched_timer` for the only thread to run.
> kernel: Add case that runq_get_next returns 0

- src/arch/x86/kernel/smp/smp.c
The smp_send_resched function is mainly used in sched_tick handler which gives up current thread by force and find a new thread to run. But when one cpu want to give up current thread by itself doesn't means other cpus also want to give up current thread that runs on other cpus
> arch:x86: change the smp_send_resched function

- src/include/kernel/sched/runq.h
- src/kernel/sched/strategy/runq/list_array.c
In smp system, it's useful to know whether is really empty in rq or just because of affinity to get an NULL result
> sched: Add API of get schedee with no affinity

- src/kernel/sched/sched_ticker.c
Put sched_post_switch after sending resched signal because sched_post_switch may switch to another thread which delays the resched signal.
It's no need to send resched signal to self_cpu
> kernel:sched: Improve sched_tick function in smp

- src/arch/x86/kernel/smp/smp.c
- src/include/kernel/sched.h
- src/include/kernel/time/timer.h
- src/kernel/sched/Mybuild
- src/kernel/sched/sched.c
- src/kernel/sched/sched_ticker.c
- src/kernel/time/timer/strategy/Mybuild
- src/kernel/time/timer/strategy/head_timer_smp.c
- src/kernel/time/timer/sys_timer.c
In the previous situation, each CPU would interfere with each other during timer scheduling. Timer sharing was introduced in this PR to solve this problem.
> Improve system timer strategy for smp

- src/arch/Mybuild
- src/arch/generic/Mybuild
- src/arch/riscv/kernel/smp/Mybuild
- src/arch/x86/kernel/smp/Mybuild
- src/kernel/time/clock_tick.c
In some SMP cases, each CPU has a complete independent clock. In order to prevent scheduling frequency changes as the number of CPUs increase.
> kernel:time: Add SMP jiffies tick increasing rule

- src/include/kernel/irq.h
- src/kernel/irq/irq.c
- src/kernel/irq/static_irq/irq_static.c
This is one way to enable all registered interrput source in AP. I'm not sure if the method is good, if someone  come up better  way, please give me a suggestion
> kernel:irq: Add function of enable attached IRQs

- src/arch/x86/kernel/smp/ap_trampoline.S
- src/arch/x86/kernel/smp/smp.c
1. Allow more than two cpus
2. Allow each cpu handles all events independently after calling `irq_enable_attached()`
> improve x86 in smp case one step further

- src/arch/riscv/mmu/mmu.c
- src/arch/riscv/mmu/mmuinfo.c
- templates/riscv/qemu/mods.conf
- Enhanced the `mmu_set` function for RISC-V architecture.
- Implemented `mmuinfo.c` to provide MMU register information.
- Tested with riscv/qemu template to ensure compatibility and functionality.
> riscv: Improve RISC-V MMU Support

- src/arch/riscv/mmu/mmu.h
- src/arch/riscv/mmu/test/Mybuild
- src/arch/riscv/mmu/test/test_mmu.c
This PR introduces a test suite to validate the RISC-V MMU functionality, specifically testing the following:
- Enabling the MMU with one-to-one address mapping.
- Verification that the SV39 mode is enabled in the SATP register.
- Ensures that mapped pages are present and correctly configured.
The test suite is properly commented for better understanding of the RISC-V MMU module usage and has been successfully compiled.
> riscv: Add MMU test suite

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/expm1_test.c
- templates/x86/test/units/mods.conf
Added unit tests for `expm1()` in `src/compat/libc/math/tests`. Closes https://github.com/embox/embox/issues/3454
> TST: Add test for `expm1()` in libc tests

- src/arch/mips/kernel/exc_init.c
- src/drivers/interrupt/mips_intc/mips_intc.c
1. c0 EBase may be remapped by bootloader, so explisctly set it to KSEG0.
2. Improvement in interrupt handling:
- mask out unwanted interrupts;
- set higher priority for higher interrupt number.
> mips: correct general exception vector setting and some improvement in interrupt processing

- platform/ralink/templates/rt5350/build.conf
- platform/ralink/templates/rt5350/lds.conf
- platform/ralink/templates/rt5350/mods.conf
- platform/ralink/templates/rt5350/rootfs/network
- platform/ralink/templates/rt5350/start_script.inc
- src/arch/mips/mm/mips_cache.c
- src/drivers/diag/ralink_diag/Mybuild
- src/drivers/diag/ralink_diag/board_diag.c
1. Module *mips_cache* was corrected to use predefined values for data and instruction cache line size.
2. Added ralink diag port driver and new platform **ralink**
> mips: correct mips_cache and add Ralink SoC platform

- platform/ralink/templates/rt5350/mods.conf
- src/cmds/hardware/mem/mem.c
- src/drivers/interrupt/ralink_intc/Mybuild
- src/drivers/interrupt/ralink_intc/ralink_intc.c
- src/drivers/interrupt/ralink_intc/ralink_intc.h
I've added Ralink SoC interrupt controller support and build config to use it imstead of mips INTC.
> mips: ralink: add ralink SoC interrupt controller

- platform/ralink/templates/rt5350/mods.conf
- src/arch/mips/kernel/reg/mmap_reg.h
- src/drivers/serial/ns16550/ns16550.c
1. Fix load/store macros to work correctly for addr from any segment.
2. Add Ralink register layout into uart ns16550 driver.
3. Switch to standard uart ns16550 driver in config.
> platform: ralink: add support into uart ns16550 driver

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/acosh_test.c
- templates/x86/test/units/mods.conf
add checks to validate the functioning of acosh across various test cases.
closes #3502
> math/tests: add acosh unit test

- src/drivers/clock/riscv_clk/Mybuild
- src/drivers/clock/riscv_clk/riscv_timer_clint.c
Some vendors get riscv clocksource from CSR TIME, better to make an abstraction.
> drivers: clock: make riscv_clk an abstract module

- src/drivers/net/tun/tun.c
fix the memory leak in tun_dev_read by adding skb_free and race condition in tun_xmit by adding lock to the code that accesses queue
> Tun: fix memory leak and race condition

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/frexp_test.c
- templates/x86/test/units/mods.conf
for issue #3332 
Test case successfully executed.
> issue #3332: Add tests for frexp() from math.h

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/remainder_test.c
- templates/x86/test/units/mods.conf
This pull request implements unit tests for the `remainder()` function from `math.h`, addressing issue [#3594](https://github.com/embox/embox/issues/3594).
Changes Introduced -
- Created a new test file: `remainder_test.c`
- Added test cases covering:
- Positive and negative input values
- Zero as the dividend
- Registered the test in `mods.conf` under the `x86` architecture
> Add unit tests for math.h remainder() function

- board_config/nucleo_f429zi.conf.h
For #2842 
Firstly, According to the user manual [https://www.st.com/resource/en/user_manual/um1974-stm32-nucleo144-boards-mb1137-stmicroelectronics.pdf](url), A total of 7 USART6 field information were queried, with USART_SA_TX pointing to PG14 and USART_SA_RX pointing to PG14.
Secondly, [https://www.st.com/resource/en/datasheet/stm32f429zi.pdf](url) query  shows:PG14: AF8 = USART6_TX, PG9: AF8 = USART6_RX
Finally, my personal thoughts are that in the future, if device trees are supported, pin and clock information can be directly modified in DTS files without recompiling, and the scalability will be better.
Thank you for your guidance. I will continue to follow Embox
> Change the UART 6 pins and clock source

- src/cmds/service/service.c
This pull request corrects a small typo in a `printf` output string to improve clarity. No functional changes were made.
> [Minor]: Fix spelling error in printf statement.

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/tgamma_test.c
- templates/x86/test/units/mods.conf
Hi, this is my first PR, please advise me if there are any deficiencies. 
Completed testing of tgamma() based on x86. 
I've noticed that the openlibm currently used by embox seems to be a bit undefined.
``` 
Errors are reported as specified in math_errhandling.
For IEEE-compatible type double, overflow happens if 0 < x < 1/[DBL_MAX] or if x > 171.7.  
If a range error due to overflow occurs, [±HUGE_VAL], ±HUGE_VALF, or ±HUGE_VALL is returned.
POSIX requires that a pole error occurs if the argument is zero, but a domain error occurs when the argument is a negative integer
```
However, errno is not set to ERANGE in the case of an overflow, nor is it set to EDOM when the parameter is a negative integer.
Considering RTOS might trim some standard library features for performance, I commented …
> Add tests for tgamma() from math.h

- src/arch/riscv/kernel/Mybuild
This fixed:
https://github.com/embox/embox/actions/runs/15211776776/job/42787425755
> riscv: Fix kernel sbi defconfig reversing

- .gitignore
- board_config/dts/dummy.dts
- scripts/mkiso.sh
- scripts/uboot-uimage
uboot-uimage is mainly used for u-boot `bootm` command
mkiso.sh is mainly used to enable qemu to identify and load the kernel and dtb in ISO through virtio.
> Add image scripts for creating uImage and ISO Image

- src/include/net/l3/ipv4/ip.h
- src/net/l3/ipv4/ip_input.c
Completes a TODO task in the Embox RTOS networking stack by refactoring the declaration of `ip_forward()`:
- Removed `ip_forward()` declaration from `ip.h`.
- Added the correct declaration in `ip_input.c`, where the function is used.
- Avoids confusion and redundancy since `ip_output.c` already includes a different declaration with more parameters.
> Refactor: Move ip_forward() declaration from ip.h to ip_input.c

- src/compat/posix/include/signal.h
- src/compat/posix/proc/signal/signal.c
signal: enforce POSIX SIGKILL/SIGSTOP rules
- Reject handler setup for SIGKILL/SIGSTOP with EINVAL
- Remove incorrect errno setting in signal()
Fixes #3532
> Enforce POSIX SIGKILL/SIGSTOP rules

- README.md
When building on debian an error occur because the compilation script wants to use `python` but under debian `python` is not present. 
To fix this i added the `python-is-python3` dependency that creates a symlink to point the `/usr/bin/python` interpreter at the current default `python3`.
with this the compilation is successful.
Another way to fix this is to change the compilation scripts but is more invasive.
> docs: add debian dependency python-is-python3 in README

- templates/aarch64/qemu/build.conf
There was problem (Alignment Fault) with starting embox with qemu-system-aarch64 (on mac m1). 
Added flag -mstrict-align in build.conf for 16 byte register address alignment.
> add flag for 16 byte register address alignment

- third-party/lib/lvgl/Makefile
- third-party/lib/lvgl/lv_demos/Makefile
There was a problem(arm-none-eabi-gcc: error: unrecognized command-line option '-arch'; did you mean '-march='?)  when making the lvgl library on a Mac M1.
This problem was solved by adding the '-D CMAKE_SYSTEM_NAME=Generic' flag to the Makefile.
> Add flag for making lvgl library 

- src/compat/libc/math/tests/Mybuild
- src/compat/libc/math/tests/erfc_test.c
- templates/x86/test/units/mods.conf
In this pull request, unit tests were added for the erfc() method from math.h
Changes:
1. Added test module in `src/compat/libc/math/Mybuild`
```
module erfc_test {
@Cflags("-fno-builtin")
source "erfc_test.c"
}
```
2. Added tests covering corner cases, including +Inf, -Inf, NaN and Zero. All tests are implemented within new file `src/compat/libc/math/tests/erfc_test.c`
3. Updated configure in file `templates/x86/test/units/mods.conf`
> Added tests for erfc() from math.h
